### ISSUE TITLE
Race condition when deploying bpmn - Error: 5 NOT_FOUND

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#5648] opened 2020-10-21 07:58 UTC
**Describe the bug**

There seems to be a race condition when deploying bpmn. Intermittently, I get the following error when immediately creating an instance after deploying the definition:
```
Error: 5 NOT_FOUND: Expected to execute command, but this command refers to an element that doesn't exist.
```

**To Reproduce**
To get this, I deploy the model using the Node client, and await the response from the server with the workflow key. 

I then immediately create an instance of the workflow. 

Periodically, it will return the Error 5 NOT_FOUND.

**Expected behavior**
I expect that if I get back the response from the gateway about the deployment then I can create an instance.

**Environment:**
 - OS: Docker
 - Zeebe Version: 0.24.2
 - Configuration: Out of the box Docker run

**Comment by Zelldon** [comment] 2020-10-21 08:03
This is not a bug, this is currently the expected behavior. If you deploy a workflow it will create it on the partition one, and start to distribute it to the other partitions. The response to the client is send back already before the distribution is done. If you create a workflow instance, it is very likely that this happens on the other partitions, since the gateway does it round robin. This means it is likely to fail if you do it shortly after the deployment.

For me this looks like an duplicate of https://github.com/zeebe-io/zeebe/issues/5474, which is why I will close this.

Greets
Chris

**Closed by Zelldon** 2020-10-21 08:03 UTC
Labels: Status: Needs Triage, Type: Bug
