### ISSUE TITLE
IllegalStateException: Iterator is closed (ProcessingStateMachine)

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5877] opened 2020-11-19 09:05 UTC
**Describe the bug**
Observed in production logs
https://console.cloud.google.com/errors/CLK1nPmOxuLIjwE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
Nov 13Nov 14Nov 15Nov 16Nov 17Nov 18Nov 19, 9:58 AM0111
Stack trace sample
java.lang.IllegalStateException: Iterator is closed

        at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.hasNext (LogStreamReaderImpl.java:159)
        at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent (ProcessingStateMachine.java:199)
        at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent (ProcessingStateMachine.java:194)
        at io.zeebe.util.sched.ActorJob.invoke (ActorJob.java:73)
        at io.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
        at io.zeebe.util.sched.ActorTask.execute (ActorTask.java:122)
        at io.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:107)
        at io.zeebe.util.sched.ActorThread.doWork (ActorThread.java:91)
        at io.zeebe.util.sched.ActorThread.run (ActorThread.java:204)
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.25.1
 - Configuration: Camunda Cloud

**Comment by pihme** [comment] 2020-11-19 09:10
Sequence of Events:
* Variable with some key was too big to be inserted into Elasticsearch Index
* Failed to append block with last event position 10176855.
* Actor Broker-0-LogAppender-1 failed in phase STARTED.
* Close appender for log stream logstream-raft-partition-partition-1
* logstream-raft-partition-partition-1 failed, marking it as unhealthy
* Partition-1 failed, marking it as unhealthy
* On closing logstream logstream-raft-partition-partition-1 close 3 readers
* Close log storage with name logstream-raft-partition-partition-1
* **THIS IS THE ERROR** Actor Broker-0-StreamProcessor-1 failed in phase STARTED.
* Broker-0-StreamProcessor-1 failed, marking it as unhealthy
* Exporter closed
* Partition-1 recovered, marking it as healthy
* + 8 minutes normal log
* Closing Broker-0 [1/14]: upgrade manager

So it had a hiccup and it recovered.

**Comment by Zelldon** [comment] 2020-11-26 15:19
duplicate of https://github.com/zeebe-io/zeebe/issues/5504 the root cause and solution is the same

**Closed by Zelldon** 2020-11-26 15:19 UTC
Labels: Impact: Observability, Severity: Low, Type: Bug
