### ISSUE TITLE
Scheduler: ActorControl#run should validate current actor

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#681] opened 2018-02-27 09:59 UTC
When calling actor#run, it should be made sure that the called actor is the same as the calling actor, or else actor jobs from the called actor are executed in the context of the calling actor introducing unexpected concurrency.

We have this issue in zb-transport `Conductor#onChannelClosed` which is called by various actors.

**Comment by menski** [comment] 2018-03-05 10:06
kind of duplicate of #682

**Closed by menski** 2018-03-05 10:06 UTC
Labels: bug, ready, util
