### ISSUE TITLE
inconsistency cluster state 

### ISSUE THREAD

**Issue by heytong** [zeebe-io/zeebe#3851] opened 2020-02-17 03:58 UTC
zeebe version: 0.22.1

Cluster size: 4
Partitions count: 3
Replication factor: 3

After killing the zeebe processes on two machines, start again.A cluster state inconsistency has occurred. 

./bin/zbctl status  --address 172.17.41.150:26500 --insecure
Cluster size: 4
Partitions count: 3
Replication factor: 3
Brokers:
  Broker 0 - 172.17.41.140:26501
    Partition 1 : Follower
    Partition 3 : Follower
  Broker 1 - 172.17.41.141:26501
    Partition 1 : Follower
    Partition 2 : Follower
  Broker 2 - 172.17.41.142:26501
    Partition 1 : Leader
    Partition 2 : Leader
    Partition 3 : Leader
  Broker 3 - 172.17.41.150:26501
    Partition 2 : Follower
    Partition 3 : Follower

./bin/zbctl status  --address 172.17.41.141:26500 --insecure
Cluster size: 4
Partitions count: 3
Replication factor: 3
Brokers:
  Broker 0 - 172.17.41.140:26501
    Partition 1 : Follower
    Partition 3 : Follower
  Broker 1 - 172.17.41.141:26501
    Partition 1 : Leader
    Partition 2 : Follower
  Broker 2 - 172.17.41.142:26501
    Partition 1 : Follower
    Partition 2 : Leader
    Partition 3 : Leader
  Broker 3 - 172.17.41.150:26501
    Partition 2 : Follower
    Partition 3 : Follower

**Comment by heytong** [comment] 2020-02-17 06:09
and go on,  kill the "Broker 1" , all brokers status is Consistent. but I kill the  "Broker 2", then start again, one leader  lost:

Cluster size: 4
Partitions count: 3
Replication factor: 3
Brokers:
  Broker 0 - 172.17.41.140:26501
    Partition 1 : Leader
    Partition 3 : Follower
  Broker 1 - 172.17.41.141:26501
    Partition 1 : Follower
    Partition 2 : Follower
  Broker 2 - 172.17.41.142:26501
    Partition 1 : Follower
    Partition 2 : Leader
    Partition 3 : Follower
  Broker 3 - 172.17.41.150:26501
    Partition 2 : Follower
    Partition 3 : Follower

**Comment by heytong** [comment] 2020-02-17 06:21
[Broker-3-ZeebePartition-3] [Broker-3-zb-actors-1] ERROR io.zeebe.broker.system - Failed to install leader partition 3
java.lang.IllegalStateException: Expected to find event with the snapshot position 2581277078632 in log stream, but nothing was found. Failed to recover 'Broker-0-StreamProcessor-3'.

**Comment by Zelldon** [comment] 2020-02-17 08:23
Hey @heytong,

thanks for your report.

Is there a specific reason why you're using a cluster size of 4?
It can happen that the topology is from time to time not consistent, because it is eventually consistent. This means at some point in time they should show all the same topology but it can happen that they don't.
We fixed also some issues lately with the topology maybe you want to try the latest alpha.



```
[Broker-3-ZeebePartition-3] [Broker-3-zb-actors-1] ERROR io.zeebe.broker.system - Failed to install leader partition 3
java.lang.IllegalStateException: Expected to find event with the snapshot position 2581277078632 in log stream, but nothing was found. Failed to recover 'Broker-0-StreamProcessor-3'.
```
This sounds like a bug. Is this reproducible? Would it be possible that you share your data folder, which contains the snapshots and raft-partitions. This would make it easier to investigate this issue.

**Comment by npepinpe** [comment] 2020-02-26 20:36
It sounds like your topology was missing a leader on partition 3 because of this bug as none of them managed to recover. In that case, sounds like this is more of an issue related to #3920, so I will close this in favor of that issue as we're already working on it.

**Closed by npepinpe** 2020-02-26 20:36 UTC
Labels: Type: Bug
