### ISSUE TITLE
Exception when a message is delivered to two waiting workflow instances

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#1440] opened 2018-10-09 06:19 UTC
As discussed on Slack my current hypothesis is that the following exception occurs when one message is correlated to more than one waiting workflow instance.

I can reproduce that in my flowing-retail example (run https://github.com/berndruecker/flowing-retail/tree/master/kafka/java/order-zeebe and https://github.com/berndruecker/flowing-retail/tree/master/kafka/java/choreography-alternative/zeebe-track via Kafka Connect at the same time) but did not yet create a stripped down test case to prove it.

```
java.lang.ArrayIndexOutOfBoundsException: null
	at java.lang.System.arraycopy(Native Method) ~[?:1.8.0_131]
	at org.agrona.ExpandableArrayBuffer.getBytes(ExpandableArrayBuffer.java:381) ~[agrona-0.9.24.jar:0.9.24]
	at io.zeebe.broker.subscription.message.state.Message.readIntoBuffer(Message.java:131) ~[zeebe-broker-core-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.broker.subscription.message.state.MessageSubscription.wrap(MessageSubscription.java:124) ~[zeebe-broker-core-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.broker.subscription.message.state.MessageStateController.getSubscription(MessageStateController.java:171) ~[zeebe-broker-core-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.broker.subscription.message.state.MessageStateController.lambda$findSubscriptionBefore$2(MessageStateController.java:220) ~[zeebe-broker-core-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.logstreams.state.StateController.foreach(StateController.java:429) ~[zb-logstreams-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.broker.subscription.message.state.MessageStateController.findSubscriptionBefore(MessageStateController.java:211) ~[zeebe-broker-core-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.broker.subscription.message.processor.PendingMessageSubscriptionChecker.run(PendingMessageSubscriptionChecker.java:46) ~[zeebe-broker-core-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
```

**Comment by Zelldon** [comment] 2018-10-10 13:07
Was able to reproduce this and we found the problem. I will create an PR to fix this. 

Since this issue references an old version Zeebe version, I will close this. For updates please see #1469

**Closed by Zelldon** 2018-10-10 13:07 UTC
Labels: broker, bug
