### ISSUE TITLE
First OOM kill that created heap dumps and filled the broker disk

### ISSUE THREAD

**Issue by hisImminence** [zeebe-io/zeebe#4848] opened 2020-06-29 13:53 UTC
Hello there, our first heap dumps due to OOM :1st_place_medal:  

As the `L cluster` on `int` stage fired a `disk-full-alert`, @zoltan realized it might be due to the OOM dumps :)  We had a look and the disk is full of fresh, tasty heap dumps :+1:  
The first OOM was on the [2020-06-28 at 18:07](https://console.cloud.google.com/logs/viewer?project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-06-28T16%3A05%3A40.000000000Z&customFacets&limitCustomFacetWidth=true&interval=JUMP_TO_TIME&resource=k8s_container%2Fcluster_name%2Fultratest%2Fnamespace_name%2F8235f864-3a5b-4cbe-a9f6-a335d478fb26-zeebe%2Fcontainer_name%2Fzeebe&scrollTimestamp=2020-06-28T16%3A07%3A31.148622211Z&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%228235f864-3a5b-4cbe-a9f6-a335d478fb26-zeebe%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-3%22%0Atimestamp%3D%222020-06-28T16%3A07%3A31.148622211Z%22%0AinsertId%3D%22m242uhpwcj3uguct6%22).
Each dump has about ~3,7 to 4 Gi, so that after 15 restarts the disk is full.

Have a look on the [disks][pvc-dash].

Follow this steps to get the heap dumps:

1. `k exec -it -n 8235f864-3a5b-4cbe-a9f6-a335d478fb26-zeebe zeebe-1 /bin/bash`
2.  Open the `data`-folder and list heap dumps
```
root@zeebe-1:/usr/local/zeebe# cd data && ls
java_started_1593360171.hprof  java_started_1593367274.hprof  java_started_1593383043.hprof  java_started_1593406161.hprof
java_started_1593361379.hprof  java_started_1593370371.hprof  java_started_1593384713.hprof  lost+found
java_started_1593362650.hprof  java_started_1593371959.hprof  java_started_1593386514.hprof  raft-partition
java_started_1593364198.hprof  java_started_1593379702.hprof  java_started_1593403252.hprof  system
java_started_1593365737.hprof  java_started_1593381367.hprof  java_started_1593404632.hprof
```

Select the dump you want to inspect and copy it to your local `/tmp` folder:
`k cp 8235f864-3a5b-4cbe-a9f6-a335d478fb26-zeebe/zeebe-1:data/java_started_1593360171.hprof /tmp/8235f864-3a5b-4cbe-a9f6-a335d478fb26-zeebe/java_started_1593360171.hprof`

[pvc-dash]:https://grafana.internal.ultrawombat.com/d/KaItfrEWz2/pvc-disk-usage?orgId=1&refresh=30s&var-persistentvolumeclaim=All&var-namespace=8235f864-3a5b-4cbe-a9f6-a335d478fb26-zeebe

**Comment by npepinpe** [comment] 2020-06-30 07:37
First step is to root cause this, and once we know what's going on then let's reprioritize this.

**Comment by npepinpe** [comment] 2020-07-03 11:49
First glance seems to be mostly scheduled tasks, so timer related things which are triggered but not processed?

Seems related to https://github.com/zeebe-io/zeebe/issues/4871

**Comment by npepinpe** [comment] 2020-07-03 11:51
Looks like it's an issue in the Gossip Executor

![Screenshot from 2020-07-03 13-51-32](https://user-images.githubusercontent.com/43373/86466674-57f75f00-bd34-11ea-98aa-159605c9de81.png)

**Comment by npepinpe** [comment] 2020-07-07 14:32
This should be fixed by https://github.com/zeebe-io/zeebe/pull/4781

**Closed by npepinpe** 2020-07-07 14:32 UTC
Labels: Impact: Availability, Priority: High, Scope: broker, Scope: gateway, Status: Ready, Type: Maintenance

**Comment by hisImminence** [comment] 2020-07-09 11:32
@npepinpe, quick question - how should we proceed with the cluster as it 3 crash-looping brokers (i assume due to their full disks) :) 

should we just delete this one and create a new one?
waiting for the fix and update the cluster as soon as 24.0 is out and free its disc space?
...?

**Comment by npepinpe** [comment] 2020-07-09 16:18
As you want. It'll be upgraded on Monday, so we could delete the dumps then and see if it recovers in the new version, but I'm also fine if you recreate it before (in case it's causing alerts or any other annoying issues for you).

**Comment by hisImminence** [comment] 2020-07-20 09:52
Just to let you know - we just moved the cluster and created a new one :rocket:
