### ISSUE TITLE
NoSuchElementException: Expected an appender, but none found, most likely we are not the leader

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5547] opened 2020-10-08 12:20 UTC
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CKKIzPGP0MfPpQE?service=zeebe&time=P7D&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.NoSuchElementException: Expected an appender, but none found, most likely we are not the leader
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorage.append(AtomixLogStorage.java:57) ~[zeebe-logstreams-0.23.4.jar:0.23.4]
	at io.zeebe.logstreams.impl.log.LogStorageAppender.appendToStorage(LogStorageAppender.java:129) ~[zeebe-logstreams-0.23.4.jar:0.23.4]
	at io.zeebe.logstreams.impl.log.LogStorageAppender.appendBlock(LogStorageAppender.java:115) ~[zeebe-logstreams-0.23.4.jar:0.23.4]
	at io.zeebe.logstreams.impl.log.LogStorageAppender.onWriteBufferAvailable(LogStorageAppender.java:169) ~[zeebe-logstreams-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.4.jar:0.23.4]
```

</p>
</details>

**Environment:**
Camunda Cloud / Prod / 0.23.4, 0.23.6

**Comment by pihme** [comment] 2020-11-17 09:32
Wrong log level.

**Comment by npepinpe** [comment] 2020-11-23 08:40
Duplicate of https://github.com/zeebe-io/zeebe/issues/5541

**Closed by npepinpe** 2020-11-23 08:40 UTC
Labels: Impact: Observability, Severity: Mid, Status: Needs Priority, Type: Bug
