### ISSUE TITLE
java.lang.IllegalStateException: Expected the active token count to be positive but was -1

### ISSUE THREAD

**Issue by strawhat5** [zeebe-io/zeebe#5251] opened 2020-08-27 12:44 UTC
**Describe the bug**
We have come across a major issue in a couple of our clusters today. We upgraded 2 of our clusters to `0.24.2` and post the upgrade we have started seeing this error continuously.
```
2020-08-27 03:40:16.390 [Broker-2-StreamProcessor-3] [Broker-2-zb-actors-0] [31mERROR[m io.zeebe.util.retry.EndlessRetryStrategy - Catched exception class java.lang.IllegalStateException with message Expected the active token count to be positive but was -1, will retry...
```
Because of this endless retry, the new requests coming to the gateway are getting dropped. And the CPU is running at over 100% capacity.

**To Reproduce**
Not sure. We upgraded one of our cluster from `0.23.2` to `0.24.2`, and the other one from `0.23.4` to `0.24.2`. Post that we started seeing this error. We have downgraded one of our cluster back to `0.23.4`, but the issue is persisting. Not sure if it is an issue because of `0.24.2` or our data is corrupted.

**Expected behavior**
Workflows should be completed without any error.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2020-08-27 03:40:16.390 [Broker-2-StreamProcessor-3] [Broker-2-zb-actors-0] [31mERROR[m io.zeebe.util.retry.EndlessRetryStrategy - Catched exception class java.lang.IllegalStateException with message Expected the active token count to be positive but was -1, will retry...
java.lang.IllegalStateException: Expected the active token count to be positive but was -1
	at io.zeebe.engine.state.instance.ElementInstance.consumeToken(ElementInstance.java:128) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.nwe.sequenceflow.SequenceFlowProcessor.lambda$joinOnParallelGateway$3(SequenceFlowProcessor.java:135) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at io.zeebe.engine.nwe.sequenceflow.SequenceFlowProcessor.joinOnParallelGateway(SequenceFlowProcessor.java:130) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.nwe.sequenceflow.SequenceFlowProcessor.onSequenceFlowTaken(SequenceFlowProcessor.java:93) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.nwe.sequenceflow.SequenceFlowProcessor.onActivating(SequenceFlowProcessor.java:52) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.nwe.sequenceflow.SequenceFlowProcessor.onActivating(SequenceFlowProcessor.java:30) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.nwe.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:156) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.nwe.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:122) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.workflow.BpmnStepHandlers.handle(BpmnStepHandlers.java:90) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.workflow.BpmnStepProcessor.processRecordValue(BpmnStepProcessor.java:82) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.workflow.BpmnStepProcessor.processRecord(BpmnStepProcessor.java:62) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:48) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$chooseOperationForEvent$5(ReProcessingStateMachine.java:287) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$processUntilDone$2(ReProcessingStateMachine.java:262) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.2.jar:0.24.2]
```

</p>
</details>

**Environment:**
 - Zeebe Version: 0.24.2
 <details><summary>Configuration</summary>
 <p>

```
Starting broker 2 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "dev-zeebe-zeebe-broker-2.dev-zeebe-zeebe-broker.dev.svc.cluster.local",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 26501,
      "advertisedHost" : "dev-zeebe-zeebe-broker-2.dev-zeebe-zeebe-broker.dev.svc.cluster.local",
      "advertisedPort" : 26501,
      "address" : "0.0.0.0:26501",
      "advertisedAddress" : "dev-zeebe-zeebe-broker-2.dev-zeebe-zeebe-broker.dev.svc.cluster.local:26501"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 26502,
      "advertisedHost" : "dev-zeebe-zeebe-broker-2.dev-zeebe-zeebe-broker.dev.svc.cluster.local",
      "advertisedPort" : 26502,
      "address" : "0.0.0.0:26502",
      "advertisedAddress" : "dev-zeebe-zeebe-broker-2.dev-zeebe-zeebe-broker.dev.svc.cluster.local:26502"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 9600,
      "advertisedHost" : "dev-zeebe-zeebe-broker-2.dev-zeebe-zeebe-broker.dev.svc.cluster.local",
      "advertisedPort" : 9600,
      "address" : "0.0.0.0:9600",
      "advertisedAddress" : "dev-zeebe-zeebe-broker-2.dev-zeebe-zeebe-broker.dev.svc.cluster.local:9600"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ "dev-zeebe-zeebe-broker-0.dev-zeebe-zeebe-broker.dev.svc.cluster.local:26502", "dev-zeebe-zeebe-broker-1.dev-zeebe-zeebe-broker.dev.svc.cluster.local:26502", "dev-zeebe-zeebe-broker-2.dev-zeebe-zeebe-broker.dev.svc.cluster.local:26502" ],
    "partitionIds" : [ 1, 2, 3 ],
    "nodeId" : 2,
    "partitionsCount" : 3,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-cluster",
    "gossipFailureTimeout" : 10000,
    "gossipInterval" : 250,
    "gossipProbeInterval" : 1000
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/usr/local/zeebe/data" ],
    "logSegmentSize" : "512MB",
    "snapshotPeriod" : "PT15M",
    "logIndexDensity" : 100,
    "atomixStorageLevel" : "DISK",
    "logSegmentSizeInBytes" : 536870912
  },
  "exporters" : {
    "hazelcast" : {
      "jarPath" : "/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar",
      "className" : "io.zeebe.hazelcast.exporter.HazelcastExporter",
      "args" : {
        "port" : 5701,
        "enabledValueTypes" : "DEPLOYMENT,JOB,WORKFLOW_INSTANCE,INCIDENT,TIMER,VARIABLE,MESSAGE,MESSAGE_SUBSCRIPTION,MESSAGE_START_EVENT_SUBSCRIPTION",
        "enabledRecordTypes" : "EVENT",
        "name" : "zeebe-dev",
        "capacity" : 10000,
        "timeToLiveInSeconds" : 300,
        "format" : "protobuf"
      },
      "external" : true
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:26502",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 26502
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M"
}
```

</p>
</details>

**Comment by Zelldon** [comment] 2020-08-27 12:57
Hey @strawhat5 

sorry to hear that. 
Could you please share the related workflow model so we can reproduce this issue.

Greets
Chris

**Comment by strawhat5** [comment] 2020-08-27 13:12
Hey @Zelldon we have quite a few workflows deployed on the cluster, so I am not sure which one is causing the issue. The logs also does not have sufficient information on the BPMN causing this issue. But from these logs, I am thinking that it is happening on a parallel gateway:
```
at io.zeebe.engine.nwe.sequenceflow.SequenceFlowProcessor.lambda$joinOnParallelGateway$3(SequenceFlowProcessor.java:135) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
at java.util.HashMap.forEach(Unknown Source) ~[?:?]
at io.zeebe.engine.nwe.sequenceflow.SequenceFlowProcessor.joinOnParallelGateway(SequenceFlowProcessor.java:130) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
```
Thankfully there is only one workflow where we are using parallel gateway. :) You can refer to it [here](https://gist.github.com/strawhat5/6989098c9e8d4b7fb7bda3dd74a4a779).

**Comment by menski** [comment] 2020-08-28 07:39
Hey @strawhat5, thanks for reporting this issue, as we assume this bug is triggered by the state of your workflow before upgrading it would help us if you could share your `data` directory of the broken partition. Let us know if this would be possible for you.

**Comment by strawhat5** [comment] 2020-08-28 12:10
Hey sure @menski ! Please find it [here](https://drive.google.com/file/d/1Gn8jAX9_2W_gXYus5w7C4BlDZi8pt4yS/view?usp=sharing).

This is the complete data of broker 0, where we are seeing this issue. It is currently leader of 2 partitions, so not sure which partition is having this issue.
```
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 0.24.2
Brokers:
  Broker 0 - alpha-zeebe-zeebe-broker-0.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local:26501
    Version: 0.24.2
    Partition 1 : Follower
    Partition 2 : Leader
    Partition 3 : Leader
  Broker 1 - alpha-zeebe-zeebe-broker-1.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local:26501
    Version: 0.24.2
    Partition 1 : Leader
    Partition 2 : Follower
    Partition 3 : Follower
  Broker 2 - alpha-zeebe-zeebe-broker-2.alpha-zeebe-zeebe-broker.alpha.svc.cluster.local:26501
    Version: 0.24.2
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower
```

I also see some other exceptions on broker 1:
```
2020-08-28 10:12:43.646 [Broker-1-SnapshotDirector-1] [Broker-1-zb-fs-workers-0] [31mERROR[m io.zeebe.logstreams.snapshot - Unexpected error in resolving last processed position.
java.lang.RuntimeException: Actor is closed
	at io.zeebe.util.sched.ActorJob.failFuture(ActorJob.java:166) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorTask.submit(ActorTask.java:98) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorControl.call(ActorControl.java:136) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.StreamProcessor.getLastProcessedPositionAsync(StreamProcessor.java:293) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.broker.system.partitions.impl.AsyncSnapshotDirector.prepareTakingSnapshot(AsyncSnapshotDirector.java:111) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.2.jar:0.24.2]
```

**Comment by strawhat5** [comment] 2020-08-31 09:06
Hey @menski any findings on this?

Both of our clusters are completely stuck on this endless loop. They are rejecting all incoming requests to gateway. We want to avoid tearing down the entire Zeebe cluster and doing a fresh install.

**Comment by menski** [comment] 2020-08-31 14:42
Hi @strawhat5,

yes I was able to reproduce the issue with your data folder. I created the following bug issue for this https://github.com/zeebe-io/zeebe/issues/5268. But at the moment I don't think that there is a easy workaround. We will investigate the root cause of the issue and if possible try to provide a patch release, but that might take a bit. Sorry that I don't have better news

**Comment by strawhat5** [comment] 2020-08-31 15:40
Ah. It is good that atleast the issue could be reproduced. :)

So at the moment, the only available option for us is a fresh install, right @menski ?

**Comment by menski** [comment] 2020-08-31 15:56
Yes, right now I'm not aware of any workaround for you to apply. If you still have the old instances of Zeebe running, you could wait for a new snapshot to be created before upgrading. This should prevent that the parallel gateway is reprocessed, and the bug is triggered.

**Comment by strawhat5** [comment] 2020-08-31 16:43
Understood, that would work for the other Zeebe instances. But I would rather wait for the patch release than update the other instances now. As for the instances which have fallen victim to it, I will tear them down. 😞 

I know Zeebe's current architecture has a tight coupling between the state machine and data. But we should probably look towards decoupling the data (#5236) that Zeebe maintains internally. The fear of losing data is the worst nightmare for users.

Also one question here:
>This should prevent that the parallel gateway is reprocessed, and the bug is triggered.

When you say "_parallel gateway is reprocessed_", do you mean to say the parallel gateway events which were either **not processed** by Zeebe stream processor or **not exported** by the exporter, were impacted?

**Comment by menski** [comment] 2020-09-01 08:31
> When you say "parallel gateway is reprocessed", do you mean to say the parallel gateway events which were either not processed by Zeebe stream processor or not exported by the exporter, were reprocessed and got impacted?

Zeebe has a event sourcing/stream processing approach by writing an event log and processing it to build up a current state of the workflows. To reduce the size of the log to keep and decrease the start up time, Zeebe takes regular snapshots of it's internal state, which is linked to the last event which was processed to reach this state. When Zeebe is now restarted or upgraded the workflow engine reads the last snapshot, and then continues from the corresponding event to read the event log to reprocess or replay the events which where not yet part of the snapshot. In this case the bug seems that the snapshot was taken before the last instance of the parallel gateway process was executed, therefore Zeebe reprocesses the events of that workflow to get an up to date state, and in this reprocessing something is broken.

**Comment by strawhat5** [comment] 2020-09-01 09:04
Easy to understand, thanks for the explanation! :)

**Comment by npepinpe** [comment] 2021-02-05 14:57
Closing as it's related to #5581, and these kind of issues should be resolved in the next release.

**Closed by npepinpe** 2021-02-05 14:57 UTC
Labels: Impact: Availability, Impact: Usability, Scope: broker, Severity: High, Status: Needs Information, Type: Bug
