### ISSUE TITLE
ExporterProcessor should only run if Exporters are configured

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1621] opened 2018-11-02 07:57 UTC
On profiling the performance tests I saw that the ExporterProcessor is running even if I had no exporter configured.

 This seems for me really unnecessary, since all the Records are copied and serialized to JSON on `RecordExporter#wrap` and then simply dropped.

[perftest.zip](https://github.com/zeebe-io/zeebe/files/2541512/perftest.zip)

**Comment by menski** [comment] 2018-11-02 08:04
duplicate of #1371

**Closed by menski** 2018-11-02 08:04 UTC
Labels: enhancement, exporters, planned
