### ISSUE TITLE
Map fails to remove bucket on merging overflow buckets

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#556] opened 2017-11-21 15:40 UTC
During our stability tests we discovered a bug which is triggered during merging of overflow buckets. We also assume that this can trigger other problems (see second stack trace).

```
java.lang.IllegalArgumentException: No bucket in buffer 0 on offset 4
	at io.zeebe.map.BucketBufferArray.removeBucket(BucketBufferArray.java:400) ~[classes/:?]
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergeOverflowBucket(ZbMapBucketMergeHelper.java:295) ~[classes/:?]
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergingBuckets(ZbMapBucketMergeHelper.java:222) ~[classes/:?]
	at io.zeebe.map.ZbMap.remove(ZbMap.java:332) ~[classes/:?]
	at io.zeebe.map.Long2BytesZbMap.remove(Long2BytesZbMap.java:74) ~[classes/:?]
	at io.zeebe.broker.task.map.TaskInstanceMap.remove(TaskInstanceMap.java:74) ~[classes/:?]
	at io.zeebe.broker.task.processor.TaskInstanceStreamProcessor$CompleteTaskProcessor.updateState(TaskInstanceStreamProcessor.java:357) ~[classes/:?]
	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$3(StreamProcessorController.java:348) [classes/:?]
	at io.zeebe.util.state.ComposedState$FailSafeStep.doWork(ComposedState.java:41) ~[classes/:?]
	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63) ~[classes/:?]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:111) [classes/:?]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) [classes/:?]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:125) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:145) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

```
java.lang.IllegalStateException: must call wrap() before
	at io.zeebe.broker.workflow.map.ActivityInstanceMap.ensureRead(ActivityInstanceMap.java:144) ~[classes/:?]
	at io.zeebe.broker.workflow.map.ActivityInstanceMap.setTaskKey(ActivityInstanceMap.java:135) ~[classes/:?]
	at io.zeebe.broker.workflow.processor.WorkflowInstanceStreamProcessor$TaskCreatedProcessor.updateState(WorkflowInstanceStreamProcessor.java:921) ~[classes/:?]
	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$3(StreamProcessorController.java:348) [classes/:?]
	at io.zeebe.util.state.ComposedState$FailSafeStep.doWork(ComposedState.java:41) ~[classes/:?]
	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63) ~[classes/:?]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:111) [classes/:?]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) [classes/:?]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:125) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:145) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by menski** [comment] 2017-11-22 14:04
The map contained in the ZIP file is a snapshot of map contained in a TaskInstanceMap instance. If the map is loaded again and the key `244816600568` is removed the bug is triggered.

[taskinstance.map.244816600568.zip](https://github.com/zeebe-io/zeebe/files/1496196/taskinstance.map.244816600568.zip)


```
private static final int MAP_VALUE_SIZE = SIZE_OF_SHORT + SIZE_OF_INT + SIZE_OF_CHAR * TaskSubscription.LOCK_OWNER_MAX_LENGTH;

@Test
public void foo() throws IOException
{
    final Long2BytesZbMap map = new Long2BytesZbMap(MAP_VALUE_SIZE);

    final ZbMapSerializer serializer = new ZbMapSerializer();
    serializer.wrap(map);
    serializer.readFromStream(new FileInputStream("/tmp/taskinstance.map.244816600568"));

    map.remove(244816600568L);
}
```


```
java.lang.IllegalArgumentException: No bucket in buffer 305 on offset 36676

	at io.zeebe.map.BucketBufferArray.removeBucket(BucketBufferArray.java:400)
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergeBucketWhichHasOverflowBucket(ZbMapBucketMergeHelper.java:320)
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergeOverflowBucket(ZbMapBucketMergeHelper.java:289)
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergingBuckets(ZbMapBucketMergeHelper.java:222)
	at io.zeebe.map.ZbMap.remove(ZbMap.java:332)
	at io.zeebe.map.Long2BytesZbMap.remove(Long2BytesZbMap.java:74)
	at io.zeebe.broker.it.workflow.LargeWorkflowTest.foo(LargeWorkflowTest.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by menski** [comment] 2017-11-22 15:56
Attached is a sequence of put and removes which triggers this bug on an empty task instance map
[map.commands.log.446676941160.buffer0offset4.zip](https://github.com/zeebe-io/zeebe/files/1496640/map.commands.log.446676941160.buffer0offset4.zip)

**Comment by menski** [comment] 2017-11-22 23:40
Okay so the recorded sequence doesn't help us much as it breaks the java compiler if we put it into a test case :tada: 

```
RemoveOverflowTest.java:[31,17] code too large
RemoveOverflowTest.java:[27,8] too many constants
```

**Comment by menski** [comment] 2017-11-22 23:58
@Zelldon I added a test case (https://github.com/zeebe-io/zb-util/commit/0e47ca34f9ee2331aaf9f1aad1d2a088f5daf9b3) based on the map access sequence I collected today on the branch https://github.com/zeebe-io/zb-util/tree/556-remove-overflow. We can use this to debug what happens to the bucket in question during the map access. :nerd_face:

**Comment by Zelldon** [comment] 2017-11-23 07:29
Nice thanks! I will take a look.

**Comment by Zelldon** [comment] 2017-11-23 08:11
OK I thought I fixed the issue (The Test is green), but I still have the wrap exception. Maybe another bug?

**Comment by menski** [comment] 2017-11-23 08:21
Did you pushed the fix on the branch? I could try if I can generate another sequence which triggers this bug.

**Comment by Zelldon** [comment] 2017-11-23 08:28
Ok pushed the changes to the branch. 

Currently the async test case stop's processing after `Completed: 999500` without an error.

**Comment by menski** [comment] 2017-11-23 14:25
With the latest zb-map fixes the test `LargeWorkflowTest#shouldCreateAndCompleteWorkflowInstances` runs successful on my local machine and on the Zeebe server. Good work @Zelldon :balloon:

**Comment by Zelldon** [comment] 2017-11-24 07:26
Yeeah :tada: thanks for your help @menski

**Comment by Zelldon** [comment] 2017-11-24 09:39
Explanation for the Bugs and exceptions:

The exceptions had two root causes;

### First Bug

The first Bucket with ID 0 was merged with himself. Problem was that after merge 
by himself the depth was -1 this means the Bucket is an Overflow bucket. 
Merging also means that the child bucket is ''removed'', which means the bucket count is decremented.
In that case the BucketBuffer with ID 0 has no buckets left, since the add block does not check if a bucket exist there was no problem here. But on the next time when the Block was removed and Merge was triggered again an OverflowBucket should removed (because depth was -1) and the BucketBuffer had no buckets left.

### Second Bug

On Merging of splitted Buckets the Child bucket was not checked if it has Overflow Buckets. The problem only appears if the Overflow Buckets are on another BucketBuffer, since if they in the same BucketBuffer the Child Bucket can't be remove because he is not the last Bucket in the Buffer. 
If the Parent and Child are merge the Overflow Pointer is lost. In that case all values which are located in the OverflowBuckets are lost as well. In that case some key's are not found.

**Closed** 2017-12-05 10:06 UTC
Labels: bug, code, needs review, zb-map
