### ISSUE TITLE
Joining two sub-processes with the same output parameter mapping is non-deterministic

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2410] opened 2019-04-29 14:55 UTC
On the join of two sub-processes, if both sub-processes map a locally scoped variable to the same higher scoped variable, both values seem to be propagated, one overwriting the other.

And it varies which one wins. 

Below, the same workflow produces different results on subsequent executions (it's the value of `FinalResults`:

```
zeebe-split-merge-demo on  master is 📦 v1.0.0 via ⬢ v10.9.0 took 22m 11s 
➜ ts-node split-join-3.ts
[ config-to-payload config-to-payload-worker ] > Ready for config-to-payload... 
[ output output-worker ] > Ready for output... 
SetThreshold2000" input: {"file":true,"threshold":true,"local":true} output: {"threshold":"2000"}
SetThreshold1000" input: {"file":true,"threshold":true,"local":true} output: {"threshold":"1000"}
ProcessFile2" input: {"file":true,"threshold":"2000","local":true} output: {"file":"file2"}
ProcessFile1" input: {"file":true,"threshold":"1000","local":true} output: {"file":"file1"}
Result1: {"file":"file1","threshold":"1000","local":true}
Result2: {"file":"file2","threshold":"2000","local":true}
FinalResults: {"files":"file1","local":true}

zeebe-split-merge-demo on  master is 📦 v1.0.0 via ⬢ v10.9.0 took 2s 
➜ ts-node split-join-3.ts
[ config-to-payload config-to-payload-worker ] > Ready for config-to-payload... 
[ output output-worker ] > Ready for output... 
SetThreshold2000" input: {"file":true,"threshold":true,"local":true} output: {"threshold":"2000"}
SetThreshold1000" input: {"file":true,"threshold":true,"local":true} output: {"threshold":"1000"}
ProcessFile1" input: {"file":true,"threshold":"1000","local":true} output: {"file":"file1"}
ProcessFile2" input: {"file":true,"threshold":"2000","local":true} output: {"file":"file2"}
Result1: {"file":"file1","threshold":"1000","local":true}
Result2: {"file":"file2","threshold":"2000","local":true}
FinalResults: {"files":"file2","local":true}
```

Minimal reproducer (courtesy of @cappelaere) here: https://github.com/jwulf/zeebe-split-merge-demo

* Code: `split-join-3.ts`
* BPMN: `bpmn/test-split-join-3.bpmn`

Could this join instead be handled as a merge (producing an array)?

**Comment by menski** [comment] 2019-04-29 15:30
Thanks for raising this issue. The observation is correct that at the moment output mapping which maps to the same output variable are overwriting each other. This is expected behavior as there is currently no _merge/collect_ output mapping type. So I guess this is more a feature request for something like this. From the example I assume that the main use cases were this will be a problem is a data processing pipeline/map reduce process. From my experience this is normally where users will use BPMN features like multi-instance (see https://docs.camunda.org/manual/7.10/reference/bpmn20/tasks/task-markers/#multiple-instance). As this also allows to have a dynamic number of parallel processing pipelines. At the moment Zeebe does not support the concept of multi-instance, but we are aware that this is a much requested feature, therefore we will take that into account when planning new features in the second half of the year.

So with the current feature set of Zeebe to realize such a process a workaround is needed, which manually takes care of the merging of the sub-processes.

Just to clarify that the behavior you are observing is not _non-deterministic_ in the sense of the stream processing, it actually is deterministic based on which worker completes last. But I understand that from user perspective this is not determinable while modeling.

**Comment by saig0** [comment] 2019-05-03 11:28
**Proposal:**

Extending the expression language to append items to an array. 

This can be used in an output mapping to collect the result. For example:

source: `append(results, localResult)` 
target: `results`

with local variable `localResult` and global variable `results` which is used to collect all results.

This works for both: multi-instance and joining concurrent branches. Since the events are processed sequentially, it is safe to update the global variable on concurrent branches.

**Comment by cappelaere** [comment] 2019-05-03 13:12
Assuming that we have two subprocesses and a join,
If we use the output mapping at the subprocess level, wouldn’t the join overwrite the results?

Joins used to have an option to merge or overwrite.  I am not sure why it was removed but this is what may be preferred, IMHO.

Thanks,
Pat.

**Comment by saig0** [comment] 2019-05-06 07:39
@cappelaere, thank you for your input. No, the variable wouldn't be overridden because there is no variable merging on the joining gateway. Variables live in scopes are no part of the token (e.g. the concurrent path). So, the variables are merged when the subprocess is completed. In the example, it would add the result of the subprocess (which is stored in a local variable) to the list of result and update the global variable.

Regarding 
> Joins used to have an option to merge or overwrite.
In previous Zeebe versions, the variables belong to tokens - there were no variable scopes. So, the variables (aka payload) was merged when the concurrent paths were merged.

**Comment by saig0** [comment] 2020-05-29 05:52
From my point of view, this issue is solved. Zeebe supports multi-instance and allows to collect the result of the instances. Additionally, the expression language was replaced with FEEL that includes a built-in function `append` to add an item to a list.

So, I'll close this issue. Feel free to open it again if the problem is not solved for you.

**Closed by saig0** 2020-05-29 05:52 UTC
Labels: Scope: broker, Status: Needs Triage, Type: Bug
