### ISSUE TITLE
Possible problem on reprocessing/recovery

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2176] opened 2019-03-12 13:32 UTC
The following line tells us that something weird happen on listing the snapshot

```
2019-03-12 01:31:47.829 CET
00:31:47.828 [logstream.partition-0.blockIdx.writer] [0.0.0.0:26501-zb-fs-workers-1] WARN io.zeebe.logstreams.rocksdb - error listing snapshot /usr/local/zeebe/data/partition-0/index/snapshots/0_28574417650904_0.tmp
```

Note: we should also log the exception

After that the reprocessing failed, because (we assume) that the state is inconsistent.

```java
java.lang.RuntimeException: Unexpected error occurred during RocksDB transaction. at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.transaction(ZeebeTransactionDb.java:169) ~[zb-db-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.logstreams.processor.StreamProcessorController.reprocessEvent(StreamProcessorController.java:248) ~[zb-logstreams-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.logstreams.processor.StreamProcessorController.reprocessNextEvent(StreamProcessorController.java:229) ~[zb-logstreams-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] Caused by: java.lang.NullPointerException at io.zeebe.broker.workflow.processor.handlers.AbstractHandler.isStateSameAsElementState(AbstractHandler.java:80) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.broker.workflow.processor.handlers.element.ElementActivatingHandler.shouldHandleState(ElementActivatingHandler.java:53) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.broker.workflow.processor.handlers.AbstractHandler.handle(AbstractHandler.java:48) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.broker.workflow.processor.BpmnStepHandlers.handle(BpmnStepHandlers.java:152) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.broker.workflow.processor.BpmnStepProcessor.processRecord(BpmnStepProcessor.java:76) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:56) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:179) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.runInNewTransaction(ZeebeTransactionDb.java:177) ~[zb-db-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.transaction(ZeebeTransactionDb.java:166) ~[zb-db-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT] ... 8 more

ERROR io.zeebe.broker.workflow - Expected to process event TypedEventImpl{metadata=RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATING, requestStreamId=-2147483648, requestId=-1, valueType=WORKFLOW_INSTANCE}, value={"bpmnProcessId":"benchmark","version":2,"workflowKey":1392497,"workflowInstanceKey":2087199,"elementId":"benchmark","flowScopeKey":-1,"bpmnElementType":"PROCESS"}} without errors, but exception occurred with message Unexpected error occurred during RocksDB transaction. 

```

**Comment by npepinpe** [comment] 2019-03-19 15:47
We figured it out that on reprocessing, our key generator does not generate the same keys again.

**Comment by Zelldon** [comment] 2019-03-19 15:55
How that? Shouldn't that be deterministic? 😅 I mean if they start and increment the key how they can be different?

**Comment by menski** [comment] 2019-03-19 17:00
We have to rethink blacklist/skipping events on reprocessing, as then we might skip generating keys. Might not be related to this issue but still we cannot skip key generating

**Comment by Zelldon** [comment] 2019-03-20 07:16
Btw there is a bug in the reprocessing if a recoverable exception is thrown we call instead of reprocessing the processing method 

https://github.com/zeebe-io/zeebe/blob/develop/logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java#L273

**Comment by npepinpe** [comment] 2019-03-25 14:56
I guess we're putting this on hold. Not sure if we should close this and reopen when it happens again (since we're going to be testing with the cluster anyway), or just leave it? We can't really say it's fixed if we don't know the root cause...

**Comment by menski** [comment] 2019-03-26 09:07
Closed until we can reproduce it with more information/context

**Closed by menski** 2019-03-26 09:07 UTC
Labels: Scope: broker, Status: Planned, Type: Bug
