### ISSUE TITLE
Follower do not delete data because it does not receive any snapshots

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3763] opened 2020-01-31 10:01 UTC
**Description**

On running our benchmarks I saw an unexpected drop of the processing metrics.

![processing](https://user-images.githubusercontent.com/2758593/73530246-643f5f00-4418-11ea-8cbb-2a81ab15b4b8.png)

The problem seem that some nodes went out of disk space.

![pvc-usage](https://user-images.githubusercontent.com/2758593/73530245-643f5f00-4418-11ea-9de7-ad523609bfcc.png)

After taking a look in the logs at broker 2. I just found the following logs:

```
I 2020-01-30T03:08:48.998201888Z 2020-01-30 03:08:48.998 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000337.sst of snapshot 43897974-5-1580353721239-108611136510024
 
I 2020-01-30T03:08:48.998324095Z 2020-01-30 03:08:48.998 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Received all snapshot chunks (74/74), snapshot is valid
 
I 2020-01-30T03:08:49.000942314Z 2020-01-30 03:08:49.000 [] [Broker-2-StateReplication-1] INFO  io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Max snapshot count reached (4), purging snapshots older than DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/42497265-5-1580351919842-105136510471232, metadata=DbSnapshotMetadata{index=42497265, term=5, timestamp=2020-01-30 02:38:39,842, position=105136510471232}}
 
I 2020-01-30T03:08:49.001165833Z 2020-01-30 03:08:49.000 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Deleting snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/40764155-3-1580350135469-101004747137888, metadata=DbSnapshotMetadata{index=40764155, term=3, timestamp=2020-01-30 02:08:55,469, position=101004747137888}}
 
I 2020-01-30T03:08:49.013363468Z 2020-01-30 03:08:49.013 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/40764155-3-1580350135469-101004747137888, metadata=DbSnapshotMetadata{index=40764155, term=3, timestamp=2020-01-30 02:08:55,469, position=101004747137888}} removed from store io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore@1c1c1850
```

It seems that the Broker-2 only receives snapshots for partition 1.
Based on the metrics I also saw that broker 2 is follower for all partitions and Broker-1 Leader for partition 2. I had a deeper look in the logs of the other nodes. 

**Broker-1 Leader for 2**

Seem to send the snapshots for partition 2.
```
I 2020-01-30T03:10:05.371088688Z 2020-01-30 03:10:05.370 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/006076.sst
 
I 2020-01-30T03:10:05.686133211Z 2020-01-30 03:10:05.685 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/005312.sst
 
I 2020-01-30T03:10:06.095022116Z 2020-01-30 03:10:06.094 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/005840.sst
 
I 2020-01-30T03:10:06.096600272Z 2020-01-30 03:10:06.096 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/000425.sst
 
I 2020-01-30T03:10:06.096628849Z 2020-01-30 03:10:06.096 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/006125.sst
 
I 2020-01-30T03:10:06.100268999Z 2020-01-30 03:10:06.099 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/006232.sst
 
```

**Broker-0 Follower for 2**
Broker 0 seems to receive the snapshots for partition 2.
```
I 2020-01-30T03:10:15.323098175Z 2020-01-30 03:10:15.322 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 006197.sst of snapshot 43099325-3-1580353776084-104969001240160
 
I 2020-01-30T03:10:15.437579442Z 2020-01-30 03:10:15.437 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 127/128
 
I 2020-01-30T03:10:15.438570092Z 2020-01-30 03:10:15.438 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 006112.sst of snapshot 43099325-3-1580353776084-104969001240160
 
I 2020-01-30T03:10:15.440894706Z 2020-01-30 03:10:15.440 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.logstreams.snapshot - Received all snapshot chunks (128/128), snapshot is valid
 
I 2020-01-30T03:10:15.443213438Z 2020-01-30 03:10:15.442 [] [Broker-0-StateReplication-2] INFO  io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Max snapshot count reached (4), purging snapshots older than DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/41699671-3-1580351977845-101588868285656, metadata=DbSnapshotMetadata{index=41699671, term=3, timestamp=2020-01-30 02:39:37,845, position=101588868285656}}
 
I 2020-01-30T03:10:15.443432341Z 2020-01-30 03:10:15.443 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Deleting snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/40782490-3-1580351085942-99505805655416, metadata=DbSnapshotMetadata{index=40782490, term=3, timestamp=2020-01-30 02:24:45,942, position=99505805655416}}
 
I 2020-01-30T03:10:15.761355865Z 2020-01-30 03:10:15.761 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/40782490-3-1580351085942-99505805655416, metadata=DbSnapshotMetadata{index=40782490, term=3, timestamp=2020-01-30 02:24:45,942, position=99505805655416}} removed from store io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore@4d80f1eb
 
I 2020-01-30T03:10:15.761456660Z 2020-01-30 03:10:15.761 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Search for orphaned snapshots below oldest valid snapshot DbSnapshotMetadata{index=41699671, term=3, timestamp=2020-01-30 02:39:37,845, position=101588868285656}
 
I 2020-01-30T03:10:15.761815249Z 2020-01-30 03:10:15.761 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160, metadata=DbSnapshotMetadata{index=43099325, term=3, timestamp=2020-01-30 03:09:36,084, position=104969001240160}}
 
```

**Broker-2 Follower for 2**
Do not receive any snapshot replication for partition 2.

![broker-2-partition-2](https://user-images.githubusercontent.com/2758593/73530247-64d7f580-4418-11ea-94c0-dc01a29dd1b9.png)
![broker-2-partition-1](https://user-images.githubusercontent.com/2758593/73530248-64d7f580-4418-11ea-8d08-bc00aa85bc73.png)

The snapshot replication view is not 100% clear to me, seems to be not working correctly?
![replication](https://user-images.githubusercontent.com/2758593/73530243-643f5f00-4418-11ea-8a82-4edd45947890.png)

**Comment by npepinpe** [comment] 2020-01-31 10:09
The graphs you're looking at are the Atomix snapshot replication, which only happens when a node is rejoining or if it is slow to append entries. Our snapshot replication metrics are under the `Snapshots` row.

**Comment by Zelldon** [comment] 2020-01-31 10:10
Ah thanks for clarification :+1:

**Comment by Zelldon** [comment] 2020-01-31 10:13
Here we can see the snapshot replication:

![snapshot-replication](https://user-images.githubusercontent.com/2758593/73531374-9c47a180-441a-11ea-8cb7-bc17ac598574.png)

The same we see in the logs; Broker 2 does not receive snapshot for partition 2.

**Comment by Zelldon** [comment] 2020-01-31 10:14
@npepinpe is 7 gig a expected snapshot size ? :sweat_smile:

**Comment by npepinpe** [comment] 2020-01-31 10:16
:scream: 

Looks like a lot of ~100mb files? You're just running our normal load, aren't you? 

Where is this running? I can't see the namespace in our Grafana :thinking:

**Comment by Zelldon** [comment] 2020-01-31 10:17
You have to adjust the range to last 2 days, then you can see the long-running ns.

**Comment by Zelldon** [comment] 2020-01-31 11:01
Ok @npepinpe and me investigated that further and we expect that create workflow instances are send to that specific partition but the workers do not complete them on that partition, which would explain why it increases in size. We can also see in the running instances metric view that this number increases up to 400k


![running](https://user-images.githubusercontent.com/2758593/73534344-314d9900-4421-11ea-94b4-58a2e1c8997d.png)


We were also not able to get the topology from the different nodes which also affirms our assumption that this seems to be related to the topology problems we currently have.

**Comment by Zelldon** [comment] 2020-01-31 11:20
We can break this down into different partitions:

**Partition 1**

![run-p1](https://user-images.githubusercontent.com/2758593/73535446-d9fcf800-4423-11ea-988d-04bade63f041.png)


**Partition 2**

![run-p2](https://user-images.githubusercontent.com/2758593/73535456-df5a4280-4423-11ea-9a23-665e638e2432.png)


**Partition 3**

![run-p3](https://user-images.githubusercontent.com/2758593/73535464-e5502380-4423-11ea-8632-e6a3ec901691.png)


We see partition 2 just increases. We also see that partition 3 has some other problems I think from the metrics it seems also not really available, which would explain also the lower throughput :man_shrugging:

**Comment by Zelldon** [comment] 2020-01-31 11:37
Some more insights:

**Partition 2 difference between created instances and completed**
![diff-p2](https://user-images.githubusercontent.com/2758593/73536458-3c56f800-4426-11ea-950f-6fd836b68896.png)

**Partition 1 difference between created instances and completed**
![diff-p1](https://user-images.githubusercontent.com/2758593/73536459-3c56f800-4426-11ea-8da7-97f7c316cd59.png)

**Partition 2 job created,activiated and completed**
![diff-job-p2](https://user-images.githubusercontent.com/2758593/73536460-3cef8e80-4426-11ea-96a5-5d6695cc784a.png)

We can see that at the end 400k less jobs are activated/completed then created.

**Comment by npepinpe** [comment] 2020-02-14 14:58
I'd be curious to see this again with the fix in Atomix from https://github.com/zeebe-io/atomix/pull/144 - essentially, if there was any issue in the serialization/deserialization of a message, the error would be silently ignored (so the executor wouldn't crash). We know that there was a bug in #3717 where we failed to transmit empty files (arguable if they should be transmitted but safe to do so), which would leave snapshots pending. The snapshot replication above only shows committed snapshots, so it might have been the cause.

I will try to reproduce it in benchmarks for a bit, then mark it as tentatively fixed, as I hoped this time around we have more logs to diagnose the problem if it fails.

**Comment by npepinpe** [comment] 2020-02-16 15:42
Did manage to reproduce this, so it's definitely still happening. The leader nodes are sending out the snapshots for replication, and the follower is correctly (as far as I can tell) subscribed to the topic to receive them, but seems not to be receiving anything. Might be a bug in the Atomix subscriptions?

**Comment by Zelldon** [comment] 2020-02-20 13:50
Our current hypothesis is that the follower was restarted and receives after that no longer any snapshots. The reason for that could be the following:

Each Leader sends via "broadcast" the snapshot chunks. Broadcast is implemented in Atomix via a list of nodes and they send the messages to all members. If we restart we keep the nodeId, dns name etc but not the ip. It might be the case that the node is not replaced in the list, which means it is send to old ip.

**Comment by npepinpe** [comment] 2020-02-20 13:58
So it uses the membership service, that's true - but on start the new node, when subscribing to a topic, will propagate that it is subscribed to that topic all known nodes in the cluster (which on restart should be every node, as we list all nodes as contact points), and every node should update and insert this node for broadcasts. That said, I still suspect there is a bug in there, as we've seen that sometimes some followers receive snapshots and others don't. The goal then is to narrow where the subscription mechanism fails - on the follower (propagating its subscription) or on the leader (updating its subscription).

**Closed** 2020-03-11 16:44 UTC
Labels: Status: Needs Review, Type: Bug, Type: Maintenance
