### ISSUE TITLE
ExporterDirector keeps trying to read new events with a closed reader

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4820] opened 2020-06-25 15:24 UTC
**Describe the bug**

The exporter director seems to be trying to read the next event constantly with a closed reader: https://console.cloud.google.com/errors/CISeh5m8loKfPw?service=zeebe&version=0.23.3&time=P7D&project=camunda-cloud-240911

I would expect if the reader was closed for a good reason, we would close the exporter. Now this eventually occurred, but not before the exporter tried to read >24,000 times the next event - as this is unrecoverable, why do we keep retrying?

**Expected behavior**

We should not retry with a closed reader - either attempt to get a new one, or close the director and mark it unhealthy.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Iterator is closed
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.hasNext(LogStreamReaderImpl.java:159) ~[zeebe-logstreams-0.23.3.jar:0.23.3]
	at io.zeebe.broker.exporter.stream.ExporterDirector.readNextEvent(ExporterDirector.java:241) ~[zeebe-broker-0.23.3.jar:0.23.3]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) ~[zeebe-util-0.23.3.jar:0.23.3]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.3.jar:0.23.3]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.3.jar:0.23.3]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.3.jar:0.23.3]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.3.jar:0.23.3]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.3.jar:0.23.3]
```

</p>
</details>

**Environment:**
 - OS: Docker distribution
 - Zeebe Version: 0.23.3
 - Configuration: cloud config

**Comment by Zelldon** [comment] 2020-11-26 15:19
duplicate of https://github.com/zeebe-io/zeebe/issues/5504

**Closed by Zelldon** 2020-11-26 15:19 UTC
Labels: Impact: Integration, Priority: Mid, Scope: broker, Severity: Mid, Status: Ready, Type: Bug
