### ISSUE TITLE
Investigate why create workflow instance requests are not evenly distributed across all partitions

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2187] opened 2019-03-13 15:54 UTC
During our k8s test, we noticed that with 3 partitions, creating workflow instances was creating evenly on both partition 0 and partition 2, but only about half on partition 1. Expected behaviour is that we would create more or less the same amount on each partition, so we should investigate what happened.

**Comment by menski** [comment] 2019-03-13 16:54
When I just run the starter the create workflow instance seems to be evenly distributed, so it might be influenced by the job worker

**Comment by menski** [comment] 2019-03-13 23:07
I cannot reproduce this in current test setup. Even with job workers the distribution is even over the partitions. Closing until we see this issue again.

**Closed by menski** 2019-03-13 23:07 UTC
Labels: Scope: broker, Status: Planned, Type: Bug
