### ISSUE TITLE
Log Mesage about connection reset

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#3786] opened 2020-02-05 14:15 UTC
**Describe the bug**
When going through the quick start after the release I saw several info log messages on the side of the broker:
This log message is confusing to the user

**To Reproduce**
- Follow quick start instruction on a Windows machine with release 0.23.0-alpha1
- Bug happens at step "4 Create Workflow Instance"

- As a side note, the bug did not occur on a Linux machine

**Expected behavior**
No log message that looks like an error.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

```
Feb 05, 2020 3:08:17 PM io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1140)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
...
```

**Environment:**
 - OS: Windows
 - Zeebe Version: 0.23.0-alpha1
 - Configuration: no changes to default config

**Comment by korthout** [comment] 2020-03-03 13:47
Also encountered on macOS.

**Comment by MiguelPires** [comment] 2020-03-03 14:11
I can't reproduce this on my machine (Linux) but I think was happening because the zbctl client wasn't closed after running the command. If that's the case, this is already fixed but it wasn't included in 0.23.0-alpha1. @pihme @korthout can you try it on develop?

**Comment by pihme** [comment] 2020-03-05 14:29
Can no longer reproduce it with 0.23.0-alpha2. I my mind the issue can be closed

**Comment by korthout** [comment] 2020-03-06 08:57
No longer encountered on macOS with `0.23.0-alpha2`.

**Comment by MiguelPires** [comment] 2020-03-06 08:57
Great, thanks guys. This was likely fixed by this PR https://github.com/zeebe-io/zeebe/pull/3825

**Closed by MiguelPires** 2020-03-06 08:57 UTC
Labels: Type: Bug
