### ISSUE TITLE
RaftTest#testCorrectTermInSnapshot is flaky

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4258] opened 2020-04-07 10:10 UTC
**Description**

Fails quite often locally

```


java.lang.AssertionError: 
Expected :27
Actual   :23
<Click to see difference>


	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.atomix.raft.RaftTest.testCorrectTermInSnapshot(RaftTest.java:1527)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by Zelldon** [comment] 2020-04-07 10:11
Test log:

```
11:58:59.171 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to CANDIDATE
11:58:59.171 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{1}{role=CANDIDATE} - Starting election
11:58:59.172 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to FOLLOWER
11:58:59.172 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to FOLLOWER
11:58:59.173 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to FOLLOWER
11:59:00.035 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{2}{role=FOLLOWER} - No heartbeat from null in the last PT0.862S (calculated from last 862 ms), sending poll requests
11:59:00.035 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to CANDIDATE
11:59:00.035 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{2}{role=CANDIDATE} - Starting election
11:59:00.036 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to LEADER
11:59:00.036 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Found leader 2
11:59:00.037 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Found leader 2
11:59:00.037 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Found leader 2
11:59:00.039 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to INACTIVE
11:59:00.061 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{2} - AppendRequest{term=1, leader=2, prevLogIndex=1, prevLogTerm=1, entries=1, commitIndex=1} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException
11:59:00.063 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{2} - AppendRequest{term=1, leader=2, prevLogIndex=2, prevLogTerm=1, entries=0, commitIndex=2} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException
11:59:00.067 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{2} - AppendRequest{term=1, leader=2, prevLogIndex=2, prevLogTerm=1, entries=0, commitIndex=3} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException
11:59:00.077 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to CANDIDATE
11:59:00.077 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{1}{role=CANDIDATE} - Starting election
11:59:00.078 [] INFO  io.atomix.raft.roles.LeaderRole - RaftServer{2}{role=LEADER} - Received greater term from 1
11:59:00.078 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to FOLLOWER
11:59:00.078 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to FOLLOWER
11:59:00.838 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{3}{role=FOLLOWER} - No heartbeat from null in the last PT0.767S (calculated from last 768 ms), sending poll requests
11:59:00.838 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{2}{role=FOLLOWER} - Accepted PollRequest{term=2, candidate=3, lastLogIndex=23, lastLogTerm=1}: candidate's log is up-to-date
11:59:00.838 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - Accepted PollRequest{term=2, candidate=3, lastLogIndex=23, lastLogTerm=1}: candidate's log is up-to-date
11:59:00.838 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to CANDIDATE
11:59:00.839 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{3}{role=CANDIDATE} - Starting election
11:59:00.839 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{2}{role=FOLLOWER} - Accepted VoteRequest{term=3, candidate=3, lastLogIndex=23, lastLogTerm=1}: candidate's log is up-to-date
11:59:00.839 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - Accepted VoteRequest{term=3, candidate=3, lastLogIndex=23, lastLogTerm=1}: candidate's log is up-to-date
11:59:00.839 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to LEADER
11:59:00.839 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Found leader 3
11:59:00.840 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Found leader 3
11:59:00.840 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Found leader 3
11:59:09.374 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to INACTIVE
11:59:09.377 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to INACTIVE
11:59:09.378 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to INACTIVE


```

**Comment by npepinpe** [comment] 2020-04-07 11:08
Duplicate of #4176 ?

**Comment by deepthidevaki** [comment] 2020-04-07 11:42
Looks like flakyness is due to https://github.com/zeebe-io/zeebe/issues/4147
Node 1 joins, starts a new election, and we have a new leader which probably results in a new snapshot?

**Comment by Zelldon** [comment] 2020-04-07 12:21
Thanks @npepinpe you're right.

@deepthidevaki thanks for looking at it might be :man_shrugging: at least you have a candidate to reproduce it then :D

**Comment by pihme** [comment] 2020-05-11 08:21
Would propose to close this issue. I haven't observed it at all in the 4+ weeks that I am tracking flaky tests

**Comment by npepinpe** [comment] 2020-05-11 11:25
Sounds good :+1:

**Closed by npepinpe** 2020-05-11 11:25 UTC
Labels: Type: Maintenance, Type: Unstable Test
