### ISSUE TITLE
Cluster failure when stopping a broker

### ISSUE THREAD

**Issue by ezolnbl** [zeebe-io/zeebe#3726] opened 2020-01-22 12:53 UTC
**Describe the bug**
As stated in https://github.com/zeebe-io/zeebe/issues/1772 when I bring down a broker from a 2 broker cluster the  activated jobs are not continued in another still living broker.

**To Reproduce**
docker-compose:
version: "3"

volumes:
    zeebe_1: {}
    zeebe_2: {}

services:
  zeebe-1:
    image: zebee-custom:0.0.4
    ports:
      - "26500:26500"
    environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-info}
            - ZEEBE_NODE_ID=0
            - ZEEBE_PARTITIONS_COUNT=2
            - ZEEBE_CLUSTER_SIZE=2
            - ZEEBE_REPLICATION_FACTOR=2
            - ZEEBE_CONTACT_POINTS=zeebe-2:26502,zeebe-1:26502
    volumes:
        - zeebe_1:/usr/local/zeebe/data
  zeebe-2:
    image: zebee-custom:0.0.4
    ports:
      - "26501:26500"    
    environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-info}
            - ZEEBE_NODE_ID=1
            - ZEEBE_PARTITIONS_COUNT=2
            - ZEEBE_CLUSTER_SIZE=2
            - ZEEBE_REPLICATION_FACTOR=2
            - ZEEBE_CONTACT_POINTS=zeebe-1:26502,zeebe-2:26502
    volumes:
        - zeebe_2:/usr/local/zeebe/data

Java client 1 connected to broker 1 to localhost 26500
ZeebeClient.newClientBuilder()
                .brokerContactPoint("127.0.0.1:26500")
                .numJobWorkerExecutionThreads(50)
                .usePlaintext()
                .defaultJobPollInterval(Duration.ofMillis(500))
                .defaultJobWorkerMaxJobsActive(1000)
                .build()
Java client 2 connected to broker 2 to localhost 26501
ZeebeClient.newClientBuilder()
                .brokerContactPoint("127.0.0.1:26501")
                .numJobWorkerExecutionThreads(50)
                .usePlaintext()
                .defaultJobPollInterval(Duration.ofMillis(500))
                .defaultJobWorkerMaxJobsActive(1000)
                .build()

client starts instance:
Map<String, String> variables = new HashMap<>();
        variables.put("txId", txId);

        zeebeClient.newCreateInstanceCommand()
                .bpmnProcessId("PaymentTest")
                .latestVersion()
                .variables(variables)
                .send();

**Expected behavior**
After starting instance on broker-n, stop that container and an active worker on the other broker  should complete the timeout intermediatecatchevent bpmn flow attached to the receivetask.

**Log/Stacktrace**
Stopped broker's java client instantly start to throw exceptions after shutdown:
1. io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.24.0.jar:1.24.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442) [grpc-stub-1.24.0.jar:1.24.0]
2. io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.24.0.jar:1.24.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442) [grpc-stub-1.24.0.jar:1.24.0]

On living broker's java client:
1. io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 29999728600ns. [remote_addr=/127.0.0.1:26500]
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.24.0.jar:1.24.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442) [grpc-stub-1.24.0.jar:1.24.0]

**Environment:**
 - OS: Docker host running on virtualbox vm, Windows 10
 - Zeebe Version: 0.23.0-SNAPSHOT
 - Configuration: VM has 4gb memory with 1 cpu core

**Comment by menski** [comment] 2020-01-22 16:25
Hi @ezolnbl,

thanks for raising this issue. This behavior is expected as Zeebe uses a replication algorithm called [Raft](https://docs.zeebe.io/basics/clustering.html#raft-consensus-and-replication-protocol) to become fault-tolerant. Raft requires a quorum of nodes to [commit](https://docs.zeebe.io/basics/clustering.html#commit) new entries to the event log.

```
- ZEEBE_CLUSTER_SIZE=2
- ZEEBE_REPLICATION_FACTOR=2
```

Your configuration defines 2 brokers with a replication factor of 2. The quorum to commit new entries to the log is 2 in this case. Therefore if you shutdown a broker the cluster becomes unavailable to prevent possible data lose. To create a fault-tolerant cluster you have to at least use 3 node with a replication factor of 3, then you have a fault-tolerance of 1. Similar if you increase the replication factor to 5 you gain a fault-tolerance of 2.

Let us know if you anymore questions? I will already close this issue as it is expected behavior with the provided configuration.

Cheers,
Sebastian

**Closed by menski** 2020-01-22 16:25 UTC
Labels: Type: Bug

**Comment by ezolnbl** [comment] 2020-01-23 10:07
I can verify this and with increased cluster_sze, replication_factor the broker fail job handover works however it took around 52 sec.

**Comment by menski** [comment] 2020-01-23 16:13
Thanks for verifying that it works as expected.

> the broker fail job handover works however it took around 52 sec.

Can you explain in more detail what the process looks like and what the situation is before you kill a broker. The fail-over time depends on different aspects, like the size of the in-flight state to recover, timeout of an already activated job etc.
