### ISSUE TITLE
Generate dispatcher positions using a predictable sequence

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3987] opened 2020-03-05 12:12 UTC
# :fire: :fire: BREAKING CHANGE :fire: :fire: 

**Description**

The worst bugs that can occur in the Zeebe Broker are the ones which can result in an inconsistent/corrupted, replicated log. Not only will they break the local node's log and make it very difficult to recover, but they can potentially infect other node's healthy logs. In order to prevent this, we should try to detect these issues before they can happen.

One of these inconsistencies that can occur is where we have missing records. With the Raft index sequence, detecting missing events is quite easy as the sequence is a simple incrementing counter - if we go from 2 to 4 then we are missing event 3.

With the dispatcher positions, it's more difficult, as the sequence is based on the dispatcher segments, the size of each segment, and the offset the entry was written at in the segment. As a result, it's quite difficult to detect gaps or wrong positions after the fact.

We should investigate a different way of generating positions which results in a predictable positions where we can detect gaps. Bonus points if we can somehow encode the Raft index in there to avoid having to keep up a mapping of the position -> index.

NOTE: this would obviously be a breaking change :fire:

**Comment by npepinpe** [comment] 2020-03-16 14:09
I came up with a possible solution, but there is one caveat: I don't know how to handle the very first entry, as we don't know deterministically what will be the index of the first `ZeebeEntry` until it's written.

The position is made of the entry index and the record's index in the records array of the entry, e.g. a 98 bits number. <sup>1</sup>

On opening the appender, we read the latest entry and extract the index from it's position - the initial partition ID is then that index + 1. <sup>2</sup>

The dispatcher's claimed batch `nextFragment()` method can simply return a position which is a simple counter incremented by 1. So basically, when claiming a batch, we claim the batch based both on size and on the number of records we will write - both information we already know. So the batch can generate positions for us by simply incrementing the record index. We can think of a batch claim as claiming a section of the ring buffer (memory) and also a series of record slots (the positions) such that the positions never overlap between different claims. As we consume batches in order and never mark them as failed, this is correct - of course if we ever want to skip batches then we'd have a problem, but we might already have a problem with the current system.

By having deterministic generator for positions we can then find gaps between them, missing records, etc, and do not need to keep a position -> index map.

/cc @deepthidevaki @Zelldon let me know what you think - like I said, I don't know how to handle the very first entry :thinking: 

<sup>1</sup> Entry indexes are 64 bits, and we probably don't need a full 32 bits integer to represent the record's index, as I doubt a batch would ever be so large, but let's say that's how it is for now.
<sup>2</sup> As mentioned above, this doesn't handle the case where no Zeebe entries are found - still not sure how to do this.

**Comment by deepthidevaki** [comment] 2020-03-16 16:31
To make sure I understood it correctly,
Lets say position := <paritionId, recordIndex>
Assume lastRaftIndex = 10 
initialPartitionId = lastRaftIndex + 1; 
The positions generated in a single leader term will be : <11, 1>: <11, 2>, <11, 3> ... 
When new leader starts, the new positions will be (for example) <100, 1>, <100,2> .. 
Is that right?

**Comment by npepinpe** [comment] 2020-03-16 16:58
Assuming the last committed entry it can read is `<99, x>`, then yes (though probably we would start at 0, e.g. `<11, 0>, <11, 1>`, etc.).

**Comment by deepthidevaki** [comment] 2020-03-16 17:10
> Assuming the last committed entry it can read is `<99, x>`, then yes (though probably we would start at 0, e.g. `<11, 0>, <11, 1>`, etc.).

When does the position becomes <99, x>? Assuming the current leader started at position <11, 0>.

**Comment by npepinpe** [comment] 2020-03-16 17:15
On the next batch we increment the partition ID as well. I guess I wasn't clear in the initial post, my bad. On every batch we increment the partition ID, predicting that one batch == one entry, and batches are written in order. Since the log is comprised solely of `InitialEntry` and `ZeebeEntry`, we know only we can write `ZeebeEntry` - except on failover, at which point `InitialEntry` grabs one index.

Actually I see that this falls apart anyway due to the `InitialEntry` - we could have the following log:

```
IE_1, IE_2, ZE_3, ZE_4, IE_5, IE_6
```

There's no clean way for us to know, by reading `ZE_4`, that the next partition ID should be 7. It's also seems quite brittle to "guess" or predict the index a batch/entry will have. :disappointed:

**Comment by npepinpe** [comment] 2020-03-16 17:38
We could just forego encoding the index in there and just using the incrementing sequence when claiming a batch. That's also fine, and we increment the partition ID on every batch but it has no special meaning. So we can detect gaps, e.g.

```
<1, 0>, <1, 1>, <1, 2>, <2, 0>, <2, 1>
```

Is valid, but:

```
<1, 0><1, 2>
```

Or

```
<1, 0>, <1, 1>, <2, 0>
```

Both are not valid.

**Comment by npepinpe** [comment] 2020-03-16 17:39
I still wish we could somehow encode the index in there, but I think it's not as easy to predict and potentially error prone.

**Comment by deepthidevaki** [comment] 2020-03-16 18:14
> of course if we ever want to skip batches then we'd have a problem, but we might already have a problem with the current system.

In current system, it is not a problem. We just ignore some positions that are already generated. But the positions are still strictly increasing. But if we assume gaps as inconsistency, then there is a chance that we detect inconsistency incorrectly when there is a gap due to aborts.

**Comment by npepinpe** [comment] 2020-03-18 16:35
Final proposal:

1. On restart, read the last written index from the Raft writer
1. Use this + 1 as the initial partition ID
1. Each batch increments the partition ID
1. Each record receives a position of <partitionId><index of record in batch> (98 bits or maybe even smaller)
1. When appending the entry on the writer side, i.e. in `FileChannelJournalSegmentWriter#append(T entry)`, delegate to the entry class (e.g. `ZeebeEntry`) to verify, within the current context, whether or not we can write this entry
1. Verification can look at the lowestPosition, highestPosition, and new property eventsCount, to verify if we indeed have the correct index we will assign, and if the range [lowestPosition, highestPosition] covers the eventsCount.

I will do a spike for this, and then try to figure out how to do it in a non-hacky way.

**Comment by MiguelPires** [comment] 2020-05-05 16:19
### Current Proposal
If I understood correctly, using the last written raft index as the basis for the `partitionId` has the disadvantages that it **a)** breaks backwards compatibility and **b)** the mapping between zeebe positions and raft indexes is easily broken. The last one has two effects, the first being that it's we can't just read the `partitionId` last zeebe entry and check that the new entry's `partitionId` is that plus one. The second effect is that we can't rely on the mapping to seek and we would still have to keep a map between the two.

Two ways in which the mapping can be broken is by having multiple initial entries on failover or by allowing the cluster to scale (which would write configuration entries). 
Regarding the first scenario, we could check that the number of IEs is equal to the difference between the partitionIds of zeebe entries: 
```
1. IE
2. ZE-2-0
3. IE
4. IE
5. ZE-5-0
```

Regarding the second scenario, having configuration entries appear between zeebe entries would break the assumption that only zeebe writes to the log. Since it doesn't happen on failover, we wouldn't be taking it into account if we just increment the `partitionId`:
```
1. IE
2. ZE-2-0
3. CE
4. ZE-3-0
```

In general, the issue is that having this mapping assumes things that may not be true and, even if they are, are a bit brittle.

### Alternative Proposal
A simple alternative would be to read the last committed zeebe position, get the corresponding `partitionId` and set the initial `partitionId` as that plus 1. This would preserve backwards compatibility and allow us to easily check for missing records regardless of other entries, since the partitionId would always be incremented by 1. However, we'd still have to keep track of position to index mappings.

**Comment by MiguelPires** [comment] 2020-05-18 19:29
The previous proposals still had the issue where an explicit map of positions to indexes (and vice-versa) had to be maintained so that we could seek semi-efficiently. In order to have a more efficient solution, Chris proposed that we only set zb positions based on the generated raft indexes. Here is the current state:
The log writers pass a callback into the dispatcher when committing fragments/batches. These callbacks take in the entry, the entry's index and "record indexes" (an entry has multiple records in it and it may belong to different batches). These callbacks are invoked from raft before persisting entries and are responsible for updating the record with the position as well as ensuring that the records aren't out of order. The new positions are 64 bits, the leftmost 56 bits are raft indexes shifted left by 8 bits and the remaining 8 bits are "record index", the index of the record in the raft entry. This assumes that there won't be more than 256 records in an entry. The "old positions" still exist but they are currently only used internally to map these handlers to their respective fragment batches in the Dispatcher. The writers' `tryWrite` methods can't return the claimed position any longer since that position is not what will be in the records. I haven't replaced that yet but we can return a `Future` instead of the position and complete the future later.

**Closed** 2020-06-26 13:00 UTC
Labels: Priority: High, Scope: broker, Severity: High, Status: Needs Review, Type: Maintenance
