### ISSUE TITLE
BufferUnderflowException on cluster restart

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2435] opened 2019-05-06 12:16 UTC
After running the cluster, we tested failover and then restarted the cluster. Broker 1 failed to start with the following exception for all the partitions:

```
12:12:00.124 [] [raft-server-raft-atomix-partition-1-state] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-1} - Failed to read snapshot
java.nio.BufferUnderflowException: null
	at io.atomix.storage.buffer.AbstractBuffer.checkRead(AbstractBuffer.java:397) ~[atomix-storage-3.2.0-20190430.073241-4.jar:?]
	at io.atomix.storage.buffer.AbstractBuffer.checkRead(AbstractBuffer.java:372) ~[atomix-storage-3.2.0-20190430.073241-4.jar:?]
	at io.atomix.storage.buffer.AbstractBuffer.readInt(AbstractBuffer.java:581) ~[atomix-storage-3.2.0-20190430.073241-4.jar:?]
	at io.atomix.protocols.raft.storage.snapshot.SnapshotReader.readInt(SnapshotReader.java:154) ~[atomix-raft-3.2.0-20190430.073321-4.jar:?]
	at io.atomix.protocols.raft.impl.RaftServiceManager.install(RaftServiceManager.java:499) ~[atomix-raft-3.2.0-20190430.073321-4.jar:?]
	at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$apply$12(RaftServiceManager.java:419) ~[atomix-raft-3.2.0-20190430.073321-4.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20190430.073221-4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by npepinpe** [comment] 2019-05-27 08:01
Probably duplicate of #2359

**Comment by npepinpe** [comment] 2019-05-27 12:58
Investigate if it's related to node being killed/crashing while its writing a snapshot.

**Comment by npepinpe** [comment] 2019-06-28 11:42
Closing this in favor of #2359

**Closed by npepinpe** 2019-06-28 11:42 UTC
Labels: Scope: broker, Status: Ready, Type: Bug
