### ISSUE TITLE
Three node cluster fails if one node goes down

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#1772] opened 2018-12-11 01:27 UTC
When I bring down a broker in a three-node cluster down to simulate failure, the cluster fails. When I bring up the node, the cluster does not recover. 

# Config files

The cluster section of my config file for each node:

* Node0

```
[cluster]

nodeId = 0
partitionsCount = 2
replicationFactor = 3
clusterSize = 3
#initialContactPoints = [ "node1:26502", "node2:26502" ]
```

* Node1
```
[cluster]

nodeId = 1
partitionsCount = 2
replicationFactor = 3
clusterSize = 3
initialContactPoints = [ "node0:26502" ]
```

* Node2
```
[cluster]

nodeId = 2
partitionsCount = 2
replicationFactor = 3
clusterSize = 3
initialContactPoints = [ "node0:26502" ]
```

## Resetting the cluster

If I bring all nodes down and delete the `data/partition-*` directories, they come up as expected:

```
~/workspace/zeebe-broker-0.14.0
➜ bin/zbctl status --address node0
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 10.0.2.7:26501
    Partition 0 : Leader
    Partition 1 : Follower
```

node1 back up:

```
~/workspace/zeebe-broker-0.14.0
➜ bin/zbctl status --address node0
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 10.0.2.7:26501
    Partition 0 : Leader
    Partition 1 : Follower
  Broker 1 - 10.0.2.9:26501
    Partition 0 : Follower
    Partition 1 : Leader
```

node2 up:

```
~/workspace/zeebe-broker-0.14.0
➜ bin/zbctl status --address node0
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 10.0.2.7:26501
    Partition 0 : Follower
    Partition 1 : Follower
  Broker 1 - 10.0.2.9:26501
    Partition 0 : Follower
    Partition 1 : Leader
  Broker 2 - 10.0.2.11:26501
    Partition 0 : Leader
    Partition 1 : Follower
```

I deploy my workflow to node1, then have my task listeners connect to node1. Then I start workflow instances on node0. My task workers get them and complete the workflow.

I connect another set of task workers to node2. They are also getting work done.

So at this point I am starting work on node0, and task workers are getting it done on node1 and node2.

## Simulate node2 failure

Now I bring down node2.

node0 throws this exception:

```
01:03:10.242 [zb-stream-processor] [10.0.2.7:26501-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'CLOSING'. Discard all jobs and stop immediatly.
java.lang.NullPointerException: null items are not supported in this collection
	at io.zeebe.util.sched.channel.ActorConditions.removeConsumer(ActorConditions.java:54) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.impl.service.LogStreamService.removeOnCommitPositionUpdatedCondition(LogStreamService.java:255) ~[zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.processor.StreamProcessorController.onActorClosing(StreamProcessorController.java:451) ~[zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
```

node1 starts throwing exceptions:

```
01:04:25.482 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [gateway-zb-actors-0] WARN  io.zeebe.gateway - Failed to activate jobs for type start_job from partition 1
io.zeebe.gateway.cmd.ClientException: Failed to read response: CANCELLED: call already cancelled
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$6(BrokerRequestManager.java:191) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:40) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
Caused by: io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
	at io.grpc.Status.asRuntimeException(Status.java:517) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:356) ~[grpc-stub-1.16.1.jar:1.16.1]
	at io.zeebe.gateway.impl.job.ActivateJobsHandler.activateJobs(ActivateJobsHandler.java:87) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.job.ActivateJobsHandler.lambda$activateJobs$1(ActivateJobsHandler.java:82) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:117) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$6(BrokerRequestManager.java:187) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	... 7 more
01:04:25.482 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [gateway-zb-actors-0] WARN  io.zeebe.gateway - Failed to activate jobs for type start_job from partition 1
io.zeebe.gateway.cmd.ClientException: Failed to handle response
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:117) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$6(BrokerRequestManager.java:190) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:40) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
Caused by: io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
	at io.grpc.Status.asRuntimeException(Status.java:517) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:356) ~[grpc-stub-1.16.1.jar:1.16.1]
	at io.zeebe.gateway.impl.job.ActivateJobsHandler.activateJobs(ActivateJobsHandler.java:87) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.job.ActivateJobsHandler.lambda$activateJobs$1(ActivateJobsHandler.java:82) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:114) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	... 8 more
01:04:25.483 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [gateway-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
	at io.grpc.Status.asRuntimeException(Status.java:517) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:356) ~[grpc-stub-1.16.1.jar:1.16.1]
	at io.zeebe.gateway.impl.job.ActivateJobsHandler.activateJobs(ActivateJobsHandler.java:87) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.job.ActivateJobsHandler.lambda$activateJobs$1(ActivateJobsHandler.java:82) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:117) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$6(BrokerRequestManager.java:190) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:40) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
```

My process starting workflow instances on node0 starts throwing this:

```
rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

My task workers connected to node2 are freaking out, but I expect that. However, my task workers on node0 are saying:

```
calculate_feasibility    | 2018/12/11 01:06:06 Failed to activate jobs for worker default rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

## Recover node2

If I bring node2 back up, then things start working again.

## Simulate failure node1

If I bring node1 down, then everything grinds to a halt again, and I see this:

```
~/workspace/zeebe-broker-0.14.0
➜ bin/zbctl status --address node0
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 10.0.2.7:26501
    Partition 0 : Leader
    Partition 1 : Leader
  Broker 2 - 10.0.2.11:26501
    Partition 0 : Follower
    Partition 1 : Follower
```
## Recover node1

I bring node1 back up, and work starts flowing again, but node2 complains continually:

```
01:12:21.165 [zb-stream-processor] [10.0.2.11:26501-zb-actors-0] ERROR io.zeebe.broker.workflow.repository - Error on pushing deployment to partition 1. Retry request.
io.zeebe.transport.RequestTimeoutException: Request timed out after PT15S
	at io.zeebe.transport.impl.sender.OutgoingRequest.timeout(OutgoingRequest.java:151) ~[zb-transport-0.14.0.jar:0.14.0]
	at io.zeebe.transport.impl.sender.Sender.onTimerExpiry(Sender.java:483) ~[zb-transport-0.14.0.jar:0.14.0]
	at org.agrona.DeadlineTimerWheel.poll(DeadlineTimerWheel.java:284) ~[agrona-0.9.27.jar:0.9.27]
	at io.zeebe.transport.impl.sender.Sender.processTimeouts(Sender.java:114) ~[zb-transport-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
```

## Bounce node2

If I bring node2 down then back up to see if that will fix it. Now node0 starts streaming this:

```
01:17:21.565 [partition-0] [10.0.2.7:26501-zb-fs-workers-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.NullPointerException: null
```

## Bounce node0

I bring node0 down, then bring it back up. Now it's really toasted:

```
~/workspace/zeebe-broker-0.14.0
➜ bin/zbctl status --address node0
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 10.0.2.7:26501
    Partition 0 : Follower
```

OK, maybe it needs node1 and node2 in its `initialContactPoints`. So I add them, and bring it back up.

Now my cluster is operating like this:

```
~/workspace/zeebe-broker-0.14.0 took 2s
➜ bin/zbctl status --address node0
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 10.0.2.7:26501
    Partition 0 : Leader
  Broker 1 - 10.0.2.9:26501
    Partition 0 : Follower
    Partition 1 : Follower
  Broker 2 - 10.0.2.11:26501
    Partition 0 : Follower
    Partition 1 : Leader
```

node1 is throwing:

```
01:21:14.515 [zb-stream-processor] [10.0.2.9:26501-zb-actors-1] ERROR io.zeebe.util.actor - Actor failed in phase 'CLOSING'. Discard all jobs and stop immediatly.
java.lang.NullPointerException: null items are not supported in this collection
	at io.zeebe.util.sched.channel.ActorConditions.removeConsumer(ActorConditions.java:54) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.impl.service.LogStreamService.removeOnCommitPositionUpdatedCondition(LogStreamService.java:255) ~[zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.processor.StreamProcessorController.onActorClosing(StreamProcessorController.java:451) ~[zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
```

node2 is throwing:

```
01:21:40.413 [zb-stream-processor] [10.0.2.11:26501-zb-actors-1] ERROR io.zeebe.util.actor - Actor failed in phase 'CLOSING'. Discard all jobs and stop immediatly.
java.lang.NullPointerException: null items are not supported in this collection
	at io.zeebe.util.sched.channel.ActorConditions.removeConsumer(ActorConditions.java:54) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.impl.service.LogStreamService.removeOnCommitPositionUpdatedCondition(LogStreamService.java:255) ~[zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.processor.StreamProcessorController.onActorClosing(StreamProcessorController.java:451) ~[zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
```

node0 is throwing:
```
01:22:10.924 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [gateway-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
	at io.grpc.Status.asRuntimeException(Status.java:517) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:356) ~[grpc-stub-1.16.1.jar:1.16.1]
	at io.zeebe.gateway.impl.job.ActivateJobsHandler.activateJobs(ActivateJobsHandler.java:87) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.job.ActivateJobsHandler.lambda$activateJobs$1(ActivateJobsHandler.java:82) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:117) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$6(BrokerRequestManager.java:190) ~[zeebe-gateway-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:40) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
```

All clients are failing at this point. For example:

```
~/workspace/zeebe-broker-0.14.0
➜ bin/zbctl list --address node0 workflows
Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

## Restart all nodes

I restart all nodes.

The cluster comes up like this:

```
~/workspace/zeebe-broker-0.14.0
➜ bin/zbctl status --address node0
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 10.0.2.7:26501
    Partition 0 : Follower
  Broker 1 - 10.0.2.9:26501
    Partition 0 : Follower
    Partition 1 : Follower
  Broker 2 - 10.0.2.11:26501
    Partition 0 : Follower
    Partition 1 : Follower
```

I delete all the `data/partition-*` directories and start over to try to get it back to a consistent state.

Except now node1 throws:

```
Exception in thread "10.0.2.9:26501-zb-actors-0" java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:695)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at io.zeebe.transport.impl.sender.Sender$Batch.<init>(Sender.java:359)
	at io.zeebe.transport.impl.sender.Sender$ChannelWriteQueue.offer(Sender.java:338)
	at io.zeebe.transport.impl.sender.Sender.onMessageSubmitted(Sender.java:220)
	at io.zeebe.transport.impl.sender.Sender.processSubmittedMessages(Sender.java:150)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112)
```

And node0 streams:

```
01:34:47.365 [replicationApi.server-receiver] [10.0.2.7:26501-zb-actors-1] WARN  io.zeebe.raft - dropping
```

Could this particular aspect be related to https://github.com/zeebe-io/zeebe/issues/511?

I remove the `initialContactPoints` from node0's configuration, bring all nodes down and delete all `data/partition-*`, then bring up node0, then node1, then node2.

Now, node0 only sees itself.

```
~/workspace/zeebe-broker-0.14.0
➜ bin/zbctl status --address node0
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 10.0.2.7:26501
    Partition 0 : Leader
    Partition 1 : Follower
```

node1 only sees node0:

```
~/workspace/zeebe-broker-0.14.0
➜ bin/zbctl status --address node1
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 0 - 10.0.2.7:26501
    Partition 0 : Leader
    Partition 1 : Follower
```

And node2 sees itself and node1:

```
~/workspace/zeebe-broker-0.14.0
➜ bin/zbctl status --address node2
Cluster size: 3
Partitions count: 2
Replication factor: 3
Brokers:
  Broker 1 - 10.0.2.9:26501
    Partition 0 : Follower
    Partition 1 : Leader
  Broker 2 - 10.0.2.11:26501
    Partition 0 : Leader
    Partition 1 : Follower
```

**Comment by Zelldon** [comment] 2018-12-11 06:07
Hey @jwulf ,

thanks for the detailed issue description and investigation.
Please be aware that currently the cluster is not that stable that it should be. We try to tackle this in the next quarter. 

----

How do you bring the nodes down? With `CTRL+C`? Do you see log statements like Broker closed?
Currently on broker close the Broker will leave the RAFT cluster and on restart it should join the cluster again. We will fix this in the near future https://github.com/zeebe-io/zeebe/issues/1076. To join an existing cluster it needs an `LEADER` to commit the "configuration" change. If you restart all nodes there will be no leader. Since you remove all the data it is like an reset and it will bootstrap all the partitions again.

---

I assume that exceptions like:

```java
01:03:10.242 [zb-stream-processor] [10.0.2.7:26501-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'CLOSING'. Discard all jobs and stop immediatly.
java.lang.NullPointerException: null items are not supported in this collection
	at io.zeebe.util.sched.channel.ActorConditions.removeConsumer(ActorConditions.java:54) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.impl.service.LogStreamService.removeOnCommitPositionUpdatedCondition(LogStreamService.java:255) ~[zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.processor.StreamProcessorController.onActorClosing(StreamProcessorController.java:451) ~[zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
```

Are kind of OK, since they will do no harm (are thrown in the StreamProcessor close) but yes they are a bit weird. I will try to reproduce them.

----

The following exception seems weird:
```java
01:12:21.165 [zb-stream-processor] [10.0.2.11:26501-zb-actors-0] ERROR io.zeebe.broker.workflow.repository - Error on pushing deployment to partition 1. Retry request.
io.zeebe.transport.RequestTimeoutException: Request timed out after PT15S
	at io.zeebe.transport.impl.sender.OutgoingRequest.timeout(OutgoingRequest.java:151) ~[zb-transport-0.14.0.jar:0.14.0]
	at io.zeebe.transport.impl.sender.Sender.onTimerExpiry(Sender.java:483) ~[zb-transport-0.14.0.jar:0.14.0]
	at org.agrona.DeadlineTimerWheel.poll(DeadlineTimerWheel.java:284) ~[agrona-0.9.27.jar:0.9.27]
	at io.zeebe.transport.impl.sender.Sender.processTimeouts(Sender.java:114) ~[zb-transport-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
```
Do you have deployed between the closing and restarting of the nodes?
Would be nice if you/we can create separate issues for the particular errors.

----

Regarding to your `OutOfMemory` exception:
What is the configured direct memory pool size of your VM?

**Comment by jwulf** [comment] 2018-12-11 06:53
Thanks for the response @Zelldon.

> How do you bring the nodes down? With CTRL+C?
Yes

> Do you see log statements like Broker closed?
Yes

> What is the configured direct memory pool size of your VM?
I'm not doing any configuration beyond the `zeebe.cfg.toml` and using `bin/broker` to start. These are 8GB Ubuntu instances on Azure. Is there something I should check?

I've started modifying a fork of https://github.com/camunda-consulting/zeebe-examples/tree/master/aws-cluster-performance to use zeebe-0.14.0 so that the configuration is declarative and deterministic. It's going to be easier to report clustering issues against that as a reproducer.

**Comment by jwulf** [comment] 2018-12-11 12:36
Perhaps the leader/follower issue (under the heading "Restart all nodes" above) is https://github.com/zeebe-io/zeebe/issues/1327?

**Comment by Zelldon** [comment] 2019-12-09 14:50
We did a lot of changes and improvements regarding the clustering topic. I assume this issue is out dated that is why I will close this. Feel free to re open this again.

**Closed by Zelldon** 2019-12-09 14:50 UTC
