### ISSUE TITLE
Nullpointer in AppendRequest

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4087] opened 2020-03-20 07:27 UTC
**Description**

It might be that these exception are related to out of memory errors?

```
I 2020-03-20T07:06:27.034160130Z 2020-03-20 07:06:27.033 [] [raft-server-1-raft-partition-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message
 
I 2020-03-20T07:06:27.034766284Z 2020-03-20 07:06:27.034 [] [raft-server-0-system-partition-1] ERROR io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - An uncaught exception occurred
 
I 2020-03-20T07:06:27.034809104Z java.lang.NullPointerException: leader cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897) ~[guava-28.2-jre.jar:?]
	at io.atomix.protocols.raft.protocol.AppendRequest$Builder.withLeader(AppendRequest.java:184) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?]
	at io.atomix.protocols.raft.roles.AbstractAppender.buildAppendEmptyRequest(AbstractAppender.java:102) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?]
	at io.atomix.protocols.raft.roles.AbstractAppender.buildAppendRequest(AbstractAppender.java:79) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?]
	at io.atomix.protocols.raft.roles.LeaderAppender.appendEntries(LeaderAppender.java:369) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?]
	at io.atomix.protocols.raft.roles.LeaderAppender.appendEntries(LeaderAppender.java:130) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.appendMembers(LeaderRole.java:1005) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:182) [atomix-utils-3.2.0-20200318.171617-141.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-03-20T07:06:27.035313626Z 2020-03-20 07:06:27.034 [] [raft-server-0-system-partition-1] ERROR io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - An uncaught exception occurred
 
I 2020-03-20T07:06:27.035341423Z java.lang.NullPointerException: leader cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897) ~[guava-28.2-jre.jar:?]
	at io.atomix.protocols.raft.protocol.ConfigureRequest$Builder.withLeader(ConfigureRequest.java:165) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?]
	at io.atomix.protocols.raft.roles.AbstractAppender.buildConfigureRequest(AbstractAppender.java:354) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?]
	at io.atomix.protocols.raft.roles.LeaderAppender.appendEntries(LeaderAppender.java:349) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?]
	at io.atomix.protocols.raft.roles.LeaderAppender.appendEntries(LeaderAppender.java:130) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.appendMembers(LeaderRole.java:1005) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:182) [atomix-utils-3.2.0-20200318.171617-141.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
E 2020-03-20T07:06:27.036013207Z Mar 20, 2020 7:06:11 AM io.grpc.netty.NettyServerTransport notifyTerminated
 
E 2020-03-20T07:06:27.036032149Z INFO: Transport failed
 
E 2020-03-20T07:06:27.036037688Z java.lang.OutOfMemoryError: Java heap space

 
```

Before them I see a lot of 

```
I 2020-03-20T07:06:19.850722839Z 2020-03-20 07:06:19.850 [] [raft-server-1-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to install 2
 
I 2020-03-20T07:06:20.100611819Z 2020-03-20 07:06:20.100 [] [raft-server-1-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to install 2
 
I 2020-03-20T07:06:20.350209707Z 2020-03-20 07:06:20.350 [] [raft-server-1-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to install 2
 
I 2020-03-20T07:06:20.600470968Z 2020-03-20 07:06:20.600 [] [raft-server-1-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to install 2
 
I 2020-03-20T07:06:20.850277932Z 2020-03-20 07:06:20.850 [] [raft-server-1-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to install 2
 
I 2020-03-20T07:06:21.103746762Z 2020-03-20 07:06:21.103 [] [raft-server-1-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to install 2
 
I 2020-03-20T07:06:21.352387727Z 2020-03-20 07:06:21.352 [] [raft-server-1-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to install 2
 
```

**Comment by deepthidevaki** [comment] 2020-03-20 12:23
Observed similar behavior 

https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=zeebe-io&minLogLevel=0&expandAll=false&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22dd-raft-onfailure-inactive%22%0Alabels.k8s-pod%2Fapp%3D%22dd-raft-onfailure-inactive-zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22dd-raft-onfailure-inactive%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22%0ANOT%20%22io.zeebe.gateway%22&scrollTimestamp=2020-03-20T11%3A58%3A36.429715153Z&pinnedLogId=jctgal13t1lc43mk8&pinnedLogTimestamp=2020-03-20T11%3A58%3A36.429686730Z

**Comment by npepinpe** [comment] 2020-03-23 08:31
Unfortunately our code doesn't cope well with us catching OOM errors, resulting in classes ending up in weird state (e.g. the LeaderAppender having no known leader when it is clearly the leader, as it looks like it here). What's strange for me is we end up with memory leaks because we failed to install a snapshot? That's really weird...

I expect with Deepthi's recent fixes we shouldn't be catching OOMs anymore so this wouldn't be as big of an issue, and I have a pending PR to handle failures with snapshot replication. Let's still wait a bit, but I expect this particular issue will be solved.

**Comment by deepthidevaki** [comment] 2020-03-25 14:06
Couldn't reproduce it. I hope with the recent changes to failure handling in raft we prevent such states. Will close this for now.

**Closed by deepthidevaki** 2020-03-25 14:06 UTC
Labels: Type: Bug, Type: Maintenance
