### ISSUE TITLE
Broker ends up in a weird state when chaos testing it under load

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2618] opened 2019-06-14 08:27 UTC
Trying to reproduce #2435, I was stress testing a local cluster (3 nodes, 2 partitions, replication factor 3) with our benchmark, and randomly restarting nodes, and sometimes stopping the benchmark to allow Atomix to compact. Brokers compacted our own local logstream at least once as well.

Anyway, I ended up in a weird state where a broker, on reprocessing, is skipping tons of `WorkflowInstanceRecord` because the element instances they point to doesn't exist in the RocksDB state :s

Once in that state, this broker fails all (most? didn't verify) requests from the benchmark program as well :s

[weird-broker.tar.gz](https://drive.google.com/file/d/1p3JIa-qWryLKdFcB0_kns9InfxWR3t-a/view?usp=sharing) (you'll need a @camunda.com google account to see it I think)

**Comment by Zelldon** [comment] 2019-06-14 08:31
Maybe snapshot replication didn't worked as expected? Are there any exception before that state exceptions?

**Comment by npepinpe** [comment] 2019-06-14 08:35
Since I was restarting the brokers a lot I lost the logs in between, so I can't tell really :disappointed: 

Also, these aren't exceptions, just logs, since there are cases where some workflow records need to be skipped since no element exists for them. Here it's just too unlikely that so many records would end up being skipped.

**Comment by Zelldon** [comment] 2019-06-14 08:37
So you tested locally or in k8? If in k8 then should still have the pvc?

**Comment by npepinpe** [comment] 2019-06-14 08:37
Locally, and it only has the console log :s

**Comment by Zelldon** [comment] 2019-06-14 08:37
Ah damn :see_no_evil:

**Comment by deepthidevaki** [comment] 2019-06-14 14:07
I was able to reproduce this state (once). Set up: 3 brokers (docker containers). broker-1 is the leader.  After some load, broker-1 takes a snapshot (snapshotId = X for example) and replicates it. Perform some more operations. broker-1 stops. broker-2 become leader, everything works. broker-1 comes back, broker-2 dies and broker-1 becomes leader again. At this point, this weird state is triggered. 

broker-1 has a snapshot (snapshot Id = Y for example) which is greater that X. Broker-1 is recovering using snapshot Y. But, from the logs, snapshot Y is never created or replicated (:thinking: ). snapshot Y also doesn't exists in any other brokers.

Hypothesis: snapshot Y is taken when broker-1 stops. Snapshot creation is enforced when a broker is closed. Could it be that this snapshot is corrupted because the broker (container) is closing at the same time?

**Comment by npepinpe** [comment] 2019-06-14 14:12
In theory the service container will close dependents first, such that things closing at the same time should theoretically be independent. Of course in practice maybe we don't connect dependencies properly and so there's a race condition where sometimes something is closed too soon or some such?

**Comment by npepinpe** [comment] 2019-06-26 14:32
Happened again today while I was testing, so definitely not solved 💩

**Comment by Zelldon** [comment] 2019-07-03 06:34
Ok saw this again on my small chaos test. After killing node 1, which was leader of 5 partitions zeebe-0 took over and printed 'million' lines of 

```
06:27:29.822 [stream-processor] [zeebe-0.zeebe.default.svc.cluster.local:26501-zb-actors-3] DEBUG io.zeebe.broker.workflow - Skipping record {"bpmnProcessId":"benchmark","version":1,"workflowKey":2251799813685263,"workflowInstanceKey":13510798882399026,"elementId":"sequenceFlow_f56027dc-5753-4247-b01e-649bfde147a3","flowScopeKey":13510798882399026,"bpmnElementType":"SEQUENCE_FLOW"} due to step guard; in-memory element is null
06:27:29.822 [stream-processor] [zeebe-0.zeebe.default.svc.cluster.local:26501-zb-actors-3] DEBUG io.zeebe.broker.workflow - Skipping record {"bpmnProcessId":"benchmark","version":1,"workflowKey":2251799813685263,"workflowInstanceKey":13510798882374083,"elementId":"end","flowScopeKey":13510798882374083,"bpmnElementType":"END_EVENT"} due to step guard; in-memory element is null
06:27:29.822 [stream-processor] [zeebe-0.zeebe.default.svc.cluster.local:26501-zb-actors-3] DEBUG io.zeebe.broker.workflow - Skipping record {"bpmnProcessId":"benchmark","version":1,"workflowKey":2251799813685263,"workflowInstanceKey":13510798882374075,"elementId":"end","flowScopeKey":13510798882374075,"bpmnElementType":"END_EVENT"} due to step guard; in-memory element is null
06:27:29.822 [stream-processor] [zeebe-0.zeebe.default.svc.cluster.local:26501-zb-actors-3] DEBUG io.zeebe.broker.workflow - Skipping record {"bpmnProcessId":"benchmark","version":1,"workflowKey":2251799813685263,"workflowInstanceKey":13510798882399060,"elementId":"start","flowScopeKey":13510798882399060,"bpmnElementType":"START_EVENT"} due to step guard; in-memory element is null
```

**Closed** 2019-07-03 08:19 UTC
Labels: Scope: broker, Status: Ready, Type: Bug
