### ISSUE TITLE
Records are not reprocessed after restart

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#3202] opened 2019-10-17 09:58 UTC
**Describe the bug**
After a broker restart, it can happen that records are not reprocessed. This can lead to workflow instances that are not continued after the restart. 

It seems that this is a synchronization problem between the process processing and the snapshotting. It assumes that the snapshot is valid (i.e. last written event is committed) but it between a new record is processed (i.e. last process position is updated in the state).  

**To Reproduce**
First of all, it seems that this is not reproducible consistently. It just happens rarely. 

* deploy a workflow
* create a new instance
* after receiving the response, shut down the broker gracefully (snapshot is created on closing!)
* start the broker and see if the workflow instance is continued 

**Expected behavior**
The records are reprocessed after startup.

**Log/Stacktrace**

```
Enforce snapshot creation. Last successful processed position is 4294975952.

Recovered state of partition 1 from snapshot at position 4294976120

{"valueType":"WORKFLOW_INSTANCE_CREATION","key":-1,"position":4294975952,"timestamp":1571295696405,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":0,"workflowInstanceKey":-1,"workflowKey":2251799813685249,"bpmnProcessId":"","variables":{}},"sourceRecordPosition":-1}

{"valueType":"WORKFLOW_INSTANCE","key":2251799813685251,"position":4294976120,"timestamp":1571295696408,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685251,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":-1,"bpmnElementType":"PROCESS","elementId":"process"},"sourceRecordPosition":4294975952}
```

<details><summary>Log Output from integration test</summary>
 <p>

```
09:01:36.409 [] [main] INFO  io.zeebe.broker.system - Broker shutting down...
09:01:36.410 [exporter] [0.0.0.0:25622-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter'.
09:01:36.411 [] [zb-blocking-task-runner-6-0.0.0.0:25622] DEBUG io.zeebe.gateway - Closing gateway broker client ...
09:01:36.412 [] [zb-blocking-task-runner-6-0.0.0.0:25622] DEBUG io.zeebe.gateway - topology manager closed
09:01:36.412 [service-container-main] [0.0.0.0:25622-zb-actors-0] DEBUG io.zeebe.servicecontainer - Removed service exporter.manager
09:01:36.412 [partition-1-processor-snapshot-director] [0.0.0.0:25622-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Enforce snapshot creation. Last successful processed position is 4294975952.

...

09:01:39.044 [io.zeebe.broker.system.monitoring.BrokerHealthCheckService] [0.0.0.0:25622-zb-actors-1] INFO  io.zeebe.broker.system - All partitions are installed. Broker is ready!
09:01:39.044 [topology] [0.0.0.0:25622-zb-actors-0] DEBUG io.zeebe.broker.clustering - Updating partition information for partition 1 on Node{nodeId=0, commandApi=0.0.0.0:25622} with state LEADER
09:01:39.044 [partition-1-processor] [0.0.0.0:25622-zb-actors-1] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
09:01:39.044 [exporter] [0.0.0.0:25622-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
09:01:39.044 [partition-1-processor] [0.0.0.0:25622-zb-actors-1] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position 4294976120
09:01:39.045 [exporter] [0.0.0.0:25622-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovered exporter 'exporter' from snapshot at lastExportedPosition -1
09:01:39.045 [exporter] [0.0.0.0:25622-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Configure exporter with id 'test-recorder'
09:01:39.045 [exporter] [0.0.0.0:25622-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={SBE_UNKNOWN=true, COMMAND=true, EVENT=true, COMMAND_REJECTION=true, NULL_VAL=true}, acceptValueTypes={INCIDENT=true, ERROR=true, DEPLOYMENT=true, MESSAGE=true, EXPORTER=true, NULL_VAL=true, WORKFLOW_INSTANCE_CREATION=true, SBE_UNKNOWN=true, WORKFLOW_INSTANCE=true, JOB=true, VARIABLE=true, VARIABLE_DOCUMENT=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, TIMER=true, WORKFLOW_INSTANCE_SUBSCRIPTION=true, MESSAGE_SUBSCRIPTION=true, JOB_BATCH=true}}
09:01:39.045 [exporter] [0.0.0.0:25622-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Open exporter with id 'test-recorder'
09:01:39.045 [partition-1-processor] [0.0.0.0:25622-zb-actors-1] TRACE io.zeebe.processor - Start scanning the log for error events.
09:01:39.046 [partition-1-processor] [0.0.0.0:25622-zb-actors-1] TRACE io.zeebe.processor - Finished scanning the log for error events.
09:01:39.046 [partition-1-processor-snapshot-director] [0.0.0.0:25622-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - The position of the last valid snapshot is '4294975952'. Taking snapshots beyond this position.

...

09:01:45.064 [] [main] INFO  io.zeebe.test.records - Test failed, following records where exported:
09:01:45.132 [] [main] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":-1,"position":4294967296,"timestamp":1571295696360,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfZWEzYWJlMDEtODZlYS00ZWJjLTgxOGQtMmE4YzkwNjRjNTkyIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2ExODJiYTgwLTdhMzktNGRiMy05YTg4LWRkOTE0Mzg3YzQwYiI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfYWRhMDlhMWYtNTlkMS00MjdiLWIxYzctYzhlYmRmMDdmY2MyPC9vdXRnb2luZz4KICAgIDwvc3RhcnRFdmVud...
09:01:45.133 [] [main] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":4294969392,"timestamp":1571295696391,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfZWEzYWJlMDEtODZlYS00ZWJjLTgxOGQtMmE4YzkwNjRjNTkyIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2ExODJiYTgwLTdhMzktNGRiMy05YTg4LWRkOTE0Mzg3YzQwYiI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfYWRhMDlhMWYtNTlkMS00MjdiLWIxYzctYzhlYmRmMDdmY2MyPC9vdXRnb2luZz4KICAgIDwv...
09:01:45.133 [] [main] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":4294971584,"timestamp":1571295696396,"recordType":"COMMAND","intent":"DISTRIBUTE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfZWEzYWJlMDEtODZlYS00ZWJjLTgxOGQtMmE4YzkwNjRjNTkyIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2ExODJiYTgwLTdhMzktNGRiMy05YTg4LWRkOTE0Mzg3YzQwYiI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfYWRhMDlhMWYtNTlkMS00MjdiLWIxYzctYzhlYmRmMDdmY2MyPC9vdXRnb2luZz4KICA...
09:01:45.133 [] [main] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":4294973776,"timestamp":1571295696399,"recordType":"EVENT","intent":"DISTRIBUTED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfZWEzYWJlMDEtODZlYS00ZWJjLTgxOGQtMmE4YzkwNjRjNTkyIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2ExODJiYTgwLTdhMzktNGRiMy05YTg4LWRkOTE0Mzg3YzQwYiI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfYWRhMDlhMWYtNTlkMS00MjdiLWIxYzctYzhlYmRmMDdmY2MyPC9vdXRnb2luZz4KICAg...
09:01:45.152 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":-1,"position":4294975952,"timestamp":1571295696405,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":0,"workflowInstanceKey":-1,"workflowKey":2251799813685249,"bpmnProcessId":"","variables":{}},"sourceRecordPosition":-1}
09:01:45.152 [] [main] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":-1,"position":4294967296,"timestamp":1571295696360,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfZWEzYWJlMDEtODZlYS00ZWJjLTgxOGQtMmE4YzkwNjRjNTkyIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2ExODJiYTgwLTdhMzktNGRiMy05YTg4LWRkOTE0Mzg3YzQwYiI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfYWRhMDlhMWYtNTlkMS00MjdiLWIxYzctYzhlYmRmMDdmY2MyPC9vdXRnb2luZz4KICAgIDwvc3RhcnRFdmVud...
09:01:45.152 [] [main] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":4294969392,"timestamp":1571295696391,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfZWEzYWJlMDEtODZlYS00ZWJjLTgxOGQtMmE4YzkwNjRjNTkyIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2ExODJiYTgwLTdhMzktNGRiMy05YTg4LWRkOTE0Mzg3YzQwYiI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfYWRhMDlhMWYtNTlkMS00MjdiLWIxYzctYzhlYmRmMDdmY2MyPC9vdXRnb2luZz4KICAgIDwv...
09:01:45.152 [] [main] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":4294971584,"timestamp":1571295696396,"recordType":"COMMAND","intent":"DISTRIBUTE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfZWEzYWJlMDEtODZlYS00ZWJjLTgxOGQtMmE4YzkwNjRjNTkyIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2ExODJiYTgwLTdhMzktNGRiMy05YTg4LWRkOTE0Mzg3YzQwYiI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfYWRhMDlhMWYtNTlkMS00MjdiLWIxYzctYzhlYmRmMDdmY2MyPC9vdXRnb2luZz4KICA...
09:01:45.153 [] [main] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":4294973776,"timestamp":1571295696399,"recordType":"EVENT","intent":"DISTRIBUTED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfZWEzYWJlMDEtODZlYS00ZWJjLTgxOGQtMmE4YzkwNjRjNTkyIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2ExODJiYTgwLTdhMzktNGRiMy05YTg4LWRkOTE0Mzg3YzQwYiI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfYWRhMDlhMWYtNTlkMS00MjdiLWIxYzctYzhlYmRmMDdmY2MyPC9vdXRnb2luZz4KICAg...
09:01:45.153 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":-1,"position":4294975952,"timestamp":1571295696405,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":0,"workflowInstanceKey":-1,"workflowKey":2251799813685249,"bpmnProcessId":"","variables":{}},"sourceRecordPosition":-1}
09:01:45.154 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685251,"position":4294976120,"timestamp":1571295696408,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685251,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":-1,"bpmnElementType":"PROCESS","elementId":"process"},"sourceRecordPosition":4294975952}
09:01:45.155 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":2251799813685252,"position":4294976344,"timestamp":1571295696408,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685251,"workflowKey":2251799813685249,"bpmnProcessId":"process","variables":{}},"sourceRecordPosition":4294975952}
09:01:45.155 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":-1,"position":8589934592,"timestamp":1571295699964,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":0,"workflowInstanceKey":-1,"workflowKey":2251799813685249,"bpmnProcessId":"","variables":{}},"sourceRecordPosition":-1}
09:01:45.155 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":8589934760,"timestamp":1571295700003,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":-1,"bpmnElementType":"PROCESS","elementId":"process"},"sourceRecordPosition":8589934592}
09:01:45.155 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":2251799813685254,"position":8589934984,"timestamp":1571295700003,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","variables":{}},"sourceRecordPosition":8589934592}
09:01:45.156 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":8589935184,"timestamp":1571295700009,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":-1,"bpmnElementType":"PROCESS","elementId":"process"},"sourceRecordPosition":8589934760}
09:01:45.156 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":8589935424,"timestamp":1571295700013,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":2251799813685253,"bpmnElementType":"START_EVENT","elementId":"startEvent_a182ba80-7a39-4db3-9a88-dd914387c40b"},"sourceRecordPosition":8589935184}
09:01:45.156 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":8589935720,"timestamp":1571295700016,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":2251799813685253,"bpmnElementType":"START_EVENT","elementId":"startEvent_a182ba80-7a39-4db3-9a88-dd914387c40b"},"sourceRecordPosition":8589935424}
09:01:45.156 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":8589936016,"timestamp":1571295700020,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":2251799813685253,"bpmnElementType":"START_EVENT","elementId":"startEvent_a182ba80-7a39-4db3-9a88-dd914387c40b"},"sourceRecordPosition":8589935720}
09:01:45.157 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":8589936312,"timestamp":1571295700023,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":2251799813685253,"bpmnElementType":"START_EVENT","elementId":"startEvent_a182ba80-7a39-4db3-9a88-dd914387c40b"},"sourceRecordPosition":8589936016}
09:01:45.157 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685256,"position":8589936608,"timestamp":1571295700027,"recordType":"EVENT","intent":"SEQUENCE_FLOW_TAKEN","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":2251799813685253,"bpmnElementType":"SEQUENCE_FLOW","elementId":"sequenceFlow_ada09a1f-59d1-427b-b1c7-c8ebdf07fcc2"},"sourceRecordPosition":8589936312}
09:01:45.157 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685257,"position":8589936904,"timestamp":1571295700030,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":2251799813685253,"bpmnElementType":"END_EVENT","elementId":"endEvent_bb1d2ec8-27cc-4fe3-8edd-d7232f07a99b"},"sourceRecordPosition":8589936608}
09:01:45.157 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685257,"position":8589937192,"timestamp":1571295700034,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":2251799813685253,"bpmnElementType":"END_EVENT","elementId":"endEvent_bb1d2ec8-27cc-4fe3-8edd-d7232f07a99b"},"sourceRecordPosition":8589936904}
09:01:45.157 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685257,"position":8589937480,"timestamp":1571295700037,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":2251799813685253,"bpmnElementType":"END_EVENT","elementId":"endEvent_bb1d2ec8-27cc-4fe3-8edd-d7232f07a99b"},"sourceRecordPosition":8589937192}
09:01:45.157 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685257,"position":8589937768,"timestamp":1571295700041,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":2251799813685253,"bpmnElementType":"END_EVENT","elementId":"endEvent_bb1d2ec8-27cc-4fe3-8edd-d7232f07a99b"},"sourceRecordPosition":8589937480}
09:01:45.157 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":8589938056,"timestamp":1571295700044,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":-1,"bpmnElementType":"PROCESS","elementId":"process"},"sourceRecordPosition":8589937768}
09:01:45.157 [] [main] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":8589938296,"timestamp":1571295700048,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685253,"workflowKey":2251799813685249,"bpmnProcessId":"process","flowScopeKey":-1,"bpmnElementType":"PROCESS","elementId":"process"},"sourceRecordPosition":8589938056}
```

</p>
</details>

**Environment:**
 - Zeebe Version:0.21.1

**Comment by npepinpe** [comment] 2020-02-11 13:57
After investigating this, we came to the conclusion that:

1. It's difficult to reproduce (we couldn't reproduce it anymore after running the above scenario > 1000 times)
1. There was a lot of refactoring done around the LogStream and AsyncSnapshotDirector

It may have been fixed - not intentionally but simply because we changed the behavior of the log stream. I will then close this for now as it's not productive to keep spending more time, and if it happens again the results should be very noticeable.

**Closed by npepinpe** 2020-02-11 13:57 UTC
Labels: Scope: broker, Status: In Progress, Type: Bug
