### ISSUE TITLE
Exporter position is not updated if the record is fiterted

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#3166] opened 2019-10-09 13:19 UTC
**Describe the bug**
An exporter can set a filter to only get the records it is interested in. If the exporter never gets a record then its position is never updated. If the exporter position is not updated then the broker can not delete data. In the worst case, the broker can run out of data.

This situation can happen, for example, if no workflows are executed but job workers are polling the broker. For each poll, it writes some records to the log stream that are usually not exported. 

**To Reproduce**
Start the broker and some job workers. See how the data is increasing - and not deleted after reaching the max snapshot count.

**Expected behavior**
The exporter position is updated if the record is filtered. But only, if the position of the last exported record is updated by the exported.

**Environment:**
 - Zeebe Version: 0.21.0
 - Configuration: at least one exporter with filter

**Comment by afirth** [comment] 2020-08-13 08:59
@npepinpe if this is the root cause of 2020-08-07 Zeebe statefulset replica mismatch, does it make sense to bump the priority and severity? Is this now release blocking?

**Comment by npepinpe** [comment] 2020-08-13 09:07
It's not blocking the release as it wasn't introduced by the release, and it will be re-prioritized during our next triage session (which is on hold due to hack days).

**Comment by npepinpe** [comment] 2020-08-17 12:09
Was re-prioritized as mid again as this is expected to affect users are not using their clusters - that last known affected users was running workers without ever creating instances. It's counter intuitive and should be fixed before GA, but can be deferred to the next quarter/version.

**Comment by afirth** [comment] 2020-09-17 09:02
any bright ideas on dirty workarounds?

**Comment by npepinpe** [comment] 2020-09-17 09:05
We could manually update the exported position in the state? That's pretty hacky and requires us to find a safe one.

**Comment by npepinpe** [comment] 2020-09-17 11:21
One workaround in our cloud would be to export job batch commands for the Domo cluster, and just run curator more aggressively.

**Comment by npepinpe** [comment] 2020-09-17 13:03
I did a PoC of the solution initially proposed by @saig0 - for every exporter, we keep track of the last unacknowledged record AND the last acknowledged record. When an exporter skips/filters out a record, if its last unacknowledged record position is <= its last acknowledged position, we update the last acknowledged position to the skipped/filtered out record position. This is safe to do as this means there were no records in between (for this exporter) that were not skipped.

The PoC clearly works, it would just need a little bit of clean up (tests are a little painful to write :slightly_smiling_face:).

**Closed** 2020-09-25 15:03 UTC
Labels: Impact: Availability, Impact: Data, Priority: Mid, Scope: broker, Severity: Mid, Status: Needs Review, Type: Bug, hacktoberfest
