### ISSUE TITLE
A node took 5 hours to restart

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#5208] opened 2020-08-20 07:39 UTC
**Describe the bug**

In one of the test cluster, observed that a node (zeebe-2) took 5 hours to become ready after a restart. Partitions 2 and 3 joined successfully, but partition 1 did not. When inspecting the logs, found the following [stackdriver](
https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-08-19T17%3A53%3A42.000000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22dd-snapshot-zeebe-2%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22dd-snapshot%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.container_name%3D%22zeebe-cluster%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Atimestamp%3D%222020-08-19T15%3A50%3A47.561453000Z%22%0AinsertId%3D%22l289ilaec07xk8451%22&scrollTimestamp=2020-08-19T21%3A37%3A28.717761000Z) 

```
W 2020-08-19T15:50:47.561453Z Received invalid handshake, closing connection 
W 2020-08-19T15:50:47.774508Z An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. 
```

At this time zeebe-0 was leader for partition 1. After 5 hours zeebe-0 was restarted and zeebe-1 was elected as leader for partition 1. Zeebe-2 was able to join successfully after this.

This looks like a similar issue as #5116 . But not sure if it is the same reason.

**Comment by npepinpe** [comment] 2020-09-15 09:41
Let's give it a few weeks after release, and if we never see it again, let's close it.

**Comment by npepinpe** [comment] 2021-01-12 09:38
Closing for now as we lost info related to this cluster. The problem isn't necessarily gone, but the general problem isn't a "single issue" kind of problem - we still need to improve restart time, however we have issues covering this topic, so I don't see much point in keeping this one.

**Closed by npepinpe** 2021-01-12 09:38 UTC
Labels: Impact: Availability, Priority: Low, Scope: broker, Type: Bug
