### ISSUE TITLE
LongPollingActivateJobsTest.shouldProbeIfNoNotificationReceived flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4608] opened 2020-05-27 07:44 UTC
**Summary**

- How often does the test fail? - at least once so far
- Does it block your work? - no
- Do we suspect that it is a real failure? - unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Error Message

activateJobsStub.handle(<any>);
Wanted 16 times:
-> at io.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldProbeIfNoNotificationReceived(LongPollingActivateJobsTest.java:208)
But was 8 times:
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)

Stacktrace

org.mockito.exceptions.verification.TooFewActualInvocations: 

activateJobsStub.handle(<any>);
Wanted 16 times:
-> at io.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldProbeIfNoNotificationReceived(LongPollingActivateJobsTest.java:208)
But was 8 times:
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)
-> at io.zeebe.gateway.api.util.StubbedBrokerClient.sendRequest(StubbedBrokerClient.java:56)

	at io.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldProbeIfNoNotificationReceived(LongPollingActivateJobsTest.java:208)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
Standard Output

20:16:40.634 [main] INFO  io.zeebe.test - Test finished: shouldProbeNextRequestWhenBlockedRequestsTimedOut(io.zeebe.gateway.api.job.LongPollingActivateJobsTest)
20:16:40.635 [main] INFO  io.zeebe.test - Test started: shouldProbeIfNoNotificationReceived(io.zeebe.gateway.api.job.LongPollingActivateJobsTest)
</pre>
</details>

**Comment by pihme** [comment] 2020-07-22 13:50
@deepthidevaki Do you have an advice on how to deal with this flaky test?

I can reproduce the log output, if I reduce the timeout in the verify clause
```
    // then
    verify(stub, timeout(10).times(2 * partitionsCount)).handle(any());
```

So one option would be to blindly increase the timeout. Maybe not just in this method, but in all methods in the test class.

On the other hand, I don't really understand what the test is actually doing, so I would prefer to improve the test.

What would you advice?

**Comment by deepthidevaki** [comment] 2020-07-22 15:05
What the test is doing is:
1. Send one activate job requests
2. Request will be send to all partitions - handled by the `stub`
3. No jobs available, so the request is put in the long polling queue
4. Increase the clock by `probeTimeout`
5. Expected behavior = At each probeTimeout, the request is re-send to the brokers to see if there are new jobs available.
6. Verify the requests are received by the `stub` twice - one for the first attempt (step 2) and one for the retry

2s timeout seems to be long enough for this case. So I don't feel confident that test will be fixed by increasing the timeout. 
If you have any idea on how to improve the test, feel free to do it. Also probably adding/enabling more log statements would help in future. 

One hypothesis I have is that increasing the clock by the exact `probeTimeout` is not ideal. May be the difference in time is not large enough to trigger a probe.

**Comment by pihme** [comment] 2020-07-22 15:12
Can you say more about the clock handling? 
Will the clock advance on its own, or will it only advance when we increase it, or will it advance on its own + when we increase it? 
Also the scheduled probeTimeout timer, will this be scheduled accoridng to the system clock or the agents virtual clock?

**Comment by deepthidevaki** [comment] 2020-07-23 09:39
@pihme We use `ControlledActorClock` in tests. It uses system time + the offset that we added as the current time. So it advances on its own + when we increase it.

**Comment by npepinpe** [comment] 2020-12-17 14:16
Closing as this hasn't happened in a while, and the CI pipeline is a lot more stable now. Please re-open if you see this occur again.

**Closed by npepinpe** 2020-12-17 14:16 UTC
Labels: Priority: Mid, Status: Planned, Type: Unstable Test

**Comment by megglos** [comment] 2023-09-27 09:05
happened again on a stable/8.2 PR https://github.com/camunda/zeebe/actions/runs/6323507254/job/17171199234 would leave it closed for now though if that was the only occurrence since 2020 :D
