### ISSUE TITLE
LogBlockIndexController has illegal position for new block

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#761] opened 2018-03-20 08:41 UTC
On executing the new performance tests with a single node I got the following exceptions:

```java

java.lang.IllegalArgumentException: Illegal value for position.Value=12885042464, last value in index=12885042464. Must provide positions in ascending order.
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.addBlock(LogBlockIndex.java:186)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIdx(LogBlockIndexController.java:319)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIndex(LogBlockIndexController.java:304)
	at io.zeebe.logstreams.impl.LogBlockIndexController.tryToCreateBlockIndex(LogBlockIndexController.java:281)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:117)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:172)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:147)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119)
09:37:01.159 [localhost:51015-zb-actors-0] ERROR io.zeebe.logstreams - Can't read from illegal address: 11329952
java.lang.IllegalArgumentException: Illegal value for position.Value=17181968304, last value in index=17181968304. Must provide positions in ascending order.
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.addBlock(LogBlockIndex.java:186)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIdx(LogBlockIndexController.java:319)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIndex(LogBlockIndexController.java:304)
	at io.zeebe.logstreams.impl.LogBlockIndexController.tryToCreateBlockIndex(LogBlockIndexController.java:281)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:117)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:172)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:147)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119)
java.lang.IllegalArgumentException: Illegal value for position.Value=21475119072, last value in index=21475119072. Must provide positions in ascending order.
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.addBlock(LogBlockIndex.java:186)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIdx(LogBlockIndexController.java:319)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIndex(LogBlockIndexController.java:304)
	at io.zeebe.logstreams.impl.LogBlockIndexController.tryToCreateBlockIndex(LogBlockIndexController.java:281)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:117)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:172)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:147)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119)
09:37:02.634 [localhost:51015-zb-actors-0] ERROR io.zeebe.logstreams - Can't read from illegal address: 22655968
09:37:02.634 [localhost:51015-zb-actors-0] ERROR io.zeebe.logstreams - Can't read from illegal address: 22655968
09:37:02.635 [localhost:51015-zb-actors-0] ERROR io.zeebe.logstreams - Can't read from illegal address: 22655968
java.lang.IllegalArgumentException: Illegal value for position.Value=21478894096, last value in index=21478894096. Must provide positions in ascending order.
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.addBlock(LogBlockIndex.java:186)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIdx(LogBlockIndexController.java:319)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIndex(LogBlockIndexController.java:304)
	at io.zeebe.logstreams.impl.LogBlockIndexController.tryToCreateBlockIndex(LogBlockIndexController.java:281)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:117)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:172)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:147)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119)
java.lang.IllegalArgumentException: Illegal value for position.Value=25772043808, last value in index=25772043808. Must provide positions in ascending order.
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.addBlock(LogBlockIndex.java:186)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIdx(LogBlockIndexController.java:319)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIndex(LogBlockIndexController.java:304)
	at io.zeebe.logstreams.impl.LogBlockIndexController.tryToCreateBlockIndex(LogBlockIndexController.java:281)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:117)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:172)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:147)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119)
09:37:03.537 [localhost:51015-zb-actors-0] ERROR io.zeebe.logstreams - Can't read from illegal address: 30205888
java.lang.IllegalArgumentException: Illegal value for position.Value=30065193952, last value in index=30065193952. Must provide positions in ascending order.
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.addBlock(LogBlockIndex.java:186)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIdx(LogBlockIndexController.java:319)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIndex(LogBlockIndexController.java:304)
	at io.zeebe.logstreams.impl.LogBlockIndexController.tryToCreateBlockIndex(LogBlockIndexController.java:281)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:117)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:172)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:147)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119)
09:37:04.472 [localhost:51015-zb-actors-0] ERROR io.zeebe.logstreams - Can't read from illegal address: 37756288
09:37:04.472 [localhost:51015-zb-actors-0] ERROR io.zeebe.logstreams - Can't read from illegal address: 37756288
java.lang.IllegalArgumentException: Illegal value for position.Value=30068969328, last value in index=30068969328. Must provide positions in ascending order.
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.addBlock(LogBlockIndex.java:186)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIdx(LogBlockIndexController.java:319)
	at io.zeebe.logstreams.impl.LogBlockIndexController.createBlockIndex(LogBlockIndexController.java:304)
	at io.zeebe.logstreams.impl.LogBlockIndexController.tryToCreateBlockIndex(LogBlockIndexController.java:281)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:117)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:172)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:147)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119)
```

I executed `CreateTaskTest#throughputTest` with the warmup time of 1 sec and test time of 5 seconds

**Comment by menski** [comment] 2018-03-27 12:51
After the refactoring the Exceptions in `addBlock` seems to be fixed. We still see some log messages which indicate a read from an illegal address.

```
14:48:21.626 [main] INFO  io.zeebe.BenchmarkRunner - Executing requests at fixed rate [runtime=30s, rate=30000req/s, maxConcurrentRequests=128]
14:48:24.723 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 7554392
14:48:25.826 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 15103880
14:48:28.177 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 30209672
14:48:28.777 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 33990776
14:48:30.778 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 49095344
14:48:33.429 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 67977056
14:48:34.517 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 75529328
14:48:37.973 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 98190584
14:48:39.138 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 105741736
14:48:40.313 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 113306672
14:48:40.906 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 117088624
14:48:41.488 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 120869216
14:48:42.086 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 124647992
14:48:43.326 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 132199768
14:48:43.941 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 135975272
14:48:51.373 [localhost:51015-zb-actors-0] WARN  io.zeebe.logstreams - Can't read from illegal address: 181280096
```

**Comment by menski** [comment] 2018-03-29 16:52
We might have a regression here, as the following entry repeats in my log of the distribution. Seems it cannot override an existing snapshot.

```
18:50:39.766 [quickstart.1.index] [0.0.0.0:51015-zb-actors-0] WARN  io.zeebe.logstreams - Failed to create snapshot of block index quickstart.1.index
java.lang.RuntimeException: Cannot write snapshot /home/menski/quickstart/zeebe-broker-0.8.0-SNAPSHOT/data/logs/quickstart.1/quickstart.1.index-0.snapshot, file already exists.
        at io.zeebe.logstreams.impl.snapshot.fs.FsSnapshotStorage.createSnapshot(FsSnapshotStorage.java:113) ~[zb-logstreams-0.8.0-20180328.124249-43.jar:0.8.0-SNAPSHOT]
        at io.zeebe.logstreams.impl.snapshot.fs.FsSnapshotStorage.createSnapshot(FsSnapshotStorage.java:28) ~[zb-logstreams-0.8.0-20180328.124249-43.jar:0.8.0-SNAPSHOT]
        at io.zeebe.logstreams.impl.LogBlockIndexAppender.createSnapshot(LogBlockIndexAppender.java:341) ~[zb-logstreams-0.8.0-20180328.124249-43.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:122) [zb-util-0.8.0-20180328.134728-43.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.8.0-20180328.134728-43.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:205) [zb-util-0.8.0-20180328.134728-43.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.8.0-20180328.134728-43.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.8.0-20180328.134728-43.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.8.0-20180328.134728-43.jar:0.8.0-SNAPSHOT]
```

**Comment by menski** [comment] 2018-04-03 09:36
If I run the `LogBlockIndexAppenderTest` locally the test `shouldWriteSnapshotWithPositionOfLastBlock` sometimes fail with following stack trace:

```
java.lang.AssertionError: Fail to read snapshot
	at io.zeebe.logstreams.log.LogBlockIndexAppenderTest.getLatestSnapshot(LogBlockIndexAppenderTest.java:240)
	at io.zeebe.logstreams.log.LogBlockIndexAppenderTest.lambda$shouldWriteSnapshotWithPositionOfLastBlock$7(LogBlockIndexAppenderTest.java:156)
	at io.zeebe.test.util.TestUtil.lambda$waitUntil$2(TestUtil.java:45)
	at io.zeebe.test.util.TestUtil$Invocation.lambda$until$4(TestUtil.java:94)
	at io.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:176)
	at io.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:144)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:94)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:74)
	at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:45)
	at io.zeebe.logstreams.log.LogBlockIndexAppenderTest.shouldWriteSnapshotWithPositionOfLastBlock(LogBlockIndexAppenderTest.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: Read invalid checksum file, no content
	at io.zeebe.logstreams.impl.snapshot.fs.FsReadableSnapshot.readChecksumContent(FsReadableSnapshot.java:104)
	at io.zeebe.logstreams.impl.snapshot.fs.FsReadableSnapshot.tryInit(FsReadableSnapshot.java:63)
	at io.zeebe.logstreams.impl.snapshot.fs.FsReadableSnapshot.<init>(FsReadableSnapshot.java:54)
	at io.zeebe.logstreams.impl.snapshot.fs.FsSnapshotStorage.getLastSnapshot(FsSnapshotStorage.java:59)
	at io.zeebe.logstreams.impl.snapshot.fs.FsSnapshotStorage.getLastSnapshot(FsSnapshotStorage.java:28)
	at io.zeebe.logstreams.log.LogBlockIndexAppenderTest.getLatestSnapshot(LogBlockIndexAppenderTest.java:236)
	... 36 more
```

**Comment by meyerdan** [comment] 2018-04-03 09:48
Fixed on my branch: https://github.com/zeebe-io/zeebe/issues/783

**Closed** 2018-05-07 07:52 UTC
Labels: bug, logstreams, needs review
