### ISSUE TITLE
Decouple Timer triggering from general stream processing

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4931] opened 2020-07-09 13:59 UTC
**Description**

Found at the Chaos day https://github.com/zeebe-io/zeebe-chaos/edit/master/chaos-days/2020-07-09/summary.md

We currently have the issue that we trigger timers in the same actor as the stream processing runs. This means we interrupt the normal processing to write new commands. This should be decoupled to streamline the processing. I can imagine that we can trigger the timers and also other things like timeout jobs, in a separate actor, which then writes to the dispatcher.

This would mean the stream processor can just continue with consuming new records. I think this will make the throughput more stable in case we have more timers. This cam also be done for jobs or messages etc.

**Comment by npepinpe** [comment] 2021-02-02 18:09
Duplicate of #4783

**Closed** 2021-02-02 18:09 UTC
Labels: Impact: Performance, Priority: Mid, Scope: broker, Type: Maintenance

**Comment by Zelldon** [comment] 2021-02-02 18:40
Wouldn't say this is a duplicate

**Comment by npepinpe** [comment] 2021-02-02 19:33
Fair enough, let's talk about it in the morning

**Comment by npepinpe** [comment] 2021-02-04 12:56
Alright, so from my pov they're duplicate as they describe the same issue but propose a different approach: triggering timers can potentially slow down stream processing. Maybe you can elaborate what the other issue isn't covering, or how it's different?
