### ISSUE TITLE
StreamProcessor failed in phase STARTED and never recovered

### ISSUE THREAD

**Issue by sergeylebed** [zeebe-io/zeebe#6140] opened 2021-01-20 14:34 UTC
**Describe the bug**
A broker starts with one partition in unhealthy status and there're no attempts to recover from this state. Restarting cluster or node does not help. The system performance is degraded there're a lot of timeout errors in client application.

**To Reproduce**
Long running production cluster with no big load.

**Expected behavior**
The broker starts with all partitions healthy.

**Some events in the log**
```
{"severity":"ERROR","logging.googleapis.com/sourceLocation":{"function":"onFailure","file":"StreamProcessor.java","line":288},"message":"Actor Broker-1-StreamProcessor-3 failed in phase STARTED.","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"threadPriority":5,"loggerName":"io.zeebe.logstreams","threadName":"Broker-1-zb-actors-0","actor-name":"Broker-1-StreamProcessor-3"},"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","exception":"java.lang.IllegalStateException: Expected that position '27516421' of current event is higher then position '27516422' of last event, but was not. Inconsistent log detected!\n\tat io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.scanLog(ReProcessingStateMachine.java:180) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]\n\tat io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.startRecover(ReProcessingStateMachine.java:150) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]\n\tat io.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorStarted(StreamProcessor.java:119) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]\n","timestampSeconds":1611140178,"timestampNanos":272692000,"logger":"io.zeebe.logstreams","thread":"Broker-1-zb-actors-0"} 
```

```
{"severity":"ERROR","logging.googleapis.com/sourceLocation":{"function":"onComponentFailure","file":"CriticalComponentsHealthMonitor.java","line":136},"message":"Partition-3 failed, marking it as unhealthy","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":33,"threadPriority":5,"loggerName":"io.zeebe.broker.system","threadName":"Broker-1-zb-actors-1","reportLocation":{"functionName":"onComponentFailure","filePath":"CriticalComponentsHealthMonitor.java","lineNumber":136},"actor-name":"Broker-1-HealthCheckService"},"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","timestampSeconds":1611140267,"timestampNanos":737490000,"logger":"io.zeebe.broker.system","thread":"Broker-1-zb-actors-1"} 
```
The next error repeated every 15 minutes

```
{"severity":"ERROR","logging.googleapis.com/sourceLocation":{"function":"lambda$prepareTakingSnapshot$0","file":"AsyncSnapshotDirector.java","line":129},"message":"Unexpected error in resolving last processed position.","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":35,"threadPriority":5,"loggerName":"io.zeebe.logstreams.snapshot","threadName":"Broker-1-zb-fs-workers-1","actor-name":"Broker-1-SnapshotDirector-3"},"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","exception":"java.lang.RuntimeException: Actor is closed\n\tat io.zeebe.util.sched.ActorJob.failFuture(ActorJob.java:166) ~[zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorTask.submit(ActorTask.java:102) ~[zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorControl.call(ActorControl.java:121) ~[zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.engine.processing.streamprocessor.StreamProcessor.getLastProcessedPositionAsync(StreamProcessor.java:311) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]\n\tat io.zeebe.broker.system.partitions.impl.AsyncSnapshotDirector.prepareTakingSnapshot(AsyncSnapshotDirector.java:114) ~[zeebe-broker-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]\n\tat io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]\n","timestampSeconds":161114437 
8,"timestampNanos":334339000,"logger":"io.zeebe.logstreams.snapshot","thread":"Broker-1-zb-fs-workers-1"} 
```

<details><summary>Full Log file for the node with the failed partition</summary>
 <p>
<a href="https://github.com/zeebe-io/zeebe/files/5843071/container.47.log">container.log</a></p>
</details>

**Environment:**
 - OS: Linux, Kubernetes
 - Zeebe Version: 0.26.0
 - Configuration: 
 3 nodes, 3 partitions, 3 replication factor

```
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"logBrokerStart","file":"Broker.java","line":169},"message":"Starting broker 0 with configuration {\n  \"network\" : {\n    \"host\" : \"0.0.0.0\",\n    \"portOffset\" : 0,\n    \"maxMessageSize\" : \"0MB\",\n    \"advertisedHost\" : \"horizons-all-zeebe-0.horizons-all-zeebe.horizons.svc.cluster.local\",\n    \"commandApi\" : {\n      \"host\" : \"0.0.0.0\",\n      \"port\" : 26501,\n      \"advertisedHost\" : \"horizons-all-zeebe-0.horizons-all-zeebe.horizons.svc.cluster.local\",\n      \"advertisedPort\" : 26501,\n      \"address\" : \"0.0.0.0:26501\",\n      \"advertisedAddress\" : \"horizons-all-zeebe-0.horizons-all-zeebe.horizons.svc.cluster.local:26501\"\n    },\n    \"internalApi\" : {\n      \"host\" : \"0.0.0.0\",\n      \"port\" : 26502,\n      \"advertisedHost\" : \"horizons-all-zeebe-0.horizons-all-zeebe.horizons.svc.cluster.local\",\n      \"advertisedPort\" : 26502,\n      \"address\" : \"0.0.0.0:26502\",\n      \"advertisedAddress\" : \"horizons-all-zeebe-0.horizons-all-zeebe.horizons.svc.cluster.local:26502\"\n    },\n    \"monitoringApi\" : {\n      \"host\" : \"0.0.0.0\",\n      \"port\" : 9600,\n      \"advertisedHost\" : \"horizons-all-zeebe-0.horizons-all-zeebe.horizons.svc.cluster.local\",\n      \"advertisedPort\" : 9600,\n      \"address\" : \"0.0.0.0:9600\",\n      \"advertisedAddress\" : \"horizons-all-zeebe-0.horizons-all-zeebe.horizons.svc.cluster.local:9600\"\n    },\n    \"maxMessageSizeInBytes\" : 262144\n  },\n  \"cluster\" : {\n    \"initialContactPoints\" : [ \"horizons-all-zeebe-0.horizons-all-zeebe.horizons.svc.cluster.local:26502\", \"horizons-all-zeebe-1.horizons-all-zeebe.horizons.svc.cluster.local:26502\", \"horizons-all-zeebe-2.horizons-all-zeebe.horizons.svc.cluster.local:26502\" ],\n    \"partitionIds\" : [ 1, 2, 3 ],\n    \"nodeId\" : 0,\n    \"partitionsCount\" : 3,\n    \"replicationFactor\" : 3,\n    \"clusterSize\" : 3,\n    \"clusterName\" : \"horizons-all-zeebe\", 
\n    \"membership\" : {\n      \"broadcastUpdates\" : false,\n      \"broadcastDisputes\" : true,\n      \"notifySuspect\" : false,\n      \"gossipInterval\" : \"PT0.25S\",\n      \"gossipFanout\" : 2,\n      \"probeInterval\" : \"PT1S\",\n      \"probeTimeout\" : \"PT0.1S\",\n      \"suspectProbes\" : 3,\n      \"failureTimeout\" : \"PT10S\",\n      \"syncInterval\" : \"PT10S\"\n    }\n  },\n  \"threads\" : {\n    \"cpuThreadCount\" : 2,\n    \"ioThreadCount\" : 2\n  },\n  \"data\" : {\n    \"directories\" : null,\n    \"directory\" : \"/usr/local/zeebe/data\",\n    \"logSegmentSize\" : \"512MB\",\n    \"snapshotPeriod\" : \"PT15M\",\n    \"logIndexDensity\" : 100,\n    \"diskUsageMonitoringEnabled\" : true,\n    \"diskUsageReplicationWatermark\" : 0.99,\n    \"diskUsageCommandWatermark\" : 0.97,\n    \"diskUsageMonitoringInterval\" : \"PT1S\",\n    \"rocksdb\" : {\n      \"columnFamilyOptions\" : { }\n    },\n    \"freeDiskSpaceReplicationWatermark\" : 525718979,\n    \"logSegmentSizeInBytes\" : 536870912,\n    \"atomixStorageLevel\" : \"MAPPED\",\n    \"freeDiskSpaceCommandWatermark\" : 1577156936\n  },\n  \"exporters\" : { },\n  \"gateway\" : {\n    \"network\" : {\n      \"host\" : \"0.0.0.0\",\n      \"port\" : 26500,\n      \"minKeepAliveInterval\" : \"PT30S\"\n    },\n    \"cluster\" : {\n      \"contactPoint\" : \"0.0.0.0:26502\",\n      \"requestTimeout\" : \"PT15S\",\n      \"clusterName\" : \"zeebe-cluster\",\n      \"memberId\" : \"gateway\",\n      \"host\" : \"0.0.0.0\",\n      \"port\" : 26502,\n      \"membership\" : {\n        \"broadcastUpdates\" : false,\n        \"broadcastDisputes\" : true,\n        \"notifySuspect\" : false,\n        \"gossipInterval\" : \"PT0.25S\",\n        \"gossipFanout\" : 2,\n        \"probeInterval\" : \"PT1S\",\n        \"probeTimeout\" : \"PT0.1S\",\n        \"suspectProbes\" : 3,\n        \"failureTimeout\" : \"PT10S\",\n        \"syncInterval\" : \"PT10S\"\n      }\n    },\n    \"threads\" : {\n      \"managementThreads\" : 3\n    },\n    \"monitoring\" : {\n 
\"enabled\" : false,\n      \"host\" : \"0.0.0.0\",\n      \"port\" : 9600\n    },\n    \"security\" : {\n      \"enabled\" : false,\n      \"certificateChainPath\" : null,\n      \"privateKeyPath\" : null\n    },\n    \"longPolling\" : {\n      \"enabled\" : true\n    },\n    \"initialized\" : true,\n    \"enable\" : false\n  },\n  \"backpressure\" : {\n    \"enabled\" : false,\n    \"algorithm\" : \"VEGAS\",\n    \"aimd\" : {\n      \"requestTimeout\" : \"PT1S\",\n      \"initialLimit\" : 100,\n      \"minLimit\" : 1,\n      \"maxLimit\" : 1000,\n      \"backoffRatio\" : 0.9\n    },\n    \"fixed\" : {\n      \"limit\" : 20\n    },\n    \"vegas\" : {\n      \"alpha\" : 3,\n      \"beta\" : 6,\n      \"initialLimit\" : 20\n    },\n    \"gradient\" : {\n      \"minLimit\" : 10,\n      \"initialLimit\" : 20,\n      \"rttTolerance\" : 2.0\n    },\n    \"gradient2\" : {\n      \"minLimit\" : 10,\n      \"initialLimit\" : 20,\n      \"rttTolerance\" : 2.0,\n      \"longWindow\" : 600\n    }\n  },\n  \"experimental\" : {\n    \"maxAppendsPerFollower\" : 2,\n    \"maxAppendBatchSize\" : \"0MB\",\n    \"disableExplicitRaftFlush\" : false,\n    \"detectReprocessingInconsistency\" : false,\n    \"maxAppendBatchSizeInBytes\" : 32768\n  },\n  \"stepTimeout\" : \"PT5M\",\n  \"executionMetricsExporterEnabled\" : false\n}","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":1,"threadPriority":5,"loggerName":"io.zeebe.broker.system","threadName":"main"},"timestampSeconds":1611132260,"timestampNanos":173967000,"logger":"io.zeebe.broker.system","thread":"main"} 
```

**Comment by deepthidevaki** [comment] 2021-01-22 08:40
Hi @sergeylebed 

I discussed with the team. Currently we don't find a way to recover from it. The error reports that it detects an incorrect ordering in the logstream. In an older version we had fixed an issue that causes it, but also ensured that this incorrect ordering would not happen by proactively checking it before anything is written to the logstream. So it is strange that this error occurred.
I guess there are two possible scenarios:
1. The logstream is consistent. But there is a bug in the inconsistency detection.
2. The logstream is actually corrupted.

To find the actual cause of it, it would be great if we can inspect the log. Would it be possible to share the data of partition 3 from Broker 0 (data/raft-partition/partitions/3/*)?
Also do you have any logs from the time before this error started appearing? This would help us to find what caused the incorrect ordering in the logstream.
Do you monitor zeebe metrics using prometheus/grafana? If yes, do you still have data from the time when this error first occurred?

**Comment by sergeylebed** [comment] 2021-01-26 18:37
Hi @deepthidevaki,
sorry for the late reply. Unfortunately, we had to restart the cluster from scratch to return it to operational state quickly and thus all data is gone. Bad luck with the logs as well. We started to monitor metrics with grafana but it was after resetting and I'm not sure that we have all metrics valid. It needs validation that it was set up correctly, as some metrics are empty. So, no help in this way too. Sorry that I cannot help with details here. The priority was to quickly bring the cluster back .
We have some logs transferred to Kibana but some were lost due to issues we have atm. I can query them if you give me some hints what to query and note that I don't know the time when the problem appeared. Not much but it is only thing I can do now.

**Comment by deepthidevaki** [comment] 2021-01-28 15:15
Thanks @sergeylebed for the reply. With out data or logs it would be difficult for us to investigate. If you observe this again, I would request to you backup as much information you can collect. That would really help us. I don't know if we can reproduce this issue because we are running several clusters with the latest version and have never encountered this.

> We started to monitor metrics with grafana but it was after resetting and I'm not sure that we have all metrics valid. It needs validation that it was set up correctly, as some metrics are empty. 

Which metrics are empty? Some metrics may be only available in later version. So if you are using latest dashboard with previous zeebe version, some metrics will be missing.

**Comment by sergeylebed** [comment] 2021-02-01 13:52
It is hard to get data from prods especially when there's a race for brining it back online. We are improving at logging, maybe, we will be more lucky next time.

About metrics, we use the latest dashboard designed for 0.26 it seems there're some problems on our side, out Ops guys are looking into it.

**Comment by deepthidevaki** [comment] 2021-02-12 07:55
Similar #6316

**Comment by deepthidevaki** [comment] 2021-02-12 07:58
Closing this issue as we will be investigating this as part of #6316

**Closed by deepthidevaki** 2021-02-12 07:58 UTC
Labels: Status: Needs Information, Type: Bug
