### ISSUE TITLE
Zeebe distribution does not contain zbctl

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3458] opened 2019-12-02 08:15 UTC
**Describe the bug**

I think after merging the go client and zbctl we broke something. It seems that on build the distribution we do not include zbctl anymore. I observed this on running benchmarks and were not able to run zbctl, because it was not shipped with the distro.

**To Reproduce**

Running 
```
clients/go/cmd/zbctl/build.sh && mvn clean install -T1C -DskipTests -pl dist -am
```
and zbctl will not be added to the distro.

**Expected behavior**
Zbctl is in the distro included.

**Comment by Zelldon** [comment] 2019-12-02 08:18
Might be related to that:


```
(chaostk) [zell zeebe/ ns:default]$ clients/go/cmd/zbctl/build.sh && mvn clean install -T1C -DskipTests -pl dist -am
+ OS=(linux windows darwin)
+ BINARY=(zbctl zbctl.exe zbctl.darwin)
++ dirname clients/go/cmd/zbctl/build.sh
+ SRC_DIR=clients/go/cmd/zbctl
+ DIST_DIR=clients/go/cmd/zbctl/dist
+ VERSION=development
++ git rev-parse HEAD
+ COMMIT=0c02de4f90da7e15af1465c844b5e7a68db591b7
+ mkdir -p clients/go/cmd/zbctl/dist
+ rm -rf 'clients/go/cmd/zbctl/dist/*'
+ for i in "${!OS[@]}"
+ for i in "${!OS[@]}"
+ for i in "${!OS[@]}"
+ CGO_ENABLED=0
+ GOOS=linux
+ GOARCH=amd64
+ go build -mod=vendor -a -tags netgo -ldflags '-w -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Version=development -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Commit=0c02de4f90da7e15af1465c844b5e7a68db591b7' -o clients/go/cmd/zbctl/dist/zbctl clients/go/cmd/zbctl/main.go
+ CGO_ENABLED=0
+ GOOS=windows
+ GOARCH=amd64
+ go build -mod=vendor -a -tags netgo -ldflags '-w -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Version=development -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Commit=0c02de4f90da7e15af1465c844b5e7a68db591b7' -o clients/go/cmd/zbctl/dist/zbctl.exe clients/go/cmd/zbctl/main.go
+ wait
+ CGO_ENABLED=0
+ GOOS=darwin
+ GOARCH=amd64
+ go build -mod=vendor -a -tags netgo -ldflags '-w -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Version=development -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Commit=0c02de4f90da7e15af1465c844b5e7a68db591b7' -o clients/go/cmd/zbctl/dist/zbctl.darwin clients/go/cmd/zbctl/main.go
build flag -mod=vendor only valid when using modules
build flag -mod=vendor only valid when using modules
build flag -mod=vendor only valid when using modules

```

**Comment by MiguelPires** [comment] 2019-12-02 09:28
I don't think this is a bug since if you `cd` into `clients/go` this doesn't happen. What I think is happening is: `go build` doesn't find a go.mod file in zeebe-io-zeebe and since you (probably) have `GO111MODULE=auto` it defaults to not using go modules. At that point, it complains that the flag `-mod=vendor` only makes sense in modules-aware mode. The issue isn't solved by setting `GO111MODULE` to `on` because then it looks for a go.mod file in the current or parent directory (https://github.com/golang/go/wiki/Modules#why-does-installing-a-tool-via-go-get-fail-with-error-cannot-find-main-module third paragraph). So the solution is to just build the go client from the `clients/go` dir.
I'm closing this issue but feel free to re-open if you disagree

**Comment by Zelldon** [comment] 2019-12-02 09:44
Then at least I would expect this is build by jenkins and included in this distribution.

But If I do 
```
[zell zeebe/ ns:default]$ docker run camunda/zeebe:SNAPSHOT
```

**AND**

```
[zell ~/ ns:default]$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS               NAMES
b443aad90a0d        camunda/zeebe:SNAPSHOT   "tini -- /usr/local/…"   11 seconds ago      Up 8 seconds        26500-26502/tcp     jovial_greider
[zell ~/ ns:default]$ docker exec -it jovial_greider bash
root@b443aad90a0d:/usr/local/zeebe# ll
bash: ll: command not found
root@b443aad90a0d:/usr/local/zeebe# ls -la
total 64
drwxr-sr-x 1 root root   4096 Dec  2 09:42 .
drwxrwsr-x 1 root staff  4096 Nov 28 16:54 ..
-rwxr-xr-x 1 root root  11357 Nov 28 16:34 APACHE-2.0.txt
-rwxr-xr-x 1 root root    472 Nov 28 16:34 Clarification-on-gRPC-code-generation.txt
-rwxr-xr-x 1 root root     50 Nov 28 16:34 NOTICE.txt
-rwxr-xr-x 1 root root   3313 Nov 28 16:34 ZEEBE-COMMUNITY-LICENSE-1.0.txt
drwxr-xr-x 2 root root   4096 Nov 28 16:54 bin
drwxr-xr-x 2 root root   4096 Nov 28 16:54 conf
drwxr-sr-x 5 root root   4096 Dec  2 09:42 data
drwxr-xr-x 2 root root  12288 Nov 28 16:54 lib
drwxr-sr-x 2 root root   4096 Dec  2 09:42 logs
root@b443aad90a0d:/usr/local/zeebe# zbctl
bash: zbctl: command not found
root@b443aad90a0d:/usr/local/zeebe# ls -la bin/
total 24
drwxr-xr-x 2 root root 4096 Nov 28 16:54 .
drwxr-sr-x 1 root root 4096 Dec  2 09:42 ..
-rwxr-xr-x 1 root root 3757 Nov 28 16:50 broker
-rw-r--r-- 1 root root 3245 Nov 28 16:50 broker.bat
-rwxr-xr-x 1 root root 3762 Nov 28 16:50 gateway
-rw-r--r-- 1 root root 3250 Nov 28 16:50 gateway.bat
root@b443aad90a0d:/usr/local/zeebe# 
```

There is no zbctl

**Comment by MiguelPires** [comment] 2019-12-02 10:01
Did you run `build.sh`? If not then I guess that's why. I can't try to reproduce that bug when I try to. I updated the release scripts to get zbctl from its new location in the zbctl-go merge PR so I'd assume that when Jenkins will work since it will run the Go build scripts and it would fail if it couldn't find zbctl. I don't know if I can ssh into Jenkins and manually verify that this is true

**Comment by Zelldon** [comment] 2019-12-02 10:21
The same output we have on jenkins 
(develop branch https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/develop/635/pipeline/49 )

```
+ .ci/scripts/distribution/build-go.sh

+ set -o pipefail

+ export CGO_ENABLED=0

+ CGO_ENABLED=0

+ ORG_DIR=/go/src/github.com/zeebe-io

+ mkdir -p /go/src/github.com/zeebe-io

+ ln -s /home/jenkins/agent/workspace/zeebe-io_zeebe_develop /go/src/github.com/zeebe-io/zeebe

+ go get -u github.com/jstemmer/go-junit-report

+ cd /go/src/github.com/zeebe-io/zeebe/clients/go/cmd/zbctl

+ ./build.sh

+ OS=(linux windows darwin)

+ BINARY=(zbctl zbctl.exe zbctl.darwin)

++ dirname ./build.sh

+ SRC_DIR=.

+ DIST_DIR=./dist

+ VERSION=development

++ git rev-parse HEAD

+ COMMIT=ea58ea4584a585f5e612d1fd5faa732ef4187af8

+ mkdir -p ./dist

+ rm -rf './dist/*'

+ for i in "${!OS[@]}"

+ for i in "${!OS[@]}"

+ CGO_ENABLED=0

+ for i in "${!OS[@]}"

+ GOOS=linux

+ GOARCH=amd64

+ go build -mod=vendor -a -tags netgo -ldflags '-w -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Version=development -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Commit=ea58ea4584a585f5e612d1fd5faa732ef4187af8' -o ./dist/zbctl ./main.go

+ CGO_ENABLED=0

+ wait

+ GOOS=windows

+ GOARCH=amd64

+ go build -mod=vendor -a -tags netgo -ldflags '-w -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Version=development -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Commit=ea58ea4584a585f5e612d1fd5faa732ef4187af8' -o ./dist/zbctl.exe ./main.go

+ CGO_ENABLED=0

+ GOOS=darwin

+ GOARCH=amd64

+ go build -mod=vendor -a -tags netgo -ldflags '-w -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Version=development -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/cmd.Commit=ea58ea4584a585f5e612d1fd5faa732ef4187af8' -o ./dist/zbctl.darwin ./main.go

build flag -mod=vendor only valid when using modules

build flag -mod=vendor only valid when using modules

build flag -mod=vendor only valid when using modules
```

**Comment by MiguelPires** [comment] 2019-12-02 10:36
Ah thanks for pointing that out, I'll investigate

**Closed** 2019-12-02 14:16 UTC
Labels: Status: Needs Review, Type: Bug
