### ISSUE TITLE
Cannot build develop branch

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#2961] opened 2019-08-11 13:12 UTC
**Describe the bug**
It looks like Java 11 is needed to build Zeebe now? With AdoptOpenJDK 11  and Maven 3.6.1, I get an error building the Scala portion:

```
➜ mvn --version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T05:00:29+10:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 11.0.4, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_AU, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"

➜ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.1.1:compile (scala-compile-first) on project zeebe-msgpack-json-el: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.1.1:compile failed: A required class was missing while executing net.alchim31.maven:scala-maven-plugin:4.1.1:compile: Could not initialize class sbt.internal.io.Milli$
-----------------------------------------------------
realm =    plugin>net.alchim31.maven:scala-maven-plugin:4.1.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
```
I deleted the maven cache, but get the same error.

**Comment by Zelldon** [comment] 2019-08-11 13:40
Hey Josh thanks for reporting.
Do you tried the normal OpenJDK?

Greets
Chris

**Comment by Zelldon** [comment] 2019-08-12 08:14
I tried it with AdoptOpenJDK and seems to work :man_shrugging: 

```
[zell zeebe]$ mvn -v
Apache Maven 3.6.1 (NON-CANONICAL_2019-07-24T20:49:02Z_root; 2019-07-24T22:49:02+02:00)
Maven home: /opt/maven
Java version: 11.0.4, vendor: AdoptOpenJDK, runtime: /home/zell/test/jdk-11.0.4+11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.2.7-arch1-1-arch", arch: "amd64", family: "unix"
```

**Comment by salaboy** [comment] 2019-09-03 14:07
For some reason with AdoptOpenJDK 12 doesn't work.

**Comment by Zelldon** [comment] 2019-09-05 05:21
Was able to build the project with AdoptOpenJDK 12 as well.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:28 min (Wall Clock)
[INFO] Finished at: 2019-09-05T07:20:07+02:00
[INFO] ------------------------------------------------------------------------
```

```
[zell zeebe]$ mvn -v
Apache Maven 3.6.1 (NON-CANONICAL_2019-07-24T20:49:02Z_root; 2019-07-24T22:49:02+02:00)
Maven home: /opt/maven
Java version: 12.0.2, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/java-12-adoptopenjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.2.11-arch1-1-arch", arch: "amd64", family: "unix"
```

Is this an Mac OS issue?

**Comment by salaboy** [comment] 2019-09-05 05:41
Interesting.. it might be something that Jacoco is doing that only affects Macs ?

**Comment by Zelldon** [comment] 2019-09-27 11:57
Since we can't reproduce it I will close this for now. Feel free to reopen it

**Closed by Zelldon** 2019-09-27 11:57 UTC
Labels: Type: Bug
