### ISSUE TITLE
Improved input/output variable mappings 

### ISSUE THREAD

**Issue by sebjonas** [zeebe-io/zeebe#3102] opened 2019-09-23 20:02 UTC
I'm posting this to promote a way to work with the payload data in a more flexible way than just using dot notation. I'm thinking of something similar to JSONPath to navigate the data and functions for lists, strings, numbers, aggregates and dates to operate on the selection. This would help to ensure that the process models do not need to contain supporting tasks that make the models difficult to read and explain to the business. It also makes it easier to manage a solution because today a worker is required to achieve something as simple as a count (order.items) => 2:

source json: order: {"items": ["item-1", "item-2"]}

**Comment by saig0** [comment] 2019-09-25 07:11
Thank you for raising this up. In order to find a suitable solution, please list everything you need for the input/output variable mapping. 
Would you need these functions only for variable mappings or also something else like conditions?

**Comment by sebjonas** [comment] 2019-09-25 08:11
I won't be able to point at any preferred solution, but to something similar that we've been used to in the pre-Json era.

I'd like to be able to use an equivalent to XPath and XPath functions as it's used in a XSLT context - i.e. a way to navigate and select a set of nodes and then pass it into a function.

Here's a sample scenario for making use of such a solution:

A workflow is initiated with a JSON payload of order items. An automated decision will decide on what path to take in the flow. The decision parameters are computed values from the payload (such as the number of items and calculated field from total amount). What I would like to have is the possibility to write the mapping of output parameters to the decision task like this:

count = count($payload.orders.order)
total = sum($payload.orders.order.amount)

**Comment by andre-neouse** [comment] 2019-09-25 21:20
Rather than invent a new language or limit it to path style selections, what about jq? I use gojq (https://github.com/itchyny/gojq) as a workflow command before and after most API calls to transform the data. It does make the workflow much larger than it should be which has lead to hitting the 64k limit, which has lead to running 0.21 alphas...

Given that most modern APIs use JSON I think this is highly desirable.

We wrote a http command which uses golangs templates for inserting variables into url, headers, and body. If the content is too complex then a jq preprocess is needed.

https://github.com/eiiches/jackson-jq looks like a java alternative. Having this functionality would help make our workflows much simpler and jq has substantial capabilities.

Using this in input, output, decisions and headers would cover our current use cases.
E.g. from above
```
$payload.orders | length
[$payload.orders[].order.amount] | add
```

For for seeing how many unpaid orders there are as a condition.
```
[[$payload.orders[].order.paid] | select(.|not)] | length
```

**Comment by saig0** [comment] 2019-09-27 11:00
I guess there are different requirements and different options for the best approach. Maybe, we can make it extensible so that you can choose your favorite expression/script language. For example, based on the JSR 223 (Java scripting languages).

**Comment by ceefour** [comment] 2020-04-18 20:42
I agree with the general requirement here.

For example, I had a "simple" use case of wanting to set an input variable as _string constant_ (in the BPMN file) when calling a Service Task, which is very easy in Camunda but currently impossible in Zeebe.

**Comment by ceefour** [comment] 2020-04-18 20:46
Perhaps this is a duplicate of #3808? Which recently implemented by #4079.

**Comment by saig0** [comment] 2020-04-20 04:47
With version 0.23.0, variable mappings use [FEEL expressions](https://stage.docs.zeebe.io/reference/expressions.html#the-expression-language) in the `source` expression. This makes it possible to define literals (i.e. constants) and call functions like `count()` and `sum()` :tada:

**Closed by saig0** 2020-04-20 04:47 UTC
Labels: Type: Enhancement

**Comment by ceefour** [comment] 2020-04-20 05:26
@saig0 Please make 0.23 (binaries) available here https://github.com/zeebe-io/zeebe/releases . Thank you in advance :+1:

**Comment by saig0** [comment] 2020-04-20 05:32
We will do so (very soon) ;-)
We just want to combine all related releases (Zeebe, Operate, Modeler) in the release announcement :balloon:

**Comment by ceefour** [comment] 2020-04-20 05:40
@saig0 In time for CamundaCon 2020? :+1: Jiayou 加油!

**Comment by ceefour** [comment] 2020-04-20 06:50
@siag0 So hoping Zeebe will get several mentions in CamundaCon Live 2020.. only 3 days more :)
There were so many Camunda last year and not enough Zeebe.... Please more Zeebe ^_^
