### ISSUE TITLE
Create workflow instance shows unexpected latency pattern 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2778] opened 2019-07-02 12:43 UTC
Running a small benchmark with `ghz` shows an unexpected number of delayed responses around 5s.

```
$ ghz -insecure --proto ./gateway-protocol/src/main/proto/gateway.proto --call gateway_protocol.Gateway.CreateWorkflowInstance -d '{"workflowKey": 2251799813685249}' -n 2000 localhost:26500

Summary:
  Count:        2000
  Total:        73683.84 ms
  Slowest:      5075.27 ms
  Fastest:      25.08 ms
  Average:      1742.50 ms
  Requests/sec: 27.14

Response time histogram:
  25.077 [1]    |
  530.096 [1339]|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1035.115 [0]  |
  1540.135 [0]  |
  2045.154 [0]  |
  2550.173 [0]  |
  3055.192 [0]  |
  3560.211 [0]  |
  4065.230 [0]  |
  4570.249 [0]  |
  5075.268 [660]|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎

Latency distribution:
  10% in 60.69 ms
  25% in 116.77 ms
  50% in 157.56 ms
  75% in 5019.84 ms
  90% in 5039.01 ms
  95% in 5048.32 ms
  99% in 5061.54 ms
Status code distribution:
  [OK]  2000 responses

```

**Comment by Zelldon** [comment] 2019-07-05 08:56
For documentation purpose I will write some things down I tested so far.

 * Tested standalone gateway without brokers, with immediately response
 * Tested standalone gateway without broker, with random delay (from 10 to 100 ms) before sending response
 * Tested standalone broker with immediately response in Command API handler
 * Tested standalone broker with random delay (from 10 to 100 ms) before sending response
 * Tested standalone broker with writing to dispatcher before sending response before sending response
 
 With all these different scenarios I saw **not** such a high latency
 After enabling processing again I saw this pattern again. First thought was that processing is the problem. I added new processing metrics to collect the processing latency (time between event is written to dispatcher and processed).

```
# HELP zeebe_stream_processor_latency Latency of command processing in seconds
# TYPE zeebe_stream_processor_latency histogram
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="0.005",} 25.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="0.01",} 52.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="0.025",} 173.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="0.05",} 445.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="0.075",} 796.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="0.1",} 2346.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="0.25",} 81525.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="0.5",} 93496.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="0.75",} 93701.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="1.0",} 93702.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="2.5",} 93702.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="5.0",} 93702.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="7.5",} 100001.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="10.0",} 100001.0
zeebe_stream_processor_latency_bucket{recordType="EVENT",partition="1",le="+Inf",} 100001.0
zeebe_stream_processor_latency_count{recordType="EVENT",partition="1",} 100001.0
zeebe_stream_processor_latency_sum{recordType="EVENT",partition="1",} 50544.728986107744
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="0.005",} 2.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="0.01",} 13.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="0.025",} 93.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="0.05",} 188.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="0.075",} 261.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="0.1",} 521.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="0.25",} 16316.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="0.5",} 18683.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="0.75",} 18733.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="1.0",} 18733.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="2.5",} 18733.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="5.0",} 18733.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="7.5",} 20002.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="10.0",} 20002.0
zeebe_stream_processor_latency_bucket{recordType="COMMAND",partition="1",le="+Inf",} 20002.0
zeebe_stream_processor_latency_count{recordType="COMMAND",partition="1",} 20002.0
zeebe_stream_processor_latency_sum{recordType="COMMAND",partition="1",} 10141.742005752865
```

As you can see in the latency, we have this 5 sec latency here as well. 
Since between dispatcher and processing there are still different steps I added more metrics.
The second metrics was the time between dispatcher and logstorage append, which appends to atomix.

```
# HELP zeebe_logstream_append_latency Latency between writing to dispatcher and appending to atomix in seconds
# TYPE zeebe_logstream_append_latency histogram
zeebe_logstream_append_latency_bucket{partition="1",le="0.005",} 126892.0
zeebe_logstream_append_latency_bucket{partition="1",le="0.01",} 129269.0
zeebe_logstream_append_latency_bucket{partition="1",le="0.025",} 129977.0
zeebe_logstream_append_latency_bucket{partition="1",le="0.05",} 130002.0
zeebe_logstream_append_latency_bucket{partition="1",le="0.075",} 130002.0
zeebe_logstream_append_latency_bucket{partition="1",le="0.1",} 130002.0
zeebe_logstream_append_latency_bucket{partition="1",le="0.25",} 130003.0
zeebe_logstream_append_latency_bucket{partition="1",le="0.5",} 130003.0
zeebe_logstream_append_latency_bucket{partition="1",le="0.75",} 130003.0
zeebe_logstream_append_latency_bucket{partition="1",le="1.0",} 130004.0
zeebe_logstream_append_latency_bucket{partition="1",le="2.5",} 130004.0
zeebe_logstream_append_latency_bucket{partition="1",le="5.0",} 130004.0
zeebe_logstream_append_latency_bucket{partition="1",le="7.5",} 130004.0
zeebe_logstream_append_latency_bucket{partition="1",le="10.0",} 130004.0
zeebe_logstream_append_latency_bucket{partition="1",le="+Inf",} 130004.0
zeebe_logstream_append_latency_count{partition="1",} 130004.0
zeebe_logstream_append_latency_sum{partition="1",} 35.06100126041565
```

Here we see no problem, such that I added a third metric.
The third metrics shows us the time between writing to the dispatcher and receiving in our distributed log primitive.

```
# HELP zeebe_atomix_receive_latency Latency between writing to dispatcher and receiving block in atomix in seconds
# TYPE zeebe_atomix_receive_latency histogram
zeebe_atomix_receive_latency_bucket{partition="1",le="0.005",} 77711.0
zeebe_atomix_receive_latency_bucket{partition="1",le="0.01",} 103151.0
zeebe_atomix_receive_latency_bucket{partition="1",le="0.025",} 118648.0
zeebe_atomix_receive_latency_bucket{partition="1",le="0.05",} 121371.0
zeebe_atomix_receive_latency_bucket{partition="1",le="0.075",} 121762.0
zeebe_atomix_receive_latency_bucket{partition="1",le="0.1",} 121790.0
zeebe_atomix_receive_latency_bucket{partition="1",le="0.25",} 121792.0
zeebe_atomix_receive_latency_bucket{partition="1",le="0.5",} 121792.0
zeebe_atomix_receive_latency_bucket{partition="1",le="0.75",} 121792.0
zeebe_atomix_receive_latency_bucket{partition="1",le="1.0",} 121793.0
zeebe_atomix_receive_latency_bucket{partition="1",le="2.5",} 121793.0
zeebe_atomix_receive_latency_bucket{partition="1",le="5.0",} 127899.0
zeebe_atomix_receive_latency_bucket{partition="1",le="7.5",} 130004.0
zeebe_atomix_receive_latency_bucket{partition="1",le="10.0",} 130004.0
zeebe_atomix_receive_latency_bucket{partition="1",le="+Inf",} 130004.0
zeebe_atomix_receive_latency_count{partition="1",} 130004.0
zeebe_atomix_receive_latency_sum{partition="1",} 41696.769030247815
```

As you can see the problem lies not in the processing more in the appending to atomix and receiving it in the primitive.

I will further investigate this.

**Comment by Zelldon** [comment] 2019-07-05 10:48
Changed the atomix log level to `DEBUG` and saw a lot of the following sequences:


```
12:42:39.772 [] [raft-partition-group-raft-atomix-5] DEBUG io.atomix.protocols.raft.session.impl.RaftSessionConnection - SessionClient{3}{type=io.zeebe.distributedlog.DistributedLogstreamType@219f41d9, name=distributed-log} - CommandRequest{session=3, sequence=53241, operation=PrimitiveOperation{id=DefaultOperationId{id=append, type=COMMAND}, value=byte[]{length=250, hash=2119083138}}} failed! Reason: java.util.concurrent.TimeoutException: Request type raft-atomix-partition-1-command timed out in 5000 milliseconds
12:42:39.772 [] [raft-server-raft-atomix-partition-1-state] DEBUG io.atomix.cluster.messaging.impl.LocalClientConnection - Received a reply for message id:[54833] but was unable to locate the request handle
12:42:39.772 [] [raft-server-raft-atomix-partition-1-state] DEBUG io.atomix.cluster.messaging.impl.LocalClientConnection - Received a reply for message id:[54834] but was unable to locate the request handle
12:42:39.772 [] [raft-server-raft-atomix-partition-1-state] DEBUG io.atomix.cluster.messaging.impl.LocalClientConnection - Received a reply for message id:[54835] but was unable to locate the request handle
12:42:39.772 [] [raft-partition-group-raft-atomix-5] DEBUG io.atomix.protocols.raft.session.impl.RaftSessionConnection - SessionClient{3}{type=io.zeebe.distributedlog.DistributedLogstreamType@219f41d9, name=distributed-log} - CommandRequest{session=3, sequence=53242, operation=PrimitiveOperation{id=DefaultOperationId{id=append, type=COMMAND}, value=byte[]{length=250, hash=78973903}}} failed! Reason: java.util.concurrent.TimeoutException: Request type raft-atomix-partition-1-command timed out in 5000 milliseconds
```

**Comment by Zelldon** [comment] 2019-07-05 16:10
Was able to reproduce this issue in an atomix unit test, the problem seems to lie in the netty messaging service.

```
  @Test
  public void testSendAndReceive1000() {
    String subject = nextSubject();

    final int workCount = 10_000;
    final CountDownLatch latch = new CountDownLatch(workCount);
    final List<Long> latencies = new ArrayList<>();

    BiFunction<Address, byte[], byte[]> handler = (ep, data) -> {
      final long latency = System.currentTimeMillis() - Long.parseLong(new String(data));
      latencies.add(latency);
      latch.countDown();
      return (latency + "").getBytes();
    };
    netty2.registerHandler(subject, handler, MoreExecutors.directExecutor());

    for (int i = 0; i < workCount; i++){
      netty1.sendAndReceive(address2, subject, (System.currentTimeMillis() + "").getBytes());
    }

    Uninterruptibles.awaitUninterruptibly(latch);

    LOGGER.error("Latencies: {}", latencies);
  }
```

**Comment by npepinpe** [comment] 2019-07-08 08:10
Correct me if I'm wrong, so the issue is that we can flood the messaging service with too many requests such that eventually they all slow down (since there's no backpressure or real timeout on the requests)?

**Comment by Zelldon** [comment] 2019-07-08 08:13
> Correct me if I'm wrong, so the issue is that we can flood the messaging service with too many requests such that eventually they all slow down (since there's no backpressure or real timeout on the requests)?

This would be my current assumption, but I'm not 100% sure. I would like to investigate this further or maybe someone else can take a look might that I missed something before we create an issue on atomix side.

**Comment by npepinpe** [comment] 2019-07-10 15:14
So I'm not sure about the test anymore...primarily because if you add more logs, it seems to be sending almost all requests before even processing a single one (so obviously last ones are slower). If you add the following before you define the `handler`:

```java
    // force initial connection? seems like it
    netty2.registerHandler("connector", (ep, data) -> CompletableFuture.completedFuture(new byte[0]));
    netty1.sendAndReceive(netty2.address(), "connector", new byte[0]).join();
```


Then put a breakpoint on the next line, wait until you see 

```
17:13:15.786 [main] DEBUG i.a.c.messaging.impl.ChannelPool - Connecting to com-camunda-npt470:45167
17:13:15.890 [netty-messaging-event-epoll-client-0] DEBUG i.a.c.m.impl.NettyMessagingService - Writing client protocol version V2 for connection to com-camunda-npt470/192.168.30.69:45167
17:13:15.974 [netty-messaging-event-epoll-client-0] DEBUG i.a.c.m.impl.NettyMessagingService - Activating server protocol version V2 for connection to /192.168.30.69:49420
17:13:15.978 [netty-messaging-event-epoll-client-0] DEBUG i.a.c.m.impl.NettyMessagingService - Activating client protocol version V2 for connection to com-camunda-npt470/192.168.30.69:45167
17:13:15.991 [netty-messaging-event-epoll-client-0] DEBUG i.a.c.messaging.impl.ChannelPool - Connected to com-camunda-npt470/192.168.30.69:45167
```

In the logs...then continue, you get what seem to me to be "normal" latencies. But I'm not 100% sure about what's going on tbh :sweat_smile:

**Comment by Zelldon** [comment] 2019-07-15 08:55
Hey guys,

I had a longer and deeper look in the Atomix raft stuff over the weekend and today. I think I have a fix for the deadlock, for the latency I need another test. 

## Problem

It can happen that we miss a command. I can't explain why, but it happens. Would like to find this out as well.

In `LeaderRole#onCommand` we apply the commands and recognize if one is missing.
As an example say we miss a command on position `X`.
If we see that we missed one we will buffer all other commands which came after the missed position `X`.
After we collect `1000` commands, on the `1000+1` command we will send a `COMMAND_FAILURE` as reply back to the `RaftSessionInvoker`. 
The reply will contain also the last successful applied position `X-1`. The `COMMAND_FAILURE` signals that the `server` received events out-of-order. 

This will trigger the following:

  * The `RaftSessionInvoker` will call `resubmit(`X-1`, attempt);`, where attempt is the command which got an `COMMAND_FAILURE` response.
 * In `resubmit` the operations are retried larger then `X-1`, this includes `X`.
 
 What is the problem with this approach you may think.
 Say we have send `1000+n` commands after the missing command, where `n` is larger then `1`.
 Then on `1000+1` and all following until `1000+n` we get an `COMMAND_FAILURE` response, this means `n` `COMMAND_FAILURE` responses. On each `COMMAND_FAILURE` responses we will retry
`1000+n` operations. This means we will send `n * (1000 + n)` commands. This can cause a lot of traffic and could end in out of memory.


## Fix

I tried a lot, also I thought first is more a concurrency issue.
In the end I concluded that it is not necessary to collect `1000` commands before we send the first `COMMAND_FAILURE`, which means in the fix we will send directly the reply since all other commands are resend anyway. Furthermore the main problem is that `OperationAttempt#retry` retries the commands asynchronously, which then caused a lot of traffic in the end because we were not able to detect if we already retried this operation or not. It is not necessary to send these commands async, in the `RaftSessionInvoker` we only have one thread. If we send it directly in `resubmit` we can check on the next iteration whether the operation was already retried or not.

**Comment by npepinpe** [comment] 2019-07-15 10:40
Great stuff :+1: 

I assumed that "missing" commands was because we may receive them out of order since they're sent asynchronously, so buffering them gives you a bit of time for that missing command to arrive and then you drain all buffered commands. I wouldn't say I'm 100% sure that was his reasoning though :sweat_smile: 

So from what I get the fix is that we now retry operations synchronously (i.e. wait for the operation attempt to complete before sending the next one) as opposed to just retrying them all at once async, and we don't buffer commands to wait for the missing one but rather just immediately reject it.

With the fix, I get the following latency distribution (ran it a bunch of times, no outliers):

```
ghz --insecure --proto ./gateway-protocol/src/main/proto/gateway.proto --call gateway_protocol.Gateway.CreateWorkflowInstance -d '{"workflowKey": 2251799813685249}' -n 2000 localhost:26500

Summary:
  Count:		2000
  Total:		4.01 s
  Slowest:		160.32 ms
  Fastest:		20.37 ms
  Average:		97.32 ms
  Requests/sec:	499.21

Response time histogram:
  20.369 [1]		|
  34.364 [154]	|∎∎∎∎∎∎∎∎∎∎∎∎
  48.359 [95]		|∎∎∎∎∎∎∎∎
  62.354 [27]		|∎∎
  76.349 [63]		|∎∎∎∎∎
  90.344 [241]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  104.339 [506]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  118.334 [433]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  132.330 [317]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  146.325 [117]	|∎∎∎∎∎∎∎∎∎
  160.320 [46]	|∎∎∎∎

Latency distribution:
  10% in 42.83 ms 
  25% in 88.20 ms 
  50% in 101.66 ms 
  75% in 117.69 ms 
  90% in 128.31 ms 
  95% in 140.57 ms 
  99% in 152.56 ms 

Status code distribution:
  [OK]   2000 responses
```

**Comment by Zelldon** [comment] 2019-07-15 11:10
Thanks for checking this, looks promising :+1: 

> I assumed that "missing" commands was because we may receive them out of order since they're sent asynchronously, so buffering them gives you a bit of time for that missing command to arrive and then you drain all buffered commands. I wouldn't say I'm 100% sure that was his reasoning though 

Would make sense, but the commands are really missing :sweat_smile: 

> So from what I get the fix is that we now retry operations synchronously (i.e. wait for the operation attempt to complete before sending the next one) as opposed to just retrying them all at once async, and we don't buffer commands to wait for the missing one but rather just immediately reject it.


Say we have `n` `COMMAND_FAILURES`, then we have `n` resubmit calls:

 * resubmit 1
 * resubmit 2
 * ...
 * resubmit n -1
 * resubmit n

Each resubmit will retry `1000 + n` commands.

 * resubmit 1
   * retry 1
   * retry 2
   * ...
   * retry 1000 + n -1
   * retry 1000 + n
 * ...
 * resubmit n

Each retry was scheduled on the context thread executor. When it is executed it increments the attempt and sends the operation (async again). 
Since the retry was async and we only have one thread all resubmit are executed in order. The resubmits have added `n * (1000 + n)` retry operations to the backlog, where `(n-1) * (1000 + n)` duplicate attempts. 

With the fix I just changed the order of executing a bit. The operation is still send async, but the attempt count is directly incremented. This means on `resubmit 1` we will increment all operation attempts by one. On the second `resubmit` we will not retry the operation since the attempt is already higher.

Hope this makes sense? :)

**Comment by npepinpe** [comment] 2019-07-15 11:14
Ah, yes, ofc. I'm surprised it wasn't like this already, as it looks like the whole point of retrying and comparing attempts was to prevent this.

**Comment by npepinpe** [comment] 2019-07-15 12:02
> Would make sense, but the commands are really missing :sweat_smile: 

You're right, they are completely missing; I think it's a bug, because if I log all requests that come through `onCommand`, the missing ones have previously been seen but for some reason session sequence number was not updated. :thinking:

**Comment by npepinpe** [comment] 2019-07-15 13:33
Ok, so I'd like to get this stuff in the release if possible. What I would propose for now is to push a fix which:

1. Enqueues the retries synchronously, such that the attempts are already incremented and on the second rejected request we don't re-enqueue all of them.
1. Fixes the `setRequestSequence` race condition where we got "missing" requests even with a local connection
1. Fixes race condition with `RaftSessionConnection#currentNode`

I would keep the pending commands buffering in for now, because if we remove that we should probably remove the whole pending commands, and I think we have a better chance of getting our PR merged if we only include "fixes".

**Comment by Zelldon** [comment] 2019-07-16 12:21
Run this test with `100_000` requests and it looks really good. I mean we are no able to handle 230 req/sec on a single partition this is awesome, before is was around 25. I assume we can increase the numbers in our benchmarks :D 

```
[zell zeebe]$  ghz --insecure --proto ./gateway-protocol/src/main/proto/gateway.proto --call gateway_protocol.Gateway.CreateWorkflowInstance -d '{"workflowKey": 2251799813685249}' -n 100000 -q 10 --connections=5 localhost:26500

Summary:
  Count:        100000
  Total:        433.83 s
  Slowest:      700.96 ms
  Fastest:      26.49 ms
  Average:      216.49 ms
  Requests/sec: 230.51

Response time histogram:
  26.494 [1]    |
  93.940 [373]  |
  161.386 [4217]        |∎∎
  228.832 [75988]       |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  296.278 [12383]       |∎∎∎∎∎∎∎
  363.724 [3478]        |∎∎
  431.171 [1892]        |∎
  498.617 [1127]        |∎
  566.063 [310] |
  633.509 [154] |
  700.955 [77]  |

Latency distribution:
  10% in 175.52 ms 
  25% in 191.28 ms 
  50% in 206.42 ms 
  75% in 222.78 ms 
  90% in 257.20 ms 
  95% in 330.70 ms 
  99% in 465.69 ms 

Status code distribution:
  [OK]   100000 responses   
```

I will close this, should be fixed now.

**Comment by Zelldon** [comment] 2019-07-16 20:49
It seems we have still an issue on high load with the processing latency. :thinking: Or maybe I did something wrong.
Run our benchmark with 1000 workflow instance creations per second and 64 workers, no exporting.

![release-20](https://user-images.githubusercontent.com/2758593/61328607-a659d800-a81b-11e9-8541-772ece7781c2.png)
![release-20b](https://user-images.githubusercontent.com/2758593/61328633-b2de3080-a81b-11e9-9206-d024781ff327.png)

**Comment by npepinpe** [comment] 2019-07-17 05:49
I think timing out is expected once we cross a certain threshold, no? Since we have no back pressure, at some point it is just too many events for the system to process and everything starts slowing down? Question is if your test reached our current limit or if again it's an issue :thinking:

**Comment by Zelldon** [comment] 2019-07-17 06:44
BTW with 0.19.0 the latencies look like this (same setup).
![screenshot2019-07-1622:28:53](https://user-images.githubusercontent.com/2758593/61352828-a46d3480-a86e-11e9-8a4b-c6703cc2e489.png)

But there we had the problem that the processing then drops almost to zero because of the `RaftSessionInvoker` bug.

![release19-a](https://user-images.githubusercontent.com/2758593/61352897-cb2b6b00-a86e-11e9-8dfe-adc5cfa56e0a.png)


Yeah Idk maybe it is just to much traffic and since we have no back pressure it looks like this.
The good thing is that we are able to handel/process the events.

**Comment by Zelldon** [comment] 2019-07-17 07:15
We will take a separate look into this again if we implemented backpressure

**Closed by Zelldon** 2019-07-17 07:15 UTC
Labels: Scope: broker, Type: Bug
