### ISSUE TITLE
Allow runables to signal backpressure to actor scheduler

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#701] opened 2018-03-05 10:21 UTC
Currently a task has to call `yield` explicitly to signal back pressure which can be error prone. Instead a task should be able to return a value which signals the actor scheduler that back pressure occurred and the task should not be scheduled immediately again. Similar to `workCount` in old framework. This should be implemented for `consume` and `runUntilDone`.

**Comment by menski** [comment] 2018-03-08 09:58
We will not remove yield to still allow manual control.

**Comment by npepinpe** [comment] 2018-05-08 08:43
So after discussing it, we decided to put this back on hold:

1. The straightforward solution (reusing existing methods by wrapping the runnable/consumer) unfortunately creates garbage
2. Garbage free solution, as far as I can tell, would require adding new invocation methods in the ActorJob class, and to do this cleanly I think it makes more sense for someone with more in-depth knowledge of the Actor framework to do it (or pair it with me). Just blindly adding properties to ActorJob and handling them in invoke would add cognitive load for little benefit in my opinion.
3. As this is a convenience feature and not a product feature, it's probably not worth spending that much time on it yet, though I still think it's a good idea to implement later.

**Comment by npepinpe** [comment] 2018-05-08 09:15
Another solution would be to implement a type which extends both Supplier and Runnable, with the default run() behaviour implemented to handle the different control values.

**Comment by Zelldon** [comment] 2018-05-08 09:30
We could also say that the we have a `Predicate`, which returns a boolean. If the result is true we call done otherwise we yield. See no problem in yielding every time.

I checked the usage of runUntilDone and most of them have this construct of:

```java
if true
 done
else
yield
```

**Comment by npepinpe** [comment] 2018-05-08 09:43
I prefer an explicit type over boolean to better indicate intent, but I wouldn't insist on it if this isn't a common thing in the code base.

For consume, though, from what I understand, you typically would continue doing work and only yield under certain conditions, e.g.

```java
final ServiceEvent serviceEvent = channel.poll();
if (serviceEvent != null)
{
    dependencyResolver.onServiceEvent(serviceEvent);
}
else
{
    actor.yield();
}
```
So in this case boolean might be a little confusing semantically.

With an explicit return type, you can turn the above into a guard clause:

```java
// consumer
final ServiceEvent serviceEvent = channel.poll();
if (serviceEvent == null)
{
  return YIELD;
}

dependencyResolver.onServiceEvent(serviceEvent);
return CONTINUE;
```

Though I can see how in general the issue is more useful for the runUntilDone case.

**Comment by npepinpe** [comment] 2020-05-26 15:48
Not sure if we want to do convenience changes in the actor scheduler at this point in time - I would be in favor of closing this.

**Comment by npepinpe** [comment] 2020-12-04 17:24
Closing as there's no pressure for this at the moment, and I would hold off on non-critical refactoring in the Actor scheduler until we make a decision to commit to it or switch it out.

**Closed by npepinpe** 2020-12-04 17:24 UTC
Labels: Priority: Low, Scope: broker, Status: Ready, Type: Maintenance
