### ISSUE TITLE
Can failed snapshot installation cause OOM Errors?

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4088] opened 2020-03-20 07:29 UTC
**Describe the bug**

I have the feeling that often when the snapshot installation fails it can cause oom errors

```
I 2020-03-20T07:06:14.103450303Z 2020-03-20 07:06:14.103 [] [raft-server-1-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to install 2
 
I 2020-03-20T07:06:14.350363663Z 2020-03-20 07:06:14.350 [] [raft-server-1-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to install 2
 
I 2020-03-20T07:06:14.405583925Z 2020-03-20 07:06:10.211 [] [netty-messaging-event-epoll-client-5] WARN  io.netty.util.concurrent.SingleThreadEventExecutor - Unexpected exception from an event executor: 
 
I 2020-03-20T07:06:14.405619974Z java.lang.OutOfMemoryError: Java heap space
 
I 2020-03-20T07:06:14.405636088Z 2020-03-20 07:06:10.211 [] [netty-messaging-event-epoll-client-7] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
 
I 2020-03-20T07:06:14.405643532Z java.lang.OutOfMemoryError: Java heap space
 
I 2020-03-20T07:06:14.405648420Z 2020-03-20 07:06:10.211 [] [netty-messaging-event-epoll-client-1] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
 
I 2020-03-20T07:06:14.405668469Z java.lang.OutOfMemoryError: Java heap space
 

```

It seems netty catchs them?

**Comment by deepthidevaki** [comment] 2020-03-23 17:41
Observed endless "Failed to Install" in logs. Didn't observe oom. But the broker was shutdown gracefully after sometime. I am assuming it is just k8s rescheduling it.

```
I 2020-03-23T15:24:11.619480314Z 2020-03-23 15:24:11.619 [] [raft-server-2-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to send InstallRequest{currentTerm=2, leader=2, index=11533799, term=2, timestamp=1584977038053, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1865992860}, data=HeapByteBuffer{position=0, remaining=1949, limit=1949, capacity=1949, mark=java.nio.HeapByteBuffer[pos=0 lim=1949 cap=1949], hash=792367769}, initial=true, complete=false} to member 0, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot.
 
I 2020-03-23T15:24:11.624639800Z 2020-03-23 15:24:11.624 [] [raft-server-2-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to send InstallRequest{currentTerm=2, leader=2, index=11533799, term=2, timestamp=1584977038053, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1865992860}, data=HeapByteBuffer{position=0, remaining=1949, limit=1949, capacity=1949, mark=java.nio.HeapByteBuffer[pos=0 lim=1949 cap=1949], hash=792367769}, initial=true, complete=false} to member 0, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot.
 
I 2020-03-23T15:24:11.634944981Z 2020-03-23 15:24:11.634 [] [raft-server-2-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to send InstallRequest{currentTerm=2, leader=2, index=11533799, term=2, timestamp=1584977038053, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1865992860}, data=HeapByteBuffer{position=0, remaining=1949, limit=1949, capacity=1949, mark=java.nio.HeapByteBuffer[pos=0 lim=1949 cap=1949], hash=792367769}, initial=true, complete=false} to member 0, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot.
 
I 2020-03-23T15:24:11.640211884Z 2020-03-23 15:24:11.639 [] [raft-server-2-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to send InstallRequest{currentTerm=2, leader=2, index=11533799, term=2, timestamp=1584977038053, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1865992860}, data=HeapByteBuffer{position=0, remaining=1949, limit=1949, capacity=1949, mark=java.nio.HeapByteBuffer[pos=0 lim=1949 cap=1949], hash=792367769}, initial=true, complete=false} to member 0, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot.
 
I 2020-03-23T15:24:11.641998496Z 2020-03-23 15:24:11.641 [] [raft-server-2-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to send InstallRequest{currentTerm=2, leader=2, index=11533799, term=2, timestamp=1584977038053, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1865992860}, data=HeapByteBuffer{position=0, remaining=1949, limit=1949, capacity=1949, mark=java.nio.HeapByteBuffer[pos=0 lim=1949 cap=1949], hash=792367769}, initial=true, complete=false} to member 0, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot.
 
I 2020-03-23T15:24:11.656336510Z 2020-03-23 15:24:11.656 [] [raft-server-2-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to send InstallRequest{currentTerm=2, leader=2, index=11533799, term=2, timestamp=1584977038053, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1865992860}, data=HeapByteBuffer{position=0, remaining=1949, limit=1949, capacity=1949, mark=java.nio.HeapByteBuffer[pos=0 lim=1949 cap=1949], hash=792367769}, initial=true, complete=false} to member 0, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot.
 
I 2020-03-23T15:24:11.659923557Z 2020-03-23 15:24:11.659 [] [raft-server-2-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to send InstallRequest{currentTerm=2, leader=2, index=11533799, term=2, timestamp=1584977038053, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1865992860}, data=HeapByteBuffer{position=0, remaining=1949, limit=1949, capacity=1949, mark=java.nio.HeapByteBuffer[pos=0 lim=1949 cap=1949], hash=792367769}, initial=true, complete=false} to member 0, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot.
 
I 2020-03-23T15:24:11.667399505Z 2020-03-23 15:24:11.667 [] [raft-server-2-raft-partition-partition-2] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-2} - Failed to send InstallRequest{currentTerm=2, leader=2, index=11533799, term=2, timestamp=1584977038053, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1865992860}, data=HeapByteBuffer{position=0, remaining=1949, limit=1949, capacity=1949, mark=java.nio.HeapByteBuffer[pos=0 lim=1949 cap=1949], hash=792367769}, initial=true, complete=false} to member 0, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot.

```

**Comment by deepthidevaki** [comment] 2020-03-25 14:03
I have now attempted to reproduce this several times, both on the cloud and locally with a docker compose. I could not reproduce it. I would close this issue for now.

If we observe this again, we can reopen it. What will be useful for debugging issues like these are:
1. Snapshot of grafana dashboard.
2. Data directory of the brokers
3. Necessary info to find the logs from gcloud console

**Comment by hisImminence** [comment] 2020-06-19 13:35
Hey @deepthidevaki, thanks for the input! As discussed here the snapshots and logs, going to prepare the `disc snapshots` and provide them as soon as I get them :)

## What we know so far
Since `2020-06-05 02:29 PM` broker-2 of an e2e-test cluster on int, `type: production S`, is frequently restarting. The cool thing is, that the cluster has 3 brokers and could still serve all requests with a monthly yield of 99.98% - even if  availability since then is is only 66% ([dashboard][db-zeebe]):
![image](https://user-images.githubusercontent.com/55736962/85135891-1bf5d180-b23f-11ea-9dc1-081f60932f3e.png)

Crash looping started after node was becoming unready and broker-2 restarted (dashboard):
![image](https://user-images.githubusercontent.com/55736962/85136100-69723e80-b23f-11ea-96a8-66f5c6402664.png)

Since then, broker-2 is not stable anymore and keeps restarting. Before it goes down, the following [error message][errmsg] appears:
```
RaftServer{system-partition-1} - AppendRequest{term=240, leader=1, prevLogIndex=263314, prevLogTerm=240, entries=0, commitIndex=263314} to 2 failed: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.439e397a-b932-430a-8594-dac13c26b1c0-zeebe.svc.cluster.local/10.28.5.20:26502
```

Seeing the connection seemd to be refused from the broker-service, we had a look on the logs and found the following error you saw as well:
```
"RaftServer{raft-partition-partition-1} - Failed to send InstallRequest{currentTerm=284, leader=0, index=304599, term=284, timestamp=1592567415960, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1865337458}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1665856922}, data=HeapByteBuffer{position=0, remaining=825, limit=825, capacity=825, mark=java.nio.HeapByteBuffer[pos=0 lim=825 cap=825], hash=-2065033342}, initial=false, complete=false} to member 2, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot."
```

The "cool" thing is, that this [error][errnew] seemed to have shown up the first time when the pod stared to crash loop:
![image](https://user-images.githubusercontent.com/55736962/85136799-77748f00-b240-11ea-87e6-e1400a08e110.png)

## Provided data
**Logs**
- zeebe [439e397a-b932-430a-8594-dac13c26b1c0-zeebe][logslink]
      - filtered for [ILLEGAL_MEMBER_STATE][ims]

Snapshots from the [zeebe dashboard][lzd], when the error started (2020-06-05 ~02:29 PM CEST) 

**snapshots**
![image](https://user-images.githubusercontent.com/55736962/85135669-c28da280-b23e-11ea-86fc-ef522ace80cd.png)

**atomix**
![image](https://user-images.githubusercontent.com/55736962/85137080-e94cd880-b240-11ea-950b-1764e1f1505b.png)

[ims]:https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22439e397a-b932-430a-8594-dac13c26b1c0-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.message:%22ILLEGAL_MEMBER_STATE%22;timeRange=2020-05-26T22:22:00.000Z%2F2020-06-20T00:00:00.000Z;summaryFields=:true:32:beginning?project=camunda-cloud-240911

[logslink]:https://console.cloud.google.com/logs/viewer?project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-06-05T00:29:00.000000000Z&customFacets=&limitCustomFacetWidth=true&interval=JUMP_TO_TIME&resource=k8s_container%2Fcluster_name%2Fultratest%2Fnamespace_name%2F439e397a-b932-430a-8594-dac13c26b1c0-zeebe%2Fcontainer_name%2Fzeebe&scrollTimestamp=2020-06-05T00:30:45.306000000Z&advancedFilter=(%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22439e397a-b932-430a-8594-dac13c26b1c0-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0A)%0A

[lzd]:https://grafana.internal.ultrawombat.com/d/I4lo7_EZk/zeebe?orgId=1&from=1591340988339&to=1591390089363&var-DS_PROMETHEUS=Prometheus&var-namespace=439e397a-b932-430a-8594-dac13c26b1c0-zeebe&var-pod=zeebe-0&var-pod=zeebe-1&var-pod=zeebe-2&var-partition=All

[errnew]:https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22439e397a-b932-430a-8594-dac13c26b1c0-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.message:%22ILLEGAL_MEMBER_STATE%22;timeRange=2020-05-26T22:22:00.000Z%2F2020-06-20T00:00:00.000Z;summaryFields=:true:32:beginning?project=camunda-cloud-240911
[errmsg]:https://console.cloud.google.com/logs/viewer?project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-06-05T12%3A48%3A00.000000000Z&customFacets&limitCustomFacetWidth=true&interval=JUMP_TO_TIME&resource=k8s_container%2Fcluster_name%2Fultratest%2Fnamespace_name%2F439e397a-b932-430a-8594-dac13c26b1c0-zeebe%2Fcontainer_name%2Fzeebe&scrollTimestamp=2020-06-05T12%3A48%3A55.593000000Z&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.namespace_name%3D%22439e397a-b932-430a-8594-dac13c26b1c0-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Atimestamp%3D%222020-06-05T12%3A48%3A55.593000000Z%22%0AinsertId%3D%22q5voyfhaxt7vpxnvw%22

[db-zeebe]:https://grafana.internal.ultrawombat.com/d/Fsa_ief2/zeebe-per-namespace?orgId=1&from=1591221883660&to=1592572235944&var-ingress=zeebe-ingress&var-namespace=439e397a-b932-430a-8594-dac13c26b1c0-zeebe

**Comment by hisImminence** [comment] 2020-06-22 07:39
Data partitions are mounted on a VM and ssh-access shared with @deepthidevaki and @Zelldon!

**Comment by npepinpe** [comment] 2020-06-22 08:00
Closing in favor of #4784 4784

**Closed** 2020-06-22 08:21 UTC
Labels: Status: Ready, Type: Bug
