### ISSUE TITLE
Not null operator not working in bpmn

### ISSUE THREAD

**Issue by ezolnbl** [zeebe-io/zeebe#4894] opened 2020-07-07 08:09 UTC
**Describe the bug**
Checking a variable for not null is always evaluated to true in case of the variable does not exist.

**To Reproduce**
Simplest workflow with 2 worker that's just print the variables after an exclusive gateway.
![thing](https://user-images.githubusercontent.com/3415684/86744073-a3ae4f00-c039-11ea-9696-3c32bc0d33d2.jpg)
![worker](https://user-images.githubusercontent.com/3415684/86744088-a6a93f80-c039-11ea-81cb-0da433639b6a.jpg)

**Environment:**
 - Zeebe Version: 0.23.2, 0.23.3

**Comment by ezolnbl** [comment] 2020-07-07 08:20
The checking of non existent variable for null is also bad. The expression is evaluating to true.

**Comment by korthout** [comment] 2020-07-07 08:37
Hi @ezolnbl, thanks for sharing this bug. We were already aware of this problem (#4212), but we have not yet worked on a solution. Perhaps we need to re-evaluate the priority of this bug, since it is counter-intuitive. However, there is a workaround you can try:

> check if a variable has a specific type
>```
>if(x instance of string) then x else "default"
>```

For now, I will close this issue as a duplicate of #4212. If you think this is not a duplicate, please re-open the issue.

**Closed by korthout** 2020-07-07 08:37 UTC
Labels: Status: Needs Triage, Type: Bug
