### ISSUE TITLE
Message Start Event of an Event Subprocess is not setting variables and not allowing Output mapping

### ISSUE THREAD

**Issue by nitindileep** [zeebe-io/zeebe#4884] opened 2020-07-04 15:11 UTC
**Describe the bug**
When using an Event Process that is triggered by a message start event (both interrupting and non-interrupting), the variables of the message start event are not accessible to other service task workers following it.

**To Reproduce**
Steps to reproduce the behavior

1. Create a process as depicted in the diagram attached (BPMN also attached as a reference)
2. Trigger the Workflow using zbctl
`zbctl --insecure create instance --variables "{\"id\": 1}" Process_1lahqdt`
3. Complete the instance of service task TriggerJob
`zbctl --insecure create worker service-worker --handler cat`
4. Publish a message to start the first Event Sub workflow
`zbctl --insecure publish message "Message1" --correlationKey 1 --variables "{\"trigger\": \"123\"}"`
5. Observe the output of `Task1`. It doesn't have the variables published with `Message1`
6. Publish message `WaitForTask1`.
`zbctl --insecure publish message "WaitForTask1" --correlationKey 1 --variables "{\"somevar\": \"abc\"}"` 
7. The variables defined by `Message1` appears in scope.
8. Publish message `Message1` again
`zbctl --insecure publish message "Message1" --correlationKey 1 --variables "{\"trigger\": \"789\"}"`
9. Observe output of `Task1`. It shows the older variables.

No matter how many times `WaitForTask1` is published, the newer variables created on `Message1` are never considered in `Task1` after it

[SampleSubProcess.txt](https://github.com/zeebe-io/zeebe/files/4873042/SampleSubProcess.txt)
![SampleSubProcess](https://user-images.githubusercontent.com/16206085/86515345-d5ef5f00-be35-11ea-8ae9-b9bd151ec5a7.png)

If possible add a minimal reproducer code sample
 
The above steps were also performed using Java Client library v0.23.0 and display the same behavior

**Expected behavior**
The service task `Task1` should have access to the variables created on `Message1` event. These variables should also be available for Output mapping on `Message1` as well.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 
No errors in zeebe log

**Environment:**
 - OS: Docker(Engine v 19.03.8) on MacOS Catalina
 - Zeebe Version: 0.23.3
 - Configuration: Default configuration with Hazelcast and Elasticsearch exporter

**Comment by saig0** [comment] 2020-07-06 05:30
@nitindileep, thank you for reporting and providing all the information :+1: 

I can confirm the bug. I see no workaround so far.

**Comment by nitindileep** [comment] 2020-07-08 04:56
Thanks guys for the initial analysis. Any ETA I can hope for?

**Comment by saig0** [comment] 2020-07-08 05:23
@nitindileep, I can not give you a concrete date but we think that it is an import issue and assigned the priority `high` to it. That means we plan to fix it in the next release (`0.25.0` in 3 months). However, when the bug is fixed then we'll also backport the fix to the last two previous versions.

**Comment by saig0** [comment] 2020-07-10 09:25
I just noticed that his issue is a duplicate of #3930

**Closed** 2020-07-13 14:19 UTC
Labels: Impact: Usability, Priority: High, Scope: broker, Severity: High, Status: Needs Review, Type: Bug
