### ISSUE TITLE
KryoException: Unable to find class: Z / R / :

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5886] opened 2020-11-20 12:42 UTC
**Describe the bug**
Observed in error logs in one particular cluster `excitingdev`

https://console.cloud.google.com/errors/CNu5jpier4KD7AE?service=zeebe&time=P7D&project=camunda-cloud-240911
https://console.cloud.google.com/errors/CLej_v7I9-v3hAE?service=zeebe&time=P7D&project=camunda-cloud-240911

It looks like something goes horribly wrong with serialization in this cluster:
![image](https://user-images.githubusercontent.com/14032870/99801020-994aa880-2b35-11eb-8393-e50e25a0926b.png)

(I am posting screenshots here, because when you try to copy some of these stacktraces, it doesn't work. The class name which is displayed as Z is maybe a bunch of control charactorers, sometimes after copying it is converted to SOH. It is really really strange)

![image](https://user-images.githubusercontent.com/14032870/99801243-fd6d6c80-2b35-11eb-9b63-527570ec61d8.png)

<details><summary>Full Stacktrace</summary>
 <p>

```

 java.lang.IllegalStateException: Failed to execute CommandLineRunner

        at io.zeebe.broker.StandaloneBroker.main (StandaloneBroker.java:52)

Caused by: io.zeebe.util.exception.UncheckedExecutionException: Failed to start broker

        at io.zeebe.broker.Broker.internalStart (Broker.java:137)
        at io.zeebe.util.LogUtil.doWithMDC (LogUtil.java:21)
        at io.zeebe.broker.Broker.start (Broker.java:110)
        at io.zeebe.broker.StandaloneBroker.run (StandaloneBroker.java:65)
        at org.springframework.boot.SpringApplication.callRunner (SpringApplication.java:795)

Caused by: java.util.concurrent.CompletionException: com.esotericsoftware.kryo.KryoException: Unable to find class: 

```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.24.3
 - Configuration: Camunda Cloud (somebody said Dev environment, but I don't know why)

**Comment by pihme** [comment] 2020-11-20 12:46
Hint: I have no idea why this happens. 

It is limited to a certain cluster running at 0.24.3.  Maybe the cluster was updated or rolled back to different versions, I don't know.

It looks very much like an experiment gone wrong.

However what is going wrong seems to be that the serialization is reading arbitrary characters and interpreting these as class names.

I chose critical severity as a matter of caution. 

If this is a genuine bug then the impact might be much greater than this version.

**Comment by saig0** [comment] 2021-01-11 07:16
This happened again in a QA cluster running on `0.27.0-SNAPSHOT`: 

![image](https://user-images.githubusercontent.com/4305769/104154395-1df2ce00-53e5-11eb-8781-f06803535e27.png)

```
java.util.concurrent.CompletionException: com.esotericsoftware.kryo.KryoException: Unable to find class: 
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: 
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:190) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:691) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:802) ~[kryo-5.0.3.jar:?]
	at io.atomix.utils.serializer.Namespace.deserialize(Namespace.java:189) ~[atomix-utils-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.MappedJournalSegmentWriter.reset(MappedJournalSegmentWriter.java:219) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.MappedJournalSegmentWriter.<init>(MappedJournalSegmentWriter.java:70) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.JournalSegment.createWriter(JournalSegment.java:169) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.JournalSegment.<init>(JournalSegment.java:61) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal.newSegment(SegmentedJournal.java:493) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal.loadSegment(SegmentedJournal.java:504) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal.loadSegments(SegmentedJournal.java:552) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal.open(SegmentedJournal.java:255) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal.<init>(SegmentedJournal.java:92) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal$Builder.build(SegmentedJournal.java:853) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.storage.log.RaftLog$Builder.build(RaftLog.java:284) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.storage.RaftStorage.openLog(RaftStorage.java:300) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:155) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:322) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:296) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:181) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:151) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:109) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:130) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:202) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:204) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[atomix-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	... 9 more
Caused by: java.lang.ClassNotFoundException: 
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:184) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:691) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:802) ~[kryo-5.0.3.jar:?]
	at io.atomix.utils.serializer.Namespace.deserialize(Namespace.java:189) ~[atomix-utils-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.MappedJournalSegmentWriter.reset(MappedJournalSegmentWriter.java:219) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.MappedJournalSegmentWriter.<init>(MappedJournalSegmentWriter.java:70) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.JournalSegment.createWriter(JournalSegment.java:169) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.JournalSegment.<init>(JournalSegment.java:61) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal.newSegment(SegmentedJournal.java:493) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal.loadSegment(SegmentedJournal.java:504) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal.loadSegments(SegmentedJournal.java:552) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal.open(SegmentedJournal.java:255) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal.<init>(SegmentedJournal.java:92) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal$Builder.build(SegmentedJournal.java:853) ~[atomix-storage-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.storage.log.RaftLog$Builder.build(RaftLog.java:284) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.storage.RaftStorage.openLog(RaftStorage.java:300) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:155) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:322) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:296) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:181) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:151) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:109) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:130) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:202) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:204) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[atomix-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	... 9 more
```

See the logs: https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22e1d1569d-afda-42c1-baea-8d2b42f10c50-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2021-01-11T06:58:31.313680Z%2Fsb7eebg1mu9yf9?project=camunda-cloud-240911

**Comment by MiguelPires** [comment] 2021-01-14 13:24
A couple of thoughts about this:
- The logs show that the broker keeps crashing at the same point so this isn't a transient error, we wrote something corrupted to disk which always makes the broker crash when reading it
- The stacktrace shows Kryo tries to read a class name (hence the weird characters in the exception message). This only happens when the id written at the start of the serialized block is 1. This id is used for unregistered classes, if `Kryo.setRegistrationRequired()` is set to `false`. We require registration so we should never write class names, only registration ids. I double-checked this by inspecting the ids we're using and the smallest id one is 8. This points to an entry being corrupted after serialization.
- The exception also occurs after the entry checksum is (successfully) verified so we know that the log wasn't corrupted after the write which excludes disk corruption.
- I wrote a concurrent serialize/deserialize test but didn't catch any weird behaviors. The pools we use are thread-safe so I wasn't expecting that to be the problem but it's good to double check
- This crash loop lasted several days. During the morning of the 8th of January, similar exceptions happened when deserializing SWIM messages:
```
com.esotericsoftware.kryo.KryoException: Unable to find class: x
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:190) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:691) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:802) ~[kryo-5.0.3.jar:?]
	at io.atomix.utils.serializer.Namespace.deserialize(Namespace.java:169) ~[atomix-utils-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.utils.serializer.Serializer$1.decode(Serializer.java:75) ~[atomix-utils-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.cluster.protocol.SwimMembershipProtocol.lambda$new$2(SwimMembershipProtocol.java:111) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$5(NettyMessagingService.java:202) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: x
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:184) ~[kryo-5.0.3.jar:?]
	... 13 more
```

Ok, so I hadn't realized this was a long running cluster. The previous log statement shows what happened. The problems started  late night on the 7th, a few hours after my Kryo 5 update PR was merged. The SNAPSHOT image was updated with that code and when a node was restarted it had a different (and incompatible) image. Since the expected serialized format was different, we got all of these deserialization exceptions. Ultimately, this was caused by running a cluster with a SNAPSHOT image which can be changed to be incompatible with previous versions

**Closed by MiguelPires** 2021-01-14 13:24 UTC
Labels: Impact: Data, Severity: Critical, Status: Needs Information, Type: Bug

**Comment by npepinpe** [comment] 2021-01-14 13:58
Good catch :muscle:
