### ISSUE TITLE
go client: Failed to activate jobs for worker default rpc error: code = Unknown desc = 

### ISSUE THREAD

**Issue by asaf** [zeebe-io/zeebe#5179] opened 2020-08-15 10:32 UTC
After upgrading to 0.24.1 I suddenly see client producing the following error every 1 second approximately, constantly:

```
Failed to activate jobs for worker default rpc error: code = Unknown desc = 
```

After a restart to the go client, the error is gone. until new flows start

**Environment:**
 - OS: OS/Linux
 - Zeebe Version: 0.24.2
- Go Client: version 0.24.2

**Comment by npepinpe** [comment] 2020-08-17 12:13
Did you see any errors around the same time logged in the Zeebe gateway and/or broker?

**Comment by asaf** [comment] 2020-08-17 12:39
No errors in gw/broker.

I see DEBUGs per service type such (not sure if it's related to the client error):

```
Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"foo","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type foo after timeout of PT10S
```

**Comment by josvegit** [comment] 2020-08-19 11:55
I have the exact same issue, running 0.24.2, eveything works but client keeps logging
Failed to activate jobs for worker default rpc error: code = Unknown desc =

**Comment by josvegit** [comment] 2020-08-19 11:58
It starts right when I start my client, no workflows or anything has been started.

**Comment by asaf** [comment] 2020-08-19 13:11
@josvegit my client is pretty complicated with multi-channels, I wonder if this is happening to you with a simple client as well.

**Comment by josvegit** [comment] 2020-08-19 13:36
my service that uses the client is kinda straightforward and it did not produce this logs in 0.23.X

**Comment by josvegit** [comment] 2020-08-19 20:59
I downgraded to client v0.23.4 it doesn't happen in that one

It did happen in 0.23.5

**Comment by npepinpe** [comment] 2020-08-20 08:27
This looks like a duplicate of https://github.com/zeebe-io/zeebe/issues/5187

**Comment by asaf** [comment] 2020-08-20 09:37
@npepinpe was just about linking those, at least regarding the error being swallowed.

Do you think this is related to `RESOURCE_EXHAUSTED` even though there are not many jobs at all? (seems like it happens to @josvegit even with no flows at all)

Thanks.

**Comment by asaf** [comment] 2020-08-20 11:55
Once I disabled backpressure error is gone,
@josvegit try to disable breakpressure and check if the error is gone for you as well,

If so I think it's safe to say that this is a dup of #5187

**Comment by npepinpe** [comment] 2020-09-22 07:54
Closed as duplicate

**Closed** 2020-09-22 07:54 UTC
Labels: Scope: clients/go, Severity: Mid, Status: Needs Information, Type: Bug

**Comment by josvegit** [comment] 2020-09-28 15:56
still getting this issue with latest zeebe

Failed to activate jobs for worker default rpc error: code = Unknown desc =
Failed to activate jobs for worker default rpc error: code = Unknown desc =
Failed to activate jobs for worker default rpc error: code = Unknown desc =
Failed to activate jobs for worker default rpc error: code = Unknown desc =

**Comment by josvegit** [comment] 2020-09-28 15:58
> Once I disabled backpressure error is gone,
> @josvegit try to disable backpressure and check if the error is gone for you as well,
> 
> If so I think it's safe to say that this is a dup of #5187

How do you mean "disable backpressure" ?

**Comment by asaf** [comment] 2020-09-30 09:17
@josvegit you can disable the backpressure in broker config file
