### ISSUE TITLE
Failed to obtain access token with zbctl

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5865] opened 2020-11-17 16:24 UTC
**Describe the bug**
Run zbctl on different clusters and have an experied token for one.

Output:
```sh
[zell scripts/ ns:testbench]$ ./analysis-completed.sh b735a89d-e037-4291-8fc3-e0008abbb220
++ export ZEEBE_ADDRESS=a8565e6a-e0e7-***.zeebe.ultrawombat.com:443
++ ZEEBE_ADDRESS=a8565e6a-e0e7-***.zeebe.ultrawombat.com:443
++ export ZEEBE_CLIENT_ID=**
++ ZEEBE_CLIENT_ID=**
++ export ZEEBE_CLIENT_SECRET=**
++ ZEEBE_CLIENT_SECRET=**
++ export ZEEBE_AUTHORIZATION_SERVER_URL=https://login.cloud.ultrawombat.com/oauth/token
++ ZEEBE_AUTHORIZATION_SERVER_URL=https://login.cloud.ultrawombat.com/oauth/token
+ zbctl publish message 'Analysis Completed' --correlationKey b735a89d-e037-4291-8fc3-e0008abbb220
2020/11/17 17:17:51 Expected to refresh token after UNAUTHENTICATED response but: failed to obtain access token: context deadline exceeded
null
```

Credentials:
```sh
[zell scripts/ ns:testbench]$ cat ~/.camunda/credentials 
810162a9-1a38-***.zeebe.ultrawombat.com:
  auth:
    credentials:
      accesstoken: eyJhbGciOiJSUzI1NiIsInR****
      tokentype: Bearer
      refreshtoken: ""
      expiry: 2020-11-17T17:39:41.750915027+01:00
a8565e6a-e0e7-***.zeebe.ultrawombat.com:
  auth:
    credentials:
      accesstoken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpX***
      tokentype: Bearer
      refreshtoken: ""
      expiry: 2020-11-14T07:32:11.461161797+01:00
```

Zbctl version: https://github.com/zeebe-io/zeebe/tree/eb43e285f8161fa5db8df7dfbad3fb6b80b7e862
```sh
[zell scripts/ ns:testbench]$ zbctl version
zbctl development (commit: eb43e285)
```
**To Reproduce**
Invalid token

**Expected behavior**
It works.

**Comment by MiguelPires** [comment] 2020-11-18 11:32
I can't reproduce this neither on the commit eb43e285 nor on develop. Was this a persistent failure? Also, why is this a `good first issue`?

**Comment by Zelldon** [comment] 2020-11-18 11:33
Because I hoped this is an easy fix :) Did you had a expired token?

**Comment by MiguelPires** [comment] 2020-11-18 12:17
Yes, I corrupted the token but it was refreshed as you'd expected. Did this happen persistently or was it a one-off?

**Comment by Zelldon** [comment] 2020-11-18 12:21
Currently not sure how often I retried. I deleted the token to overcome this.

**Comment by MiguelPires** [comment] 2020-11-18 12:36
I was thinking that if it was just that one time it might be that the auth server took too long once. We can wait to see if it happens again

**Comment by npepinpe** [comment] 2020-11-23 08:57
I would close this for now as we're unsure if this was expected (i.e. auth0 servers just take too long) or not, and @MiguelPires already tried to reproduce it without success.

**Closed by npepinpe** 2020-11-23 08:57 UTC
Labels: Impact: Usability, Scope: clients/go, Severity: Mid, Status: Needs Priority, Type: Bug, good first issue
