### ISSUE TITLE
Data Recovery in Zeebe

### ISSUE THREAD

**Issue by strawhat5** [zeebe-io/zeebe#5310] opened 2020-09-07 13:51 UTC
**Is your feature request related to a problem? Please describe.**
Currently if an issue occurs (such as #5268) which results in corruption of data, there is no way to recover the old state. In situations like these Zeebe cluster becomes unusable, and we are left with deletion of entire data and running a fresh installation of Zeebe. The data is too precious for the users to just delete, and it contains the complete state of all active instances which is lost forever if data is deleted.

**Describe the solution you'd like**
We would like to have an embedded or external Data Recovery solution in Zeebe, which could help recover the data in cases of data corruption. The best solution would be where the data can be automatically recovered, and the cluster can heal itself. Even if such a solution is not possible, we should be able to manually recover the data by fixing the corrupted entries.

**Describe alternatives you've considered**
Currently, Zeebe has a tightly coupled broker-cum-storage engine. With this architecture, having a data recovery solution looks to be the only way to restore user data. As an alternative Zeebe can have broker and storage decoupled from each other, so that the storage engine can be chosen and managed by the user as per their need. This is nicely covered in #5236.

**Additional context**
This requirement has been covered with several examples and debated in detail on [slack](https://zeebe-io.slack.com/archives/C6WGNHV2A/p1598953024010300). @jwulf also suggested a possible solution similar to having `chkdsk` or `fsck`.
Some reference links for RocksDB repair:
[RocksDB Repairer](https://github.com/facebook/rocksdb/wiki/RocksDB-Repairer)
[Backup RocksDB?](https://rocksdb.org/blog/2014/03/27/how-to-backup-rocksdb.html)
[Persist in-memory RocksDB database](https://rocksdb.org/blog/2014/03/27/how-to-persist-in-memory-rocksdb-database.html#:~:text=Every%20update%20to%20RocksDB%20is,recover%20the%20data%20in%20memtable.)

**Comment by npepinpe** [comment] 2020-09-10 07:20
Hey Ankit, thanks for opening this more formally. I agree that having a data recovery solution is a good feature for us to have - more specifically a point-in-time recovery solution. That's not only useful in case the data becomes corrupted, but it's extremely useful in case your cluster gets bricked by any other bug (e.g. the data is fine, but there's a bug which blocks processing due to the state), where rolling back to a previous known state and avoiding the step that got you into the wrong state is preferrable to recreating the cluster.

iirc in the slack thread you were against back up solutions, is that correct? Because that would be my proposed solution :slightly_smiling_face: It's a fairly common solution that most databases adopt - you take a backup of the data every X minutes so you can always rollback to a known state and miss at most X minutes of data. In theory Zeebe should be able to to work with standard snapshots of your disk - for example, this is how we reproduce some issues from Camunda Cloud users by snapshotting their disks and spinning up a new cluster with the snapshot - so you could roll back to those (I think a user also suggested that in the Slack thread), but we're not actively testing it, so as saying goes, if you're not testing it then you can't say it works :wink: 

I get that you'd rather have something that's simply built into Zeebe, but even with chkdsk, or the RocksDB utils you linked to, there's only so much you can do. We have to differentiate between corrupted data (e.g. checksum mismatch) and wrong data (e.g. wrong position due to a bug, or wrong metadata written). Both are quite hard to fix automatically, and the latter is harder to detect automatically as well. imo I think regular backups of your PVCs is by far the simplest solution - if you're running on k8s >= 1.17, you can simply setup a cron job which will take periodic volume snapshots of your PVCs, and you can then recreate your cluster based on those snapshot. If you've ever operated a database, that's pretty standard where you'll take regular back ups of the data to be able to rollback to point-in-time snapshots.

P.S. I'm marking this as needs info for now as I think it needs a bit of discussion before we prioritize anything :slightly_smiling_face:

**Comment by strawhat5** [comment] 2020-09-10 12:35
Hey Nicolas thanks for taking this discussion ahead.

>you were against back up solutions, is that correct?
>imo I think regular backups of your PVCs is by far the simplest solution

Not really, actually this is exactly what we have started doing as well. We are taking regular snapshots of our PVs so that we can try to recover from a disaster-like situation.

But as you mentioned having a point-in-time recovery solution has its own benefits. More specifically with Zeebe, we need this because Zeebe's storage engine is like a black-box for the users. There is absolutely no way for the users to look into the data and rectify it in case of corruption. That is fairly easy if it is an external storage engine where users have a good understanding of the state and if push comes to shove they can fix it manually (that is also one of the advantages of having a decoupled storage 😉, where user can choose a well-known storage engine which best fits their need).

So there are limits to what we can do with regular snapshotting of PVs. And restoring data from an old snapshot also creates data inconsistency issues for non-idempotent clients. I understand not all these problems can be tackled by a data recovery tool, but a recovery solution coming from the team which best understands Zeebe's state is the best we can hope for. 🙂

**Comment by cameronbraid** [comment] 2020-09-17 04:44
Is a filesystem copy a reliable way to snapshot zeebe, or would you have to use something like lvm or https://longhorn.io/ for pv ?

**Comment by npepinpe** [comment] 2020-09-17 07:03
I've never used Longhorn in production, so I can't comment on how good it is, but it should work in theory. Like I mentioned, if you're on Kubernetes 1.17+ and your provider supports it, you could just do volume snapshots (e.g. here's the [GKE link](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/volume-snapshots)), which should work. We regularly use this to recreate customer clusters and reproduce bugs, and so far it's worked well, but as we're not testing this in an automated way I can't guarantee you won't run into any snags. In theory though, taking snapshots of your PVCs should be the same as restarting Zeebe from a crashed container, so we expect it to work.

**Comment by npepinpe** [comment] 2021-01-03 18:21
After some discussion, the only way to keep a consistent snapshot of a cluster is to pause the cluster. The reason is that you want to maintain a consistent view of your cluster - if you take snapshots at different point in time, it's not clear that you will have that when you restore from them. So for now, I would not recommend doing online or "hot" backups.

You can do so in 0.25+ by using the admin endpoints on the monitoring port (by default 9600): `/actuator/partitions/pauseProcessing` and `/actuator/partitions/pauseExporting`. These are persisted to handle random restarts, so make sure to call `/actuator/partitions/resumeProcessing` and `/actuator/partitions/resumeExporting` once you finish the snapshots.

Once everything is paused, you can query `/actuator/partitions` and you will see that all leaders report a stream processor phase of `PAUSED`. Then you can take a snapshot of your PVC, and your cluster will be consistent once you restart from these.

Another option is to simply scale your `StatefulSet` to 0, take a snapshot of the PVCs, then scale it back (this is how we do it ourselves for now). This is simpler operationally, so I would recommend doing that, but it may depend on your cloud provider.

We will work on hot snapshots eventually, that's a no brainer, but for now we don't have the resources.

**Comment by npepinpe** [comment] 2021-01-03 18:25
Finally, having a pluggable storage engine means two things - having a pluggable append-only-log storage engine, and a pluggable state/embedded DB storage. These are heavily coupled with the performance of Zeebe, so it's unlikely we (as in, the core team) will ever officially support more than one. I can see though the use for having pluggable interfaces where users can add their own - I believe we've almost got this with the state one (see the `zb-db` module), though the snapshot replication is somewhat coupled to RocksDB (which we will hopefully fix). In either case, it requires a custom build of Zeebe, as opposed to an official public API. I don't see that happening any time soon, unfortunately, we just don't have the resources, and wouldn't have them to maintain even if somebody else were to contribute these.

I will close this for now, but I'm happy to discuss this more over Slack or the forums.

**Closed by npepinpe** 2021-01-03 18:25 UTC
Labels: Impact: Data, Scope: broker, Status: Needs Information, Type: Enhancement

**Comment by strawhat5** [comment] 2021-01-05 12:42
>You can do so in 0.25+ by using the admin endpoints on the monitoring port
>Another option is to simply scale your StatefulSet to 0, take a snapshot of the PVCs, then scale it back

@npepinpe Both options require a downtime, so I agree that hot snapshots would be essentially required. Also without hot snapshots, we cannot mitigate inconsistencies arising due to random broker restarts (we have faced this already on `0.25.3`!).
