### ISSUE TITLE
IllegalStateException: Failed to execute CommandLineRunner

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5549] opened 2020-10-08 12:26 UTC
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CImxzMiKoOOs3gE?service=zeebe&time=P7D&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:52) [zeebe-distribution-0.24.2.jar:0.24.2]
Caused by: io.zeebe.util.exception.UncheckedExecutionException: Failed to start broker
	at io.zeebe.broker.Broker.internalStart(Broker.java:137) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.broker.Broker.start(Broker.java:110) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:65) ~[zeebe-distribution-0.24.2.jar:0.24.2]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	... 5 more
Caused by: java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:32) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:201) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.broker.Broker.scheduleActor(Broker.java:263) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.Broker.lambda$partitionsStep$18(Broker.java:328) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:60) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:58) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:43) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.Broker.partitionsStep(Broker.java:334) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.Broker.lambda$initStart$9(Broker.java:179) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:60) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:58) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:43) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.Broker.internalStart(Broker.java:130) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.broker.Broker.start(Broker.java:110) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:65) ~[zeebe-distribution-0.24.2.jar:0.24.2]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	... 5 more
```

</p>
</details>

**Environment:**
Camunda Cloud / Prod / 0.24.3

**Comment by npepinpe** [comment] 2020-11-16 08:38
Closing as duplicate of https://github.com/zeebe-io/zeebe/issues/5549

**Comment by Zelldon** [comment] 2020-11-16 08:39
@npepinpe I think you referenced the wrong issue :)

**Closed by npepinpe** 2020-11-16 08:38 UTC
Labels: Status: Needs Triage, Type: Bug

**Comment by npepinpe** [comment] 2020-11-16 08:40
Haha you're right :see_no_evil: Meant this one https://github.com/zeebe-io/zeebe/issues/5755
