### ISSUE TITLE
Allow to interrupt services in the starting phase 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#824] opened 2018-04-24 08:09 UTC
When a service is waiting for something to complete in the starting phase it is not possible to interrupt this at the moment. Examples for service which wait for something which may not happen in the starting phase are the raft join and initial event committed service. In this case the raft service cannot be closed without a timeout.

It should be possible for a service to indicate that the async run might be interrupted by the service container. To make the interruption discoverable by the service it self either add a flag to the stop context or the a new method `interrupted` which is called if the service was interrupted.

**Comment by npepinpe** [comment] 2018-05-09 13:19
I implemented the interruptible part for RaftJoinService, but I wasn't entirely sure about where to start with the initial commit event; it can still be done as part of this issue, just reassign it to me and point me in the right direction (or we just take 5 minutes to check it out together).

In general though the issue can already be reviewed, I think.

**Comment by menski** [comment] 2018-05-16 07:30
Remaining tasks:
- use interruptible feature for LeaderCommitInitalEvent service
   https://github.com/zeebe-io/zb-raft/blob/01b910ef5b20ed52c9ff170fc77ba048964521e5/src/main/java/io/zeebe/raft/controller/LeaderCommitInitialEvent.java#L59
- write test to ensure that the LeaderCommitInitalEvent service can be interrupted during starting phase

@npepinpe if you want we can try to figure out a way how to test this together, just let me know

**Comment by npepinpe** [comment] 2018-05-16 09:53
As discussed, no test was added since it's complicated to reproduce the conditions necessary to get the LeaderCommitInitialEvent service stuck in the await start state.

**Closed** 2018-05-17 14:09 UTC
Labels: code, enhancement, needs review, service-container
