### ISSUE TITLE
BrokerReprocessingTest#shouldAssignUniqueIncidentKeyAfterRestart unstable

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3874] opened 2020-02-19 11:59 UTC
**Description**

It seems that an incident is not created in time or the workflow is stuck.

Test failes at `assertIncidentCreated();` with message:

```
Error
expected:<[tru]e> but was:<[fals]e>
Stacktrace
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.zeebe.broker.it.util.ZeebeAssertHelper.assertIncidentCreated(ZeebeAssertHelper.java:59)
	at io.zeebe.broker.it.startup.BrokerReprocessingTest.shouldAssignUniqueIncidentKeyAfterRestart(BrokerReprocessingTest.java:519)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

These events are created:
```
11:42:05.482 [] [Time-limited test] INFO  io.zeebe.broker.test - Client Rule assumption: Test execution time: 8081
11:42:05.484 [] [Time-limited test] INFO  io.zeebe.broker.test - Client closing time: 2
11:42:05.484 [] [Time-limited test] INFO  io.zeebe.test.records - Test failed, following records where exported:
11:42:05.518 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":-1,"position":4294967296,"timestamp":1582112517410,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfMDBkNWEyMzAtNzQ2OS00N2Y0LWEwMzctYTE3NGExNzRmZWRhIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93X2MyZmI5MTNiLTg2ODAtNDllZC1hZTY3LTMxYTcxOTUzZjljZTwvb3V0Z29pb...
11:42:05.520 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":4294970168,"timestamp":1582112517657,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfMDBkNWEyMzAtNzQ2OS00N2Y0LWEwMzctYTE3NGExNzRmZWRhIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93X2MyZmI5MTNiLTg2ODAtNDllZC1hZTY3LTMxYTcxOTUzZjlj...
11:42:05.520 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":4294973136,"timestamp":1582112517864,"recordType":"COMMAND","intent":"DISTRIBUTE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfMDBkNWEyMzAtNzQ2OS00N2Y0LWEwMzctYTE3NGExNzRmZWRhIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93X2MyZmI5MTNiLTg2ODAtNDllZC1hZTY3LTMxYTcxOTU...
11:42:05.521 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":4294976104,"timestamp":1582112518098,"recordType":"EVENT","intent":"DISTRIBUTED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfMDBkNWEyMzAtNzQ2OS00N2Y0LWEwMzctYTE3NGExNzRmZWRhIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93X2MyZmI5MTNiLTg2ODAtNDllZC1hZTY3LTMxYTcxOTUz...
11:42:05.524 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":-1,"position":4294979072,"timestamp":1582112518301,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":-1,"workflowInstanceKey":-1,"workflowKey":0,"bpmnProcessId":"process","variables":{}},"sourceRecordPosition":-1}
11:42:05.527 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685251,"position":4294979256,"timestamp":1582112518695,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685251,"workflowKey":2251799813685249,"bpmnProcessId":"process","elementId":"process","parentElementInstanceKey":-1,"parentWorkflowInstanceKey":-1,"bpmnElementType":"PROCESS","flowScopeKey":-1},"sourceRecordPosition":4294979072}
11:42:05.527 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":2251799813685252,"position":4294979536,"timestamp":1582112518695,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685251,"workflowKey":2251799813685249,"bpmnProcessId":"process","variables":{}},"sourceRecordPosition":4294979072}
11:42:05.527 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685251,"position":4294979752,"timestamp":1582112519269,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685251,"workflowKey":2251799813685249,"bpmnProcessId":"process","elementId":"process","parentElementInstanceKey":-1,"parentWorkflowInstanceKey":-1,"bpmnElementType":"PROCESS","flowScopeKey":-1},"sourceRecordPosition":4294979256}
11:42:05.527 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":4294980048,"timestamp":1582112519502,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685251,"workflowKey":2251799813685249,"bpmnProcessId":"process","elementId":"start","parentElementInstanceKey":-1,"parentWorkflowInstanceKey":-1,"bpmnElementType":"START_EVENT","flowScopeKey":2251799813685251},"sourceRecordPosition":4294979752}
11:42:05.527 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":4294980352,"timestamp":1582112519993,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"workflowInstanceKey":2251799813685251,"workflowKey":2251799813685249,"bpmnProcessId":"process","elementId":"start","parentElementInstanceKey":-1,"parentWorkflowInstanceKey":-1,"bpmnElementType":"START_EVENT","flowScopeKey":2251799813685251},"sourceRecordPosition":4294980048}
11:42:05.527 [] [Time-limited test] INFO  io.zeebe.broker.test - Test execution time: 8128
```

**Comment by saig0** [comment] 2020-03-10 07:51
I can not reproduce the test failure locally. 

Looking at the test output, it seems that the execution (or test recording) stoped after the start event was activated. This is odd :confused: 

Let's wait until this happens again and continue with the investigation.

**Comment by npepinpe** [comment] 2020-03-25 16:43
If this has not happened since then, I would propose to close it for now.

**Closed by npepinpe** 2020-03-25 16:43 UTC
Labels: Type: Maintenance, Type: Unstable Test
