### ISSUE TITLE
Speed of creating workflow instances drops significantly with higher Zeebe versions

### ISSUE THREAD

**Issue by PinoNTK** [zeebe-io/zeebe#5639] opened 2020-10-20 11:28 UTC
Hi, we are currently using Zeebe version 0.22.5 after upgrading from Zeebe version 0.21.0-alpha3 and trying to run benchmarks on it but the results are not what we expected. With each version, we run the following test command:
```
 /home/debian/ghz/cmd/ghz/ghz --insecure --proto ./gateway-protocol/src/main/proto/gateway.proto --call gateway_protocol.Gateway.CreateWorkflowInstance -d '{"workflowKey": 2251799813685252}' -n 1000 localhost:8500 
```
and get the following results:
- __Version 0.21.0-alpha3__
![Screenshot from 2020-10-20 16-43-35](https://user-images.githubusercontent.com/26008333/96578650-b8b8a080-12ff-11eb-854e-7378fafebb78.png)
__CPU usage__
![Screenshot from 2020-10-20 16-40-58](https://user-images.githubusercontent.com/26008333/96578679-cb32da00-12ff-11eb-992d-c5cf805ceae2.png)
- __Version 0.25.x__
![Screenshot from 2020-10-20 17-11-24](https://user-images.githubusercontent.com/26008333/96578732-e0a80400-12ff-11eb-8505-f018899e412f.png)
__CPU usage__
![Screenshot from 2020-10-20 17-11-12](https://user-images.githubusercontent.com/26008333/96578764-ef8eb680-12ff-11eb-84ac-d1313d4602de.png)

We are running the benchmarks on a server with **16 CPUs, 16G RAM, HDD disk**. It is surprising that the speed drops dramatically with later versions. We tested with various versions from 0.22.x to 0.25.x and it gradually slows down.

From the results, It seems that the engine in later versions does not make use of CPUs (the CPU consumption is quite low), which results in a bad performance.

Are we missing some configs? Please give us some suggestions and explanations.
Here is our config for benchmarking: [application.yaml](https://github.com/PinoNTK/zeebe/blob/main/zeebe_default_origin.yaml)

**Comment by Zelldon** [comment] 2020-10-21 07:11
Hey @PinoNTK 

thanks for reporting this. 

We are aware of that and currently working on improving the situation. The next release (0.25.0) allows you to use memory mapped file again, which will improve the situation. See related issue https://github.com/zeebe-io/zeebe/issues/4274.
We have several other issues open which should improve the performance, you can find them via searching for the label [Impact: Performance.](https://github.com/zeebe-io/zeebe/labels/Impact%3A%20Performance).

Since this seems to me like a duplicate of https://github.com/zeebe-io/zeebe/issues/4942 I will close this.

Greets
Chris

**Closed by Zelldon** 2020-10-21 07:11 UTC
Labels: Status: Needs Triage, Type: Unstable Test
