### ISSUE TITLE
is there any way to listen to the workflow "end" event and do some business logic?

### ISSUE THREAD

**Issue by bboylilshaw** [zeebe-io/zeebe#2982] opened 2019-08-16 04:06 UTC
is there any way to listen to the workflow "end" event and do some business logic?

**Comment by jwulf** [comment] 2019-08-17 14:58
See: https://zeebe.io/blog/2019/08/zeebe-rest-affinity/

Duplicate of https://github.com/zeebe-io/zeebe/issues/2896

**Closed** 2019-08-19 05:50 UTC
Labels: Type: Enhancement
